var searchData=
[
  ['dc_3a_3a_20prefix_0',['21. Why do I have to use the &lt;span class=&quot;tt&quot;&gt;dc::&lt;/span&gt; prefix?',['../group__tutorial-faq.html#faq_prefix',1,'']]],
  ['dc_3a_3acontinued_20and_20dc_3a_3afinish_1',['Using continued_cf, dc::continued and dc::finish',['../group__nesting-debug-output.html#using_continued',1,'']]],
  ['dc_3a_3afinish_2',['Using continued_cf, dc::continued and dc::finish',['../group__nesting-debug-output.html#using_continued',1,'']]],
  ['dc_3a_3anotice_20hello_20world_3',['&lt;span class=&quot;tt&quot;&gt;Dout(dc::notice, &quot;Hello World&quot;);&lt;/span&gt;',['../group__tutorial-hello-world.html#autotoc_md134',1,'']]],
  ['dc_3a_3anotice_20on_4',['&lt;span class=&quot;tt&quot;&gt;Debug(dc::notice.on());&lt;/span&gt;',['../group__tutorial-hello-world.html#tutorial_hello_world_turn_on_channel',1,'']]],
  ['debug_5',['Debug',['../debug_8h.html#acd8dd41e8a67bba7ccfb3b50f7aa88a5',1,'debug.h']]],
  ['debug_6',['debug',['../group__predefined-debug-channels.html#ga110eb8734c35fc3bcbbc1ef6047c98b7',1,'libcwd::channels::dc']]],
  ['debug_20and_20dout_7',['5. Why are you using macros for &lt;span class=&quot;tt&quot;&gt;Debug&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;Dout&lt;/span&gt;?',['../group__tutorial-faq.html#faq_macros',1,'']]],
  ['debug_20around_20it_8',['6. Why do I need to type the &lt;span class=&quot;tt&quot;&gt;Debug(  )&lt;/span&gt; around it?',['../group__tutorial-faq.html#faq_debug',1,'']]],
  ['debug_20channel_9',['9. Why do you call it a Debug &lt;em&gt;Channel&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Channel?',['../group__tutorial-faq.html#faq_channel',1,'']]],
  ['debug_20channel_20and_20or_20debug_20object_20are_20turned_20off_10',['18. Is the second field of the macro still evaluated when the Debug Channel and/or Debug Object are turned off?',['../group__tutorial-faq.html#faq_evaluation',1,'']]],
  ['debug_20channel_20name_20collisions_11',['Debug channel name collisions',['../group__the-custom-debug-h-file.html#debug_channel_name_collisions',1,'']]],
  ['debug_20channel_20what_20is_20a_20debug_20channel_12',['9. Why do you call it a Debug &lt;em&gt;Channel&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Channel?',['../group__tutorial-faq.html#faq_channel',1,'']]],
  ['debug_20channel_20why_20not_20the_20other_20way_20around_13',['14. Why do you turn on the debug object after you enable a debug channel, why not the other way around?',['../group__tutorial-faq.html#faq_order',1,'']]],
  ['debug_20channels_14',['Debug Channels',['../group__controlling-the-output-level-debug-channels.html',1,'Controlling The Output Level (Debug Channels)'],['../group__predefined-debug-channels.html',1,'Predefined Debug Channels'],['../group__tutorial-advanced.html#tutorial_advanced_running',1,'Running over all Debug Channels'],['../group__tutorial-channels.html',1,'Tutorial 2: Creating Your Own Debug Channels']]],
  ['debug_20channels_20and_20name_20spaces_15',['Debug Channels and name spaces',['../group__tutorial-advanced.html#tutorial_advanced_debug',1,'']]],
  ['debug_20channels_20and_20namespace_16',['Debug channels and namespace',['../group__the-custom-debug-h-file.html#debug_channels_and_namespace',1,'']]],
  ['debug_20channels_20exist_20can_20i_20make_20my_20own_17',['7. Which Debug Channels exist? Can I make my own?',['../group__tutorial-faq.html#faq_debugchannels',1,'']]],
  ['debug_20channels_20in_20my_20own_20name_20space_18',['22. Can I put my debug channels in my own name space?',['../group__tutorial-faq.html#faq_ownnamespace',1,'']]],
  ['debug_20channels_20off_20again_20can_20i_20do_20that_20recursively_19',['8. Can I turn Debug Channels off again? Can I do that recursively?',['../group__tutorial-faq.html#faq_recursive',1,'']]],
  ['debug_20dc_3a_3anotice_20on_20',['&lt;span class=&quot;tt&quot;&gt;Debug(dc::notice.on());&lt;/span&gt;',['../group__tutorial-hello-world.html#tutorial_hello_world_turn_on_channel',1,'']]],
  ['debug_20h_21',['4. What is defined &lt;em&gt;exactly&lt;/em&gt; in &lt;span class=&quot;tt&quot;&gt;libcwd/debug.h&lt;/span&gt;?',['../group__tutorial-faq.html#faq_debug_h',1,'']]],
  ['debug_20h_20file_22',['The Custom &quot;debug.h&quot; File',['../group__the-custom-debug-h-file.html',1,'']]],
  ['debug_20libcw_5fdo_20on_23',['&lt;span class=&quot;tt&quot;&gt;Debug(libcw_do.on());&lt;/span&gt;',['../group__tutorial-hello-world.html#autotoc_md133',1,'']]],
  ['debug_20namespace_5fdebug_3a_3ainit_24',['&lt;span class=&quot;tt&quot;&gt;Debug(NAMESPACE_DEBUG::init());&lt;/span&gt;',['../group__tutorial-hello-world.html#tutorial_hello_world_main_reached',1,'']]],
  ['debug_20object_25',['Debug Object',['../group__tutorial-faq.html#faq_owndebugobject',1,'10. Can I make my own Debug Object?'],['../group__tutorial-faq.html#faq_setostream',1,'12. How do I set a new &lt;span class=&quot;tt&quot;&gt;ostream&lt;/span&gt; for a given Debug Object?'],['../group__tutorial-faq.html#faq_object',1,'15. Why do you call it a Debug &lt;em&gt;Object&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Object?'],['../group__the-output-device-debug-object.html',1,'The Output Device (Debug Object)']]],
  ['debug_20object_26',['Methods of the debug object',['../group__tutorial-advanced.html#tutorial_advanced_methods',1,'']]],
  ['debug_20object_20after_20you_20enable_20a_20debug_20channel_20why_20not_20the_20other_20way_20around_27',['14. Why do you turn on the debug object after you enable a debug channel, why not the other way around?',['../group__tutorial-faq.html#faq_order',1,'']]],
  ['debug_20object_20are_20turned_20off_28',['18. Is the second field of the macro still evaluated when the Debug Channel and/or Debug Object are turned off?',['../group__tutorial-faq.html#faq_evaluation',1,'']]],
  ['debug_20object_20can_20i_20still_20use_20dout_29',['17. I made my own Debug Object, can I still use &lt;span class=&quot;tt&quot;&gt;Dout&lt;/span&gt;?',['../group__tutorial-faq.html#faq_libcwdout',1,'']]],
  ['debug_20object_20what_20is_20a_20debug_20object_30',['15. Why do you call it a Debug &lt;em&gt;Object&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Object?',['../group__tutorial-faq.html#faq_object',1,'']]],
  ['debug_20objects_31',['Custom Debug Objects',['../group__custom-debug-objects.html',1,'']]],
  ['debug_20objects_20off_20again_20can_20i_20do_20that_20recursively_32',['11. Can I turn Debug Objects off again? Can I do that recursively?',['../group__tutorial-faq.html#faq_recursive2',1,'']]],
  ['debug_20objects_20turned_20off_20at_20creation_33',['13. Why are Debug Objects turned off at creation?',['../group__tutorial-faq.html#faq_whyoff',1,'']]],
  ['debug_20output_34',['Debug Output',['../quick-reference.html#autotoc_md6',1,'Debug Output'],['../group__fatal-debug-output.html',1,'Fatal Debug Output'],['../group__format-of-the-debug-output.html',1,'Format Of The Debug Output'],['../group__book__writing__intro.html',1,'Introduction (Debug Output)'],['../group__nesting-debug-output.html',1,'Nesting Debug Output'],['../group__reference-manual-writing-debug-output.html',1,'Writing Debug Output']]],
  ['debug_20output_35',['Formatting debug output',['../group__tutorial-advanced.html#tutorial_advanced_formatting',1,'']]],
  ['debug_2eh_36',['debug.h',['../debug_8h.html',1,'']]],
  ['debugging_20threaded_20applications_37',['Tutorial 6: Debugging Threaded Applications',['../group__tutorial-threads.html',1,'']]],
  ['debugobject_38',['DebugObject',['../classlibcwd_1_1DebugObject.html',1,'libcwd::DebugObject'],['../classlibcwd_1_1DebugObject.html#aa3d00391adaa6cbc864a661766b1c108',1,'libcwd::DebugObject::DebugObject()']]],
  ['debugobject_2eh_39',['DebugObject.h',['../DebugObject_8h.html',1,'']]],
  ['debugstack_2eh_40',['DebugStack.h',['../DebugStack_8h.html',1,'']]],
  ['debugstring_41',['DebugString',['../classlibcwd_1_1DebugString.html',1,'libcwd']]],
  ['debugstring_2eh_42',['DebugString.h',['../DebugString_8h.html',1,'']]],
  ['dec_202005_43',['13 Dec 2005',['../release-notes.html#autotoc_md31',1,'']]],
  ['dec_5findent_44',['dec_indent',['../group__format-of-the-debug-output.html#gaf2cca18d43fa8d638b4ee22e5b545665',1,'libcwd::DebugObject']]],
  ['define_20make_20my_20code_20non_20portable_45',['1. Won&apos;t this define make my code non-portable?',['../group__tutorial-faq.html#faq_gnu_source',1,'']]],
  ['defined_20exactly_20in_20libcwd_20debug_20h_46',['4. What is defined &lt;em&gt;exactly&lt;/em&gt; in &lt;span class=&quot;tt&quot;&gt;libcwd/debug.h&lt;/span&gt;?',['../group__tutorial-faq.html#faq_debug_h',1,'']]],
  ['defining_47',['Defining',['../group__function-objects.html#autotoc_md128',1,'']]],
  ['defining_20and_20initializing_20function_20objects_48',['Defining and initializing &lt;span class=&quot;tt&quot;&gt;Function&lt;/span&gt; objects',['../group__function-objects.html#autotoc_md127',1,'']]],
  ['demangle_2eh_49',['demangle.h',['../demangle_8h.html',1,'']]],
  ['demangle_5fsymbol_50',['demangle_symbol',['../group__demangle__type-and-demangle__symbol.html#ga07fe6e4a67d89d15efad26b49f891b10',1,'libcwd::demangle_symbol()'],['../group__demangle__type-and-demangle__symbol.html',1,'demangle_type() and demangle_symbol()']]],
  ['demangle_5ftype_51',['demangle_type',['../group__demangle__type-and-demangle__symbol.html#gae2a72d78552cbfe2ca8b33f871b0a3a0',1,'libcwd']]],
  ['demangle_5ftype_20and_20demangle_5fsymbol_52',['demangle_type() and demangle_symbol()',['../group__demangle__type-and-demangle__symbol.html',1,'']]],
  ['demangled_5fname_53',['demangled_name',['../classlibcwd_1_1TypeInfo.html#acf54a554237cbd0e106260837cc772a1',1,'libcwd::TypeInfo']]],
  ['demangled_5fname_5f_54',['demangled_name_',['../classlibcwd_1_1TypeInfo.html#a1b87a9087b44942d4774bb84fca1737f',1,'libcwd::TypeInfo']]],
  ['dereferenced_5ftype_5fsize_5f_55',['dereferenced_type_size_',['../classlibcwd_1_1TypeInfo.html#a577cf3cdea5228d87f0595fffe53eeac',1,'libcwd::TypeInfo']]],
  ['destination_56',['Setting The Output Destination',['../group__setting-the-output-destination.html',1,'']]],
  ['determined_57',['23. Why does it print spaces between the label and the colon? How is the field width of the label determined?',['../group__tutorial-faq.html#faq_labelwidth',1,'']]],
  ['device_20debug_20object_58',['The Output Device (Debug Object)',['../group__the-output-device-debug-object.html',1,'']]],
  ['do_20i_20have_20to_20use_20the_20dc_3a_3a_20prefix_59',['21. Why do I have to use the &lt;span class=&quot;tt&quot;&gt;dc::&lt;/span&gt; prefix?',['../group__tutorial-faq.html#faq_prefix',1,'']]],
  ['do_20i_20need_20to_20type_20that_20semi_20colon_20after_20the_20macro_20why_20isn_20t_20it_20part_20of_20the_20macro_60',['16. Do I need to type that semi-colon after the macro? Why isn&apos;t it part of the macro?',['../group__tutorial-faq.html#faq_semicolon',1,'']]],
  ['do_20i_20need_20to_20type_20the_20debug_20around_20it_61',['6. Why do I need to type the &lt;span class=&quot;tt&quot;&gt;Debug(  )&lt;/span&gt; around it?',['../group__tutorial-faq.html#faq_debug',1,'']]],
  ['do_20i_20set_20a_20new_20ostream_20for_20a_20given_20debug_20object_62',['12. How do I set a new &lt;span class=&quot;tt&quot;&gt;ostream&lt;/span&gt; for a given Debug Object?',['../group__tutorial-faq.html#faq_setostream',1,'']]],
  ['do_20that_20recursively_63',['do that recursively',['../group__tutorial-faq.html#faq_recursive2',1,'11. Can I turn Debug Objects off again? Can I do that recursively?'],['../group__tutorial-faq.html#faq_recursive',1,'8. Can I turn Debug Channels off again? Can I do that recursively?']]],
  ['do_20you_20call_20it_20a_20debug_20channel_20what_20is_20a_20debug_20channel_64',['9. Why do you call it a Debug &lt;em&gt;Channel&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Channel?',['../group__tutorial-faq.html#faq_channel',1,'']]],
  ['do_20you_20call_20it_20a_20debug_20object_20what_20is_20a_20debug_20object_65',['15. Why do you call it a Debug &lt;em&gt;Object&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Object?',['../group__tutorial-faq.html#faq_object',1,'']]],
  ['do_20you_20turn_20on_20the_20debug_20object_20after_20you_20enable_20a_20debug_20channel_20why_20not_20the_20other_20way_20around_66',['14. Why do you turn on the debug object after you enable a debug channel, why not the other way around?',['../group__tutorial-faq.html#faq_order',1,'']]],
  ['documentation_67',['Documentation',['../index.html#autotoc_md2',1,'']]],
  ['does_20it_20print_20spaces_20between_20the_20label_20and_20the_20colon_20how_20is_20the_20field_20width_20of_20the_20label_20determined_68',['23. Why does it print spaces between the label and the colon? How is the field width of the label determined?',['../group__tutorial-faq.html#faq_labelwidth',1,'']]],
  ['dout_69',['Dout',['../group__tutorial-faq.html#faq_libcwdout',1,'17. I made my own Debug Object, can I still use &lt;span class=&quot;tt&quot;&gt;Dout&lt;/span&gt;?'],['../group__tutorial-faq.html#faq_macros',1,'5. Why are you using macros for &lt;span class=&quot;tt&quot;&gt;Debug&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;Dout&lt;/span&gt;?'],['../group__nesting-debug-output.html#section_nesting_calling',1,'Calling functions inside Dout'],['../debug_8h.html#a259ef5a9eab0830909e9e20b42380dd3',1,'Dout:&#160;debug.h']]],
  ['dout_20dc_3a_3anotice_20hello_20world_70',['&lt;span class=&quot;tt&quot;&gt;Dout(dc::notice, &quot;Hello World&quot;);&lt;/span&gt;',['../group__tutorial-hello-world.html#autotoc_md134',1,'']]],
  ['doutentering_71',['DoutEntering',['../debug_8h.html#aeab210dd7cf7911e13928a4e21251a26',1,'debug.h']]],
  ['doutfatal_72',['DoutFatal',['../group__fatal-debug-output.html#ga1eec86ccc5e0dc1bd75d5bcc2209d433',1,'debug.h']]],
  ['downloading_73',['Downloading',['../group__downloading.html',1,'']]],
  ['dump_20core_74',['Making The Program Dump Core',['../group__making-the-program-dump-core.html',1,'']]]
];
