var searchData=
[
  ['i_20do_20that_20recursively_0',['I do that recursively',['../group__tutorial-faq.html#faq_recursive2',1,'11. Can I turn Debug Objects off again? Can I do that recursively?'],['../group__tutorial-faq.html#faq_recursive',1,'8. Can I turn Debug Channels off again? Can I do that recursively?']]],
  ['i_20have_20to_20use_20the_20dc_3a_3a_20prefix_1',['21. Why do I have to use the &lt;span class=&quot;tt&quot;&gt;dc::&lt;/span&gt; prefix?',['../group__tutorial-faq.html#faq_prefix',1,'']]],
  ['i_20made_20my_20own_20debug_20object_20can_20i_20still_20use_20dout_2',['17. I made my own Debug Object, can I still use &lt;span class=&quot;tt&quot;&gt;Dout&lt;/span&gt;?',['../group__tutorial-faq.html#faq_libcwdout',1,'']]],
  ['i_20make_20my_20own_3',['7. Which Debug Channels exist? Can I make my own?',['../group__tutorial-faq.html#faq_debugchannels',1,'']]],
  ['i_20make_20my_20own_20debug_20object_4',['10. Can I make my own Debug Object?',['../group__tutorial-faq.html#faq_owndebugobject',1,'']]],
  ['i_20need_20to_20type_20that_20semi_20colon_20after_20the_20macro_20why_20isn_20t_20it_20part_20of_20the_20macro_5',['16. Do I need to type that semi-colon after the macro? Why isn&apos;t it part of the macro?',['../group__tutorial-faq.html#faq_semicolon',1,'']]],
  ['i_20need_20to_20type_20the_20debug_20around_20it_6',['6. Why do I need to type the &lt;span class=&quot;tt&quot;&gt;Debug(  )&lt;/span&gt; around it?',['../group__tutorial-faq.html#faq_debug',1,'']]],
  ['i_20put_20my_20debug_20channels_20in_20my_20own_20name_20space_7',['22. Can I put my debug channels in my own name space?',['../group__tutorial-faq.html#faq_ownnamespace',1,'']]],
  ['i_20set_20a_20new_20ostream_20for_20a_20given_20debug_20object_8',['12. How do I set a new &lt;span class=&quot;tt&quot;&gt;ostream&lt;/span&gt; for a given Debug Object?',['../group__tutorial-faq.html#faq_setostream',1,'']]],
  ['i_20still_20use_20dout_9',['17. I made my own Debug Object, can I still use &lt;span class=&quot;tt&quot;&gt;Dout&lt;/span&gt;?',['../group__tutorial-faq.html#faq_libcwdout',1,'']]],
  ['i_20suppress_20that_20new_20line_20character_10',['19. Can I suppress that new-line character?',['../group__tutorial-faq.html#faq_suppress',1,'']]],
  ['i_20turn_20debug_20channels_20off_20again_20can_20i_20do_20that_20recursively_11',['8. Can I turn Debug Channels off again? Can I do that recursively?',['../group__tutorial-faq.html#faq_recursive',1,'']]],
  ['i_20turn_20debug_20objects_20off_20again_20can_20i_20do_20that_20recursively_12',['11. Can I turn Debug Objects off again? Can I do that recursively?',['../group__tutorial-faq.html#faq_recursive2',1,'']]],
  ['in_20libcwd_20debug_20h_13',['4. What is defined &lt;em&gt;exactly&lt;/em&gt; in &lt;span class=&quot;tt&quot;&gt;libcwd/debug.h&lt;/span&gt;?',['../group__tutorial-faq.html#faq_debug_h',1,'']]],
  ['in_20my_20own_20name_20space_14',['22. Can I put my debug channels in my own name space?',['../group__tutorial-faq.html#faq_ownnamespace',1,'']]],
  ['inc_5findent_15',['inc_indent',['../group__format-of-the-debug-output.html#ga29b3829fc31039c910c181cc15832c04',1,'libcwd::DebugObject']]],
  ['include_16',['&lt;span class=&quot;tt&quot;&gt;#include &amp;lt;libcwd/debug.h&amp;gt;&lt;/span&gt;',['../group__tutorial-hello-world.html#tutorial_hello_world_include',1,'']]],
  ['indent_17',['Indent',['../structlibcwd_1_1Indent.html',1,'libcwd::Indent'],['../structlibcwd_1_1Indent.html#afce3eea13019ff8e33003caa3f1c33d4',1,'libcwd::Indent::Indent()']]],
  ['information_18',['Source-File:Line-Number Information',['../group__source-file-line-number-information.html',1,'']]],
  ['information_20of_20types_20and_20symbols_19',['Getting Type Information Of Types And Symbols',['../group__getting-type-information-of-types-and-symbols.html',1,'']]],
  ['init_20',['init',['../classlibcwd_1_1TypeInfo.html#a01e9463b222ef9b2f0824a793d1b4e95',1,'libcwd::TypeInfo']]],
  ['initialization_5fdelayed_5f_21',['initialization_delayed_',['../classlibcwd_1_1Location.html#a6bfbdbc17270910225e3197435c72fcb',1,'libcwd::Location']]],
  ['initialize_22',['initialize',['../namespacelibcwd.html#a17abf4d2560c1786ccf7812235a19bd1',1,'libcwd']]],
  ['initializing_23',['Initializing',['../group__function-objects.html#autotoc_md129',1,'']]],
  ['initializing_20function_20objects_24',['Defining and initializing &lt;span class=&quot;tt&quot;&gt;Function&lt;/span&gt; objects',['../group__function-objects.html#autotoc_md127',1,'']]],
  ['inside_20dout_25',['Calling functions inside Dout',['../group__nesting-debug-output.html#section_nesting_calling',1,'']]],
  ['installation_26',['Installation',['../quick-reference.html#autotoc_md4',1,'']]],
  ['installing_20libcwd_27',['Step 1: Installing libcwd',['../group__preparation.html#installation',1,'']]],
  ['introduction_28',['Introduction',['../index.html',1,'']]],
  ['introduction_20debug_20output_29',['Introduction (Debug Output)',['../group__book__writing__intro.html',1,'']]],
  ['introduction_20types_20and_20symbols_30',['Introduction (Types And Symbols)',['../group__introduction-types-and-symbols.html',1,'']]],
  ['is_20a_20debug_20channel_31',['9. Why do you call it a Debug &lt;em&gt;Channel&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Channel?',['../group__tutorial-faq.html#faq_channel',1,'']]],
  ['is_20a_20debug_20object_32',['15. Why do you call it a Debug &lt;em&gt;Object&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Object?',['../group__tutorial-faq.html#faq_object',1,'']]],
  ['is_20defined_20exactly_20in_20libcwd_20debug_20h_33',['4. What is defined &lt;em&gt;exactly&lt;/em&gt; in &lt;span class=&quot;tt&quot;&gt;libcwd/debug.h&lt;/span&gt;?',['../group__tutorial-faq.html#faq_debug_h',1,'']]],
  ['is_20the_20field_20width_20of_20the_20label_20determined_34',['23. Why does it print spaces between the label and the colon? How is the field width of the label determined?',['../group__tutorial-faq.html#faq_labelwidth',1,'']]],
  ['is_20the_20maximum_20length_20of_20a_20label_35',['20. What is the maximum length of a label?',['../group__tutorial-faq.html#faq_label',1,'']]],
  ['is_20the_20second_20field_20of_20the_20macro_20still_20evaluated_20when_20the_20debug_20channel_20and_20or_20debug_20object_20are_20turned_20off_36',['18. Is the second field of the macro still evaluated when the Debug Channel and/or Debug Object are turned off?',['../group__tutorial-faq.html#faq_evaluation',1,'']]],
  ['is_5fknown_37',['is_known',['../classlibcwd_1_1Location.html#a4ddfbcb212587ec150d99d21ec55bf82',1,'libcwd::Location']]],
  ['is_5fon_38',['is_on',['../classlibcwd_1_1Channel.html#af7c69cbef2d9251ab966ad0ad535e38f',1,'libcwd::Channel::is_on()'],['../classChannel.html#af7c69cbef2d9251ab966ad0ad535e38f',1,'Channel::is_on()']]],
  ['isn_20t_20it_20part_20of_20the_20macro_39',['16. Do I need to type that semi-colon after the macro? Why isn&apos;t it part of the macro?',['../group__tutorial-faq.html#faq_semicolon',1,'']]],
  ['it_40',['6. Why do I need to type the &lt;span class=&quot;tt&quot;&gt;Debug(  )&lt;/span&gt; around it?',['../group__tutorial-faq.html#faq_debug',1,'']]],
  ['it_20a_20debug_20channel_20what_20is_20a_20debug_20channel_41',['9. Why do you call it a Debug &lt;em&gt;Channel&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Channel?',['../group__tutorial-faq.html#faq_channel',1,'']]],
  ['it_20a_20debug_20object_20what_20is_20a_20debug_20object_42',['15. Why do you call it a Debug &lt;em&gt;Object&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Object?',['../group__tutorial-faq.html#faq_object',1,'']]],
  ['it_20part_20of_20the_20macro_43',['16. Do I need to type that semi-colon after the macro? Why isn&apos;t it part of the macro?',['../group__tutorial-faq.html#faq_semicolon',1,'']]],
  ['it_20print_20spaces_20between_20the_20label_20and_20the_20colon_20how_20is_20the_20field_20width_20of_20the_20label_20determined_44',['23. Why does it print spaces between the label and the colon? How is the field width of the label determined?',['../group__tutorial-faq.html#faq_labelwidth',1,'']]]
];
