var searchData=
[
  ['wait_5fcf_0',['wait_cf',['../group__control-flags.html#gadb67bb8d9558741b023f3bce3444bfdc',1,'libcwd']]],
  ['warning_1',['warning',['../group__predefined-debug-channels.html#ga4bd3d341b405427e7b4083ec1306ea55',1,'libcwd::channels::dc']]],
  ['way_20around_2',['14. Why do you turn on the debug object after you enable a debug channel, why not the other way around?',['../group__tutorial-faq.html#faq_order',1,'']]],
  ['what_20is_20a_20debug_20channel_3',['9. Why do you call it a Debug &lt;em&gt;Channel&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Channel?',['../group__tutorial-faq.html#faq_channel',1,'']]],
  ['what_20is_20a_20debug_20object_4',['15. Why do you call it a Debug &lt;em&gt;Object&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Object?',['../group__tutorial-faq.html#faq_object',1,'']]],
  ['what_20is_20defined_20exactly_20in_20libcwd_20debug_20h_5',['4. What is defined &lt;em&gt;exactly&lt;/em&gt; in &lt;span class=&quot;tt&quot;&gt;libcwd/debug.h&lt;/span&gt;?',['../group__tutorial-faq.html#faq_debug_h',1,'']]],
  ['what_20is_20the_20maximum_20length_20of_20a_20label_6',['20. What is the maximum length of a label?',['../group__tutorial-faq.html#faq_label',1,'']]],
  ['when_20the_20debug_20channel_20and_20or_20debug_20object_20are_20turned_20off_7',['18. Is the second field of the macro still evaluated when the Debug Channel and/or Debug Object are turned off?',['../group__tutorial-faq.html#faq_evaluation',1,'']]],
  ['when_20using_20gitache_8',['How to configure libcwd when using gitache',['../group__configuration-options-and-macros.html#autotoc_md126',1,'']]],
  ['which_20debug_20channels_20exist_20can_20i_20make_20my_20own_9',['7. Which Debug Channels exist? Can I make my own?',['../group__tutorial-faq.html#faq_debugchannels',1,'']]],
  ['why_20are_20debug_20objects_20turned_20off_20at_20creation_10',['13. Why are Debug Objects turned off at creation?',['../group__tutorial-faq.html#faq_whyoff',1,'']]],
  ['why_20are_20you_20using_20macros_20for_20debug_20and_20dout_11',['5. Why are you using macros for &lt;span class=&quot;tt&quot;&gt;Debug&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;Dout&lt;/span&gt;?',['../group__tutorial-faq.html#faq_macros',1,'']]],
  ['why_20do_20i_20have_20to_20use_20the_20dc_3a_3a_20prefix_12',['21. Why do I have to use the &lt;span class=&quot;tt&quot;&gt;dc::&lt;/span&gt; prefix?',['../group__tutorial-faq.html#faq_prefix',1,'']]],
  ['why_20do_20i_20need_20to_20type_20the_20debug_20around_20it_13',['6. Why do I need to type the &lt;span class=&quot;tt&quot;&gt;Debug(  )&lt;/span&gt; around it?',['../group__tutorial-faq.html#faq_debug',1,'']]],
  ['why_20do_20you_20call_20it_20a_20debug_20channel_20what_20is_20a_20debug_20channel_14',['9. Why do you call it a Debug &lt;em&gt;Channel&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Channel?',['../group__tutorial-faq.html#faq_channel',1,'']]],
  ['why_20do_20you_20call_20it_20a_20debug_20object_20what_20is_20a_20debug_20object_15',['15. Why do you call it a Debug &lt;em&gt;Object&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Object?',['../group__tutorial-faq.html#faq_object',1,'']]],
  ['why_20do_20you_20turn_20on_20the_20debug_20object_20after_20you_20enable_20a_20debug_20channel_20why_20not_20the_20other_20way_20around_16',['14. Why do you turn on the debug object after you enable a debug channel, why not the other way around?',['../group__tutorial-faq.html#faq_order',1,'']]],
  ['why_20does_20it_20print_20spaces_20between_20the_20label_20and_20the_20colon_20how_20is_20the_20field_20width_20of_20the_20label_20determined_17',['23. Why does it print spaces between the label and the colon? How is the field width of the label determined?',['../group__tutorial-faq.html#faq_labelwidth',1,'']]],
  ['why_20isn_20t_20it_20part_20of_20the_20macro_18',['16. Do I need to type that semi-colon after the macro? Why isn&apos;t it part of the macro?',['../group__tutorial-faq.html#faq_semicolon',1,'']]],
  ['why_20not_20the_20other_20way_20around_19',['14. Why do you turn on the debug object after you enable a debug channel, why not the other way around?',['../group__tutorial-faq.html#faq_order',1,'']]],
  ['width_20of_20the_20label_20determined_20',['23. Why does it print spaces between the label and the colon? How is the field width of the label determined?',['../group__tutorial-faq.html#faq_labelwidth',1,'']]],
  ['with_20a_20new_20project_21',['Using libcwd with a new project',['../quick-reference.html#autotoc_md5',1,'']]],
  ['won_20t_20this_20define_20make_20my_20code_20non_20portable_22',['1. Won&apos;t this define make my code non-portable?',['../group__tutorial-faq.html#faq_gnu_source',1,'']]],
  ['world_23',['World',['../group__tutorial-hello-world.html#autotoc_md134',1,'&lt;span class=&quot;tt&quot;&gt;Dout(dc::notice, &quot;Hello World&quot;);&lt;/span&gt;'],['../group__tutorial-hello-world.html',1,'Tutorial 1: Hello World']]],
  ['writing_20debug_20output_24',['Writing Debug Output',['../group__reference-manual-writing-debug-output.html',1,'']]]
];
