var searchData=
[
  ['object_0',['Object',['../group__tutorial-faq.html#faq_owndebugobject',1,'10. Can I make my own Debug Object?'],['../group__tutorial-faq.html#faq_setostream',1,'12. How do I set a new &lt;span class=&quot;tt&quot;&gt;ostream&lt;/span&gt; for a given Debug Object?'],['../group__tutorial-faq.html#faq_object',1,'15. Why do you call it a Debug &lt;em&gt;Object&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Object?'],['../group__the-output-device-debug-object.html',1,'The Output Device (Debug Object)']]],
  ['object_1',['Methods of the debug object',['../group__tutorial-advanced.html#tutorial_advanced_methods',1,'']]],
  ['object_20after_20you_20enable_20a_20debug_20channel_20why_20not_20the_20other_20way_20around_2',['14. Why do you turn on the debug object after you enable a debug channel, why not the other way around?',['../group__tutorial-faq.html#faq_order',1,'']]],
  ['object_20are_20turned_20off_3',['18. Is the second field of the macro still evaluated when the Debug Channel and/or Debug Object are turned off?',['../group__tutorial-faq.html#faq_evaluation',1,'']]],
  ['object_20can_20i_20still_20use_20dout_4',['17. I made my own Debug Object, can I still use &lt;span class=&quot;tt&quot;&gt;Dout&lt;/span&gt;?',['../group__tutorial-faq.html#faq_libcwdout',1,'']]],
  ['object_20what_20is_20a_20debug_20object_5',['15. Why do you call it a Debug &lt;em&gt;Object&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Object?',['../group__tutorial-faq.html#faq_object',1,'']]],
  ['object_5ffile_6',['object_file',['../classlibcwd_1_1Location.html#a82f5d66a1b6daa2c0e3889646f53b7ad',1,'libcwd::Location']]],
  ['object_5ffile_5fname_5f_7',['object_file_name_',['../classlibcwd_1_1Location.html#a2510b7b22c75578a7190f7ef9348a5ac',1,'libcwd::Location']]],
  ['objectfilename_8',['ObjectFileName',['../classlibcwd_1_1ObjectFileName.html',1,'libcwd']]],
  ['objectfilename_2eh_9',['ObjectFileName.h',['../ObjectFileName_8h.html',1,'']]],
  ['objects_10',['Objects',['../group__custom-debug-objects.html',1,'Custom Debug Objects'],['../group__function-objects.html',1,'Function Objects']]],
  ['objects_11',['Defining and initializing &lt;span class=&quot;tt&quot;&gt;Function&lt;/span&gt; objects',['../group__function-objects.html#autotoc_md127',1,'']]],
  ['objects_20off_20again_20can_20i_20do_20that_20recursively_12',['11. Can I turn Debug Objects off again? Can I do that recursively?',['../group__tutorial-faq.html#faq_recursive2',1,'']]],
  ['objects_20turned_20off_20at_20creation_13',['13. Why are Debug Objects turned off at creation?',['../group__tutorial-faq.html#faq_whyoff',1,'']]],
  ['oct_202004_14',['8 Oct 2004',['../release-notes.html#autotoc_md39',1,'']]],
  ['october_202000_15',['11 October 2000',['../release-notes.html#autotoc_md113',1,'']]],
  ['of_20a_20label_16',['20. What is the maximum length of a label?',['../group__tutorial-faq.html#faq_label',1,'']]],
  ['of_20cwdebug_17',['Tutorial 4: Management Of CWDEBUG',['../group__tutorial-cwdebug.html',1,'']]],
  ['of_20libraries_18',['Header files of libraries',['../group__the-custom-debug-h-file.html#header_files_of_libraries',1,'']]],
  ['of_20the_20debug_20object_19',['Methods of the debug object',['../group__tutorial-advanced.html#tutorial_advanced_methods',1,'']]],
  ['of_20the_20debug_20output_20',['Format Of The Debug Output',['../group__format-of-the-debug-output.html',1,'']]],
  ['of_20the_20label_20determined_21',['23. Why does it print spaces between the label and the colon? How is the field width of the label determined?',['../group__tutorial-faq.html#faq_labelwidth',1,'']]],
  ['of_20the_20macro_22',['16. Do I need to type that semi-colon after the macro? Why isn&apos;t it part of the macro?',['../group__tutorial-faq.html#faq_semicolon',1,'']]],
  ['of_20the_20macro_20still_20evaluated_20when_20the_20debug_20channel_20and_20or_20debug_20object_20are_20turned_20off_23',['18. Is the second field of the macro still evaluated when the Debug Channel and/or Debug Object are turned off?',['../group__tutorial-faq.html#faq_evaluation',1,'']]],
  ['of_20types_20and_20symbols_24',['Getting Type Information Of Types And Symbols',['../group__getting-type-information-of-types-and-symbols.html',1,'']]],
  ['off_25',['off',['../group__tutorial-faq.html#faq_evaluation',1,'18. Is the second field of the macro still evaluated when the Debug Channel and/or Debug Object are turned off?'],['../classlibcwd_1_1Channel.html#a9afa3eb80d2c622368fb62fbd313018d',1,'libcwd::Channel::off()'],['../classlibcwd_1_1DebugObject.html#ac8433609d874f6bd48ea8f62b6bc314d',1,'libcwd::DebugObject::off()'],['../classChannel.html#a9afa3eb80d2c622368fb62fbd313018d',1,'Channel::off()']]],
  ['off_20again_20can_20i_20do_20that_20recursively_26',['off again Can I do that recursively',['../group__tutorial-faq.html#faq_recursive2',1,'11. Can I turn Debug Objects off again? Can I do that recursively?'],['../group__tutorial-faq.html#faq_recursive',1,'8. Can I turn Debug Channels off again? Can I do that recursively?']]],
  ['off_20at_20creation_27',['13. Why are Debug Objects turned off at creation?',['../group__tutorial-faq.html#faq_whyoff',1,'']]],
  ['on_28',['on',['../group__tutorial-hello-world.html#tutorial_hello_world_turn_on_channel',1,'&lt;span class=&quot;tt&quot;&gt;Debug(dc::notice.on());&lt;/span&gt;'],['../group__tutorial-hello-world.html#autotoc_md133',1,'&lt;span class=&quot;tt&quot;&gt;Debug(libcw_do.on());&lt;/span&gt;'],['../classlibcwd_1_1Channel.html#a9e397bea2b8a52150cfa2647a6f83b1f',1,'libcwd::Channel::on()'],['../classlibcwd_1_1DebugObject.html#a2421619c8379548b0609f8ea215c4416',1,'libcwd::DebugObject::on()'],['../classChannel.html#a9e397bea2b8a52150cfa2647a6f83b1f',1,'Channel::on()']]],
  ['on_20the_20debug_20object_20after_20you_20enable_20a_20debug_20channel_20why_20not_20the_20other_20way_20around_29',['14. Why do you turn on the debug object after you enable a debug channel, why not the other way around?',['../group__tutorial-faq.html#faq_order',1,'']]],
  ['operator_3c_3c_30',['operator&lt;&lt;',['../classlibcwd_1_1buf2str.html#a42e07719142bad162e5d20b4e98ce78f',1,'libcwd::buf2str::operator&lt;&lt;()'],['../classlibcwd_1_1char2str.html#aaa5021412dc30c81f9dd9e2e404a88cf',1,'libcwd::char2str::operator&lt;&lt;()'],['../group__source-file-line-number-information.html#ga616a88d53f1e75e923852d4c5395f2af',1,'libcwd::operator&lt;&lt;()'],['../libraries__debug_8h.html#a616a88d53f1e75e923852d4c5395f2af',1,'libcwd_inserters::operator&lt;&lt;()']]],
  ['operator_3d_31',['operator=',['../classlibcwd_1_1Location.html#a841829c5a7250a02522dbeae1e70a05b',1,'libcwd::Location']]],
  ['options_20and_20macros_32',['Configuration Options And Macros',['../group__configuration-options-and-macros.html',1,'']]],
  ['or_20debug_20object_20are_20turned_20off_33',['18. Is the second field of the macro still evaluated when the Debug Channel and/or Debug Object are turned off?',['../group__tutorial-faq.html#faq_evaluation',1,'']]],
  ['ostream_34',['Tutorial 3: Setting The ostream',['../group__tutorial-ostream.html',1,'']]],
  ['ostream_20for_20a_20given_20debug_20object_35',['12. How do I set a new &lt;span class=&quot;tt&quot;&gt;ostream&lt;/span&gt; for a given Debug Object?',['../group__tutorial-faq.html#faq_setostream',1,'']]],
  ['other_20way_20around_36',['14. Why do you turn on the debug object after you enable a debug channel, why not the other way around?',['../group__tutorial-faq.html#faq_order',1,'']]],
  ['output_37',['Output',['../quick-reference.html#autotoc_md6',1,'Debug Output'],['../group__fatal-debug-output.html',1,'Fatal Debug Output'],['../group__format-of-the-debug-output.html',1,'Format Of The Debug Output'],['../group__book__writing__intro.html',1,'Introduction (Debug Output)'],['../group__nesting-debug-output.html',1,'Nesting Debug Output'],['../group__reference-manual-writing-debug-output.html',1,'Writing Debug Output']]],
  ['output_38',['Formatting debug output',['../group__tutorial-advanced.html#tutorial_advanced_formatting',1,'']]],
  ['output_20destination_39',['Setting The Output Destination',['../group__setting-the-output-destination.html',1,'']]],
  ['output_20device_20debug_20object_40',['The Output Device (Debug Object)',['../group__the-output-device-debug-object.html',1,'']]],
  ['output_20level_20debug_20channels_41',['Controlling The Output Level (Debug Channels)',['../group__controlling-the-output-level-debug-channels.html',1,'']]],
  ['over_20all_20debug_20channels_42',['Running over all Debug Channels',['../group__tutorial-advanced.html#tutorial_advanced_running',1,'']]],
  ['own_43',['7. Which Debug Channels exist? Can I make my own?',['../group__tutorial-faq.html#faq_debugchannels',1,'']]],
  ['own_20debug_20channels_44',['Tutorial 2: Creating Your Own Debug Channels',['../group__tutorial-channels.html',1,'']]],
  ['own_20debug_20object_45',['10. Can I make my own Debug Object?',['../group__tutorial-faq.html#faq_owndebugobject',1,'']]],
  ['own_20debug_20object_20can_20i_20still_20use_20dout_46',['17. I made my own Debug Object, can I still use &lt;span class=&quot;tt&quot;&gt;Dout&lt;/span&gt;?',['../group__tutorial-faq.html#faq_libcwdout',1,'']]],
  ['own_20name_20space_47',['22. Can I put my debug channels in my own name space?',['../group__tutorial-faq.html#faq_ownnamespace',1,'']]]
];
