var searchData=
[
  ['a_20debug_20channel_0',['9. Why do you call it a Debug &lt;em&gt;Channel&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Channel?',['../group__tutorial-faq.html#faq_channel',1,'']]],
  ['a_20debug_20channel_20what_20is_20a_20debug_20channel_1',['9. Why do you call it a Debug &lt;em&gt;Channel&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Channel?',['../group__tutorial-faq.html#faq_channel',1,'']]],
  ['a_20debug_20channel_20why_20not_20the_20other_20way_20around_2',['14. Why do you turn on the debug object after you enable a debug channel, why not the other way around?',['../group__tutorial-faq.html#faq_order',1,'']]],
  ['a_20debug_20object_3',['15. Why do you call it a Debug &lt;em&gt;Object&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Object?',['../group__tutorial-faq.html#faq_object',1,'']]],
  ['a_20debug_20object_20what_20is_20a_20debug_20object_4',['15. Why do you call it a Debug &lt;em&gt;Object&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Object?',['../group__tutorial-faq.html#faq_object',1,'']]],
  ['a_20gdb_20session_20from_20a_20running_20program_5',['Starting A gdb Session From A Running Program',['../group__starting-a-gdb-session-from-a-running-program.html',1,'']]],
  ['a_20given_20debug_20object_6',['12. How do I set a new &lt;span class=&quot;tt&quot;&gt;ostream&lt;/span&gt; for a given Debug Object?',['../group__tutorial-faq.html#faq_setostream',1,'']]],
  ['a_20label_7',['20. What is the maximum length of a label?',['../group__tutorial-faq.html#faq_label',1,'']]],
  ['a_20new_20ostream_20for_20a_20given_20debug_20object_8',['12. How do I set a new &lt;span class=&quot;tt&quot;&gt;ostream&lt;/span&gt; for a given Debug Object?',['../group__tutorial-faq.html#faq_setostream',1,'']]],
  ['a_20new_20project_9',['Using libcwd with a new project',['../quick-reference.html#autotoc_md5',1,'']]],
  ['a_20running_20program_10',['Starting A gdb Session From A Running Program',['../group__starting-a-gdb-session-from-a-running-program.html',1,'']]],
  ['adding_20the_20cwds_20submodule_11',['Step 2: Adding the cwds submodule',['../group__preparation.html#cwds_submodule',1,'']]],
  ['advanced_20examples_12',['Tutorial 5: Advanced Examples',['../group__tutorial-advanced.html',1,'']]],
  ['after_20the_20macro_20why_20isn_20t_20it_20part_20of_20the_20macro_13',['16. Do I need to type that semi-colon after the macro? Why isn&apos;t it part of the macro?',['../group__tutorial-faq.html#faq_semicolon',1,'']]],
  ['after_20you_20enable_20a_20debug_20channel_20why_20not_20the_20other_20way_20around_14',['14. Why do you turn on the debug object after you enable a debug channel, why not the other way around?',['../group__tutorial-faq.html#faq_order',1,'']]],
  ['again_20can_20i_20do_20that_20recursively_15',['again Can I do that recursively',['../group__tutorial-faq.html#faq_recursive2',1,'11. Can I turn Debug Objects off again? Can I do that recursively?'],['../group__tutorial-faq.html#faq_recursive',1,'8. Can I turn Debug Channels off again? Can I do that recursively?']]],
  ['all_20debug_20channels_16',['Running over all Debug Channels',['../group__tutorial-advanced.html#tutorial_advanced_running',1,'']]],
  ['always_17',['always',['../group__predefined-debug-channels.html#gaa48b4c4e247d095e1ca95f9e79ba2602',1,'libcwd::channels::dc']]],
  ['always_5fflush_5foff_18',['always_flush_off',['../classlibcwd_1_1DebugObject.html#afbea533153cc1b49dc4bbf302df74568',1,'libcwd::DebugObject']]],
  ['always_5fflush_5fon_19',['always_flush_on',['../classlibcwd_1_1DebugObject.html#a22141a27fdee03804c89c2b4bf12744b',1,'libcwd::DebugObject']]],
  ['alwayschannel_2eh_20',['AlwaysChannel.h',['../AlwaysChannel_8h.html',1,'']]],
  ['and_20dc_3a_3afinish_21',['Using continued_cf, dc::continued and dc::finish',['../group__nesting-debug-output.html#using_continued',1,'']]],
  ['and_20demangle_5fsymbol_22',['demangle_type() and demangle_symbol()',['../group__demangle__type-and-demangle__symbol.html',1,'']]],
  ['and_20dout_23',['5. Why are you using macros for &lt;span class=&quot;tt&quot;&gt;Debug&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;Dout&lt;/span&gt;?',['../group__tutorial-faq.html#faq_macros',1,'']]],
  ['and_20initializing_20function_20objects_24',['Defining and initializing &lt;span class=&quot;tt&quot;&gt;Function&lt;/span&gt; objects',['../group__function-objects.html#autotoc_md127',1,'']]],
  ['and_20locations_25',['Function Symbols, Types And Locations.',['../group__reference-manual-symbols.html',1,'']]],
  ['and_20macros_26',['Configuration Options And Macros',['../group__configuration-options-and-macros.html',1,'']]],
  ['and_20name_20spaces_27',['Debug Channels and name spaces',['../group__tutorial-advanced.html#tutorial_advanced_debug',1,'']]],
  ['and_20namespace_28',['Debug channels and namespace',['../group__the-custom-debug-h-file.html#debug_channels_and_namespace',1,'']]],
  ['and_20or_20debug_20object_20are_20turned_20off_29',['18. Is the second field of the macro still evaluated when the Debug Channel and/or Debug Object are turned off?',['../group__tutorial-faq.html#faq_evaluation',1,'']]],
  ['and_20symbols_30',['And Symbols',['../group__getting-type-information-of-types-and-symbols.html',1,'Getting Type Information Of Types And Symbols'],['../group__introduction-types-and-symbols.html',1,'Introduction (Types And Symbols)']]],
  ['and_20the_20colon_20how_20is_20the_20field_20width_20of_20the_20label_20determined_31',['23. Why does it print spaces between the label and the colon? How is the field width of the label determined?',['../group__tutorial-faq.html#faq_labelwidth',1,'']]],
  ['and_20utilities_32',['Special Functions And Utilities',['../group__special-functions-and-utilities.html',1,'']]],
  ['append_33',['append',['../classlibcwd_1_1DebugString.html#a3f0c22c0e34356e8e81b5abb53901b47',1,'libcwd::DebugString::append(char const *str, size_t len)'],['../classlibcwd_1_1DebugString.html#a9b80a5343dd7085112e4693a77fe6957',1,'libcwd::DebugString::append(std::string const &amp;str)']]],
  ['applications_34',['Applications',['../group__the-custom-debug-h-file.html#applications',1,'Applications'],['../group__tutorial-threads.html',1,'Tutorial 6: Debugging Threaded Applications']]],
  ['apr_202004_35',['23 Apr 2004',['../release-notes.html#autotoc_md51',1,'']]],
  ['april_202002_36',['23 April 2002',['../release-notes.html#autotoc_md81',1,'']]],
  ['are_20debug_20objects_20turned_20off_20at_20creation_37',['13. Why are Debug Objects turned off at creation?',['../group__tutorial-faq.html#faq_whyoff',1,'']]],
  ['are_20turned_20off_38',['18. Is the second field of the macro still evaluated when the Debug Channel and/or Debug Object are turned off?',['../group__tutorial-faq.html#faq_evaluation',1,'']]],
  ['are_20you_20using_20macros_20for_20debug_20and_20dout_39',['5. Why are you using macros for &lt;span class=&quot;tt&quot;&gt;Debug&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;Dout&lt;/span&gt;?',['../group__tutorial-faq.html#faq_macros',1,'']]],
  ['around_40',['14. Why do you turn on the debug object after you enable a debug channel, why not the other way around?',['../group__tutorial-faq.html#faq_order',1,'']]],
  ['around_20it_41',['6. Why do I need to type the &lt;span class=&quot;tt&quot;&gt;Debug(  )&lt;/span&gt; around it?',['../group__tutorial-faq.html#faq_debug',1,'']]],
  ['assign_42',['assign',['../classlibcwd_1_1DebugString.html#a469afcabee530192225825fbb14147d9',1,'libcwd::DebugString::assign(char const *str, size_t len)'],['../classlibcwd_1_1DebugString.html#ae640a7d1ee649c2cc278d68be413d04a',1,'libcwd::DebugString::assign(std::string const &amp;str)']]],
  ['at_20creation_43',['13. Why are Debug Objects turned off at creation?',['../group__tutorial-faq.html#faq_whyoff',1,'']]],
  ['august_202000_44',['August 2000',['../release-notes.html#autotoc_md123',1,'04 August 2000'],['../release-notes.html#autotoc_md121',1,'08 August 2000'],['../release-notes.html#autotoc_md119',1,'15 August 2000'],['../release-notes.html#autotoc_md117',1,'29 August 2000']]],
  ['august_202001_45',['August 2001',['../release-notes.html#autotoc_md97',1,'1 August 2001'],['../release-notes.html#autotoc_md95',1,'20 August 2001'],['../release-notes.html#autotoc_md93',1,'28 August 2001']]],
  ['august_202002_46',['19 August 2002',['../release-notes.html#autotoc_md69',1,'']]]
];
