var searchData=
[
  ['a_20debug_20channel_0',['9. Why do you call it a Debug &lt;em&gt;Channel&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Channel?',['../group__tutorial-faq.html#faq_channel',1,'']]],
  ['a_20debug_20channel_20what_20is_20a_20debug_20channel_1',['9. Why do you call it a Debug &lt;em&gt;Channel&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Channel?',['../group__tutorial-faq.html#faq_channel',1,'']]],
  ['a_20debug_20channel_20why_20not_20the_20other_20way_20around_2',['14. Why do you turn on the debug object after you enable a debug channel, why not the other way around?',['../group__tutorial-faq.html#faq_order',1,'']]],
  ['a_20debug_20object_3',['15. Why do you call it a Debug &lt;em&gt;Object&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Object?',['../group__tutorial-faq.html#faq_object',1,'']]],
  ['a_20debug_20object_20what_20is_20a_20debug_20object_4',['15. Why do you call it a Debug &lt;em&gt;Object&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Object?',['../group__tutorial-faq.html#faq_object',1,'']]],
  ['a_20given_20debug_20object_5',['12. How do I set a new &lt;span class=&quot;tt&quot;&gt;ostream&lt;/span&gt; for a given Debug Object?',['../group__tutorial-faq.html#faq_setostream',1,'']]],
  ['a_20label_6',['20. What is the maximum length of a label?',['../group__tutorial-faq.html#faq_label',1,'']]],
  ['a_20new_20ostream_20for_20a_20given_20debug_20object_7',['12. How do I set a new &lt;span class=&quot;tt&quot;&gt;ostream&lt;/span&gt; for a given Debug Object?',['../group__tutorial-faq.html#faq_setostream',1,'']]],
  ['a_20new_20project_8',['Using libcwd with a new project',['../quick-reference.html#autotoc_md5',1,'']]],
  ['adding_20the_20cwds_20submodule_9',['Step 2: Adding the cwds submodule',['../group__preparation.html#cwds_submodule',1,'']]],
  ['after_20the_20macro_20why_20isn_20t_20it_20part_20of_20the_20macro_10',['16. Do I need to type that semi-colon after the macro? Why isn&apos;t it part of the macro?',['../group__tutorial-faq.html#faq_semicolon',1,'']]],
  ['after_20you_20enable_20a_20debug_20channel_20why_20not_20the_20other_20way_20around_11',['14. Why do you turn on the debug object after you enable a debug channel, why not the other way around?',['../group__tutorial-faq.html#faq_order',1,'']]],
  ['again_20can_20i_20do_20that_20recursively_12',['again Can I do that recursively',['../group__tutorial-faq.html#faq_recursive2',1,'11. Can I turn Debug Objects off again? Can I do that recursively?'],['../group__tutorial-faq.html#faq_recursive',1,'8. Can I turn Debug Channels off again? Can I do that recursively?']]],
  ['all_20debug_20channels_13',['Running over all Debug Channels',['../group__tutorial-advanced.html#tutorial_advanced_running',1,'']]],
  ['and_20dc_3a_3afinish_14',['Using continued_cf, dc::continued and dc::finish',['../group__nesting-debug-output.html#using_continued',1,'']]],
  ['and_20dout_15',['5. Why are you using macros for &lt;span class=&quot;tt&quot;&gt;Debug&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;Dout&lt;/span&gt;?',['../group__tutorial-faq.html#faq_macros',1,'']]],
  ['and_20initializing_20function_20objects_16',['Defining and initializing &lt;span class=&quot;tt&quot;&gt;Function&lt;/span&gt; objects',['../group__function-objects.html#autotoc_md127',1,'']]],
  ['and_20name_20spaces_17',['Debug Channels and name spaces',['../group__tutorial-advanced.html#tutorial_advanced_debug',1,'']]],
  ['and_20namespace_18',['Debug channels and namespace',['../group__the-custom-debug-h-file.html#debug_channels_and_namespace',1,'']]],
  ['and_20or_20debug_20object_20are_20turned_20off_19',['18. Is the second field of the macro still evaluated when the Debug Channel and/or Debug Object are turned off?',['../group__tutorial-faq.html#faq_evaluation',1,'']]],
  ['and_20the_20colon_20how_20is_20the_20field_20width_20of_20the_20label_20determined_20',['23. Why does it print spaces between the label and the colon? How is the field width of the label determined?',['../group__tutorial-faq.html#faq_labelwidth',1,'']]],
  ['applications_21',['Applications',['../group__the-custom-debug-h-file.html#applications',1,'']]],
  ['apr_202004_22',['23 Apr 2004',['../release-notes.html#autotoc_md51',1,'']]],
  ['april_202002_23',['23 April 2002',['../release-notes.html#autotoc_md81',1,'']]],
  ['are_20debug_20objects_20turned_20off_20at_20creation_24',['13. Why are Debug Objects turned off at creation?',['../group__tutorial-faq.html#faq_whyoff',1,'']]],
  ['are_20turned_20off_25',['18. Is the second field of the macro still evaluated when the Debug Channel and/or Debug Object are turned off?',['../group__tutorial-faq.html#faq_evaluation',1,'']]],
  ['are_20you_20using_20macros_20for_20debug_20and_20dout_26',['5. Why are you using macros for &lt;span class=&quot;tt&quot;&gt;Debug&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;Dout&lt;/span&gt;?',['../group__tutorial-faq.html#faq_macros',1,'']]],
  ['around_27',['14. Why do you turn on the debug object after you enable a debug channel, why not the other way around?',['../group__tutorial-faq.html#faq_order',1,'']]],
  ['around_20it_28',['6. Why do I need to type the &lt;span class=&quot;tt&quot;&gt;Debug(  )&lt;/span&gt; around it?',['../group__tutorial-faq.html#faq_debug',1,'']]],
  ['at_20creation_29',['13. Why are Debug Objects turned off at creation?',['../group__tutorial-faq.html#faq_whyoff',1,'']]],
  ['august_202000_30',['August 2000',['../release-notes.html#autotoc_md123',1,'04 August 2000'],['../release-notes.html#autotoc_md121',1,'08 August 2000'],['../release-notes.html#autotoc_md119',1,'15 August 2000'],['../release-notes.html#autotoc_md117',1,'29 August 2000']]],
  ['august_202001_31',['August 2001',['../release-notes.html#autotoc_md97',1,'1 August 2001'],['../release-notes.html#autotoc_md95',1,'20 August 2001'],['../release-notes.html#autotoc_md93',1,'28 August 2001']]],
  ['august_202002_32',['19 August 2002',['../release-notes.html#autotoc_md69',1,'']]]
];
