var searchData=
[
  ['call_20it_20a_20debug_20channel_20what_20is_20a_20debug_20channel_0',['9. Why do you call it a Debug &lt;em&gt;Channel&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Channel?',['../group__tutorial-faq.html#faq_channel',1,'']]],
  ['call_20it_20a_20debug_20object_20what_20is_20a_20debug_20object_1',['15. Why do you call it a Debug &lt;em&gt;Object&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Object?',['../group__tutorial-faq.html#faq_object',1,'']]],
  ['calling_20functions_20inside_20dout_2',['Calling functions inside Dout',['../group__nesting-debug-output.html#section_nesting_calling',1,'']]],
  ['can_20i_20do_20that_20recursively_3',['Can I do that recursively',['../group__tutorial-faq.html#faq_recursive2',1,'11. Can I turn Debug Objects off again? Can I do that recursively?'],['../group__tutorial-faq.html#faq_recursive',1,'8. Can I turn Debug Channels off again? Can I do that recursively?']]],
  ['can_20i_20make_20my_20own_4',['7. Which Debug Channels exist? Can I make my own?',['../group__tutorial-faq.html#faq_debugchannels',1,'']]],
  ['can_20i_20make_20my_20own_20debug_20object_5',['10. Can I make my own Debug Object?',['../group__tutorial-faq.html#faq_owndebugobject',1,'']]],
  ['can_20i_20put_20my_20debug_20channels_20in_20my_20own_20name_20space_6',['22. Can I put my debug channels in my own name space?',['../group__tutorial-faq.html#faq_ownnamespace',1,'']]],
  ['can_20i_20still_20use_20dout_7',['17. I made my own Debug Object, can I still use &lt;span class=&quot;tt&quot;&gt;Dout&lt;/span&gt;?',['../group__tutorial-faq.html#faq_libcwdout',1,'']]],
  ['can_20i_20suppress_20that_20new_20line_20character_8',['19. Can I suppress that new-line character?',['../group__tutorial-faq.html#faq_suppress',1,'']]],
  ['can_20i_20turn_20debug_20channels_20off_20again_20can_20i_20do_20that_20recursively_9',['8. Can I turn Debug Channels off again? Can I do that recursively?',['../group__tutorial-faq.html#faq_recursive',1,'']]],
  ['can_20i_20turn_20debug_20objects_20off_20again_20can_20i_20do_20that_20recursively_10',['11. Can I turn Debug Objects off again? Can I do that recursively?',['../group__tutorial-faq.html#faq_recursive2',1,'']]],
  ['channel_11',['9. Why do you call it a Debug &lt;em&gt;Channel&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Channel?',['../group__tutorial-faq.html#faq_channel',1,'']]],
  ['channel_20and_20or_20debug_20object_20are_20turned_20off_12',['18. Is the second field of the macro still evaluated when the Debug Channel and/or Debug Object are turned off?',['../group__tutorial-faq.html#faq_evaluation',1,'']]],
  ['channel_20name_20collisions_13',['Debug channel name collisions',['../group__the-custom-debug-h-file.html#debug_channel_name_collisions',1,'']]],
  ['channel_20what_20is_20a_20debug_20channel_14',['9. Why do you call it a Debug &lt;em&gt;Channel&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Channel?',['../group__tutorial-faq.html#faq_channel',1,'']]],
  ['channel_20why_20not_20the_20other_20way_20around_15',['14. Why do you turn on the debug object after you enable a debug channel, why not the other way around?',['../group__tutorial-faq.html#faq_order',1,'']]],
  ['channels_16',['Running over all Debug Channels',['../group__tutorial-advanced.html#tutorial_advanced_running',1,'']]],
  ['channels_17',['Combining channels',['../group__tutorial-advanced.html#tutorial_advanced_combining',1,'']]],
  ['channels_20and_20name_20spaces_18',['Debug Channels and name spaces',['../group__tutorial-advanced.html#tutorial_advanced_debug',1,'']]],
  ['channels_20and_20namespace_19',['Debug channels and namespace',['../group__the-custom-debug-h-file.html#debug_channels_and_namespace',1,'']]],
  ['channels_20exist_20can_20i_20make_20my_20own_20',['7. Which Debug Channels exist? Can I make my own?',['../group__tutorial-faq.html#faq_debugchannels',1,'']]],
  ['channels_20in_20my_20own_20name_20space_21',['22. Can I put my debug channels in my own name space?',['../group__tutorial-faq.html#faq_ownnamespace',1,'']]],
  ['channels_20off_20again_20can_20i_20do_20that_20recursively_22',['8. Can I turn Debug Channels off again? Can I do that recursively?',['../group__tutorial-faq.html#faq_recursive',1,'']]],
  ['character_23',['19. Can I suppress that new-line character?',['../group__tutorial-faq.html#faq_suppress',1,'']]],
  ['code_20non_20portable_24',['1. Won&apos;t this define make my code non-portable?',['../group__tutorial-faq.html#faq_gnu_source',1,'']]],
  ['collisions_25',['Debug channel name collisions',['../group__the-custom-debug-h-file.html#debug_channel_name_collisions',1,'']]],
  ['colon_20after_20the_20macro_20why_20isn_20t_20it_20part_20of_20the_20macro_26',['16. Do I need to type that semi-colon after the macro? Why isn&apos;t it part of the macro?',['../group__tutorial-faq.html#faq_semicolon',1,'']]],
  ['colon_20how_20is_20the_20field_20width_20of_20the_20label_20determined_27',['23. Why does it print spaces between the label and the colon? How is the field width of the label determined?',['../group__tutorial-faq.html#faq_labelwidth',1,'']]],
  ['combining_20channels_28',['Combining channels',['../group__tutorial-advanced.html#tutorial_advanced_combining',1,'']]],
  ['configure_20libcwd_20when_20using_20gitache_29',['How to configure libcwd when using gitache',['../group__configuration-options-and-macros.html#autotoc_md126',1,'']]],
  ['continued_5fcf_20dc_3a_3acontinued_20and_20dc_3a_3afinish_30',['Using continued_cf, dc::continued and dc::finish',['../group__nesting-debug-output.html#using_continued',1,'']]],
  ['control_20flags_31',['Control flags',['../group__tutorial-advanced.html#tutorial_advanced_control',1,'']]],
  ['creation_32',['13. Why are Debug Objects turned off at creation?',['../group__tutorial-faq.html#faq_whyoff',1,'']]],
  ['cwds_20submodule_33',['Step 2: Adding the cwds submodule',['../group__preparation.html#cwds_submodule',1,'']]]
];
