var searchData=
[
  ['t_20it_20part_20of_20the_20macro_0',['16. Do I need to type that semi-colon after the macro? Why isn&apos;t it part of the macro?',['../group__tutorial-faq.html#faq_semicolon',1,'']]],
  ['t_20this_20define_20make_20my_20code_20non_20portable_1',['1. Won&apos;t this define make my code non-portable?',['../group__tutorial-faq.html#faq_gnu_source',1,'']]],
  ['that_20new_20line_20character_2',['19. Can I suppress that new-line character?',['../group__tutorial-faq.html#faq_suppress',1,'']]],
  ['that_20recursively_3',['that recursively',['../group__tutorial-faq.html#faq_recursive2',1,'11. Can I turn Debug Objects off again? Can I do that recursively?'],['../group__tutorial-faq.html#faq_recursive',1,'8. Can I turn Debug Channels off again? Can I do that recursively?']]],
  ['that_20semi_20colon_20after_20the_20macro_20why_20isn_20t_20it_20part_20of_20the_20macro_4',['16. Do I need to type that semi-colon after the macro? Why isn&apos;t it part of the macro?',['../group__tutorial-faq.html#faq_semicolon',1,'']]],
  ['the_20colon_20how_20is_20the_20field_20width_20of_20the_20label_20determined_5',['23. Why does it print spaces between the label and the colon? How is the field width of the label determined?',['../group__tutorial-faq.html#faq_labelwidth',1,'']]],
  ['the_20cwds_20submodule_6',['Step 2: Adding the cwds submodule',['../group__preparation.html#cwds_submodule',1,'']]],
  ['the_20dc_3a_3a_20prefix_7',['21. Why do I have to use the &lt;span class=&quot;tt&quot;&gt;dc::&lt;/span&gt; prefix?',['../group__tutorial-faq.html#faq_prefix',1,'']]],
  ['the_20debug_20around_20it_8',['6. Why do I need to type the &lt;span class=&quot;tt&quot;&gt;Debug(  )&lt;/span&gt; around it?',['../group__tutorial-faq.html#faq_debug',1,'']]],
  ['the_20debug_20channel_20and_20or_20debug_20object_20are_20turned_20off_9',['18. Is the second field of the macro still evaluated when the Debug Channel and/or Debug Object are turned off?',['../group__tutorial-faq.html#faq_evaluation',1,'']]],
  ['the_20debug_20object_10',['Methods of the debug object',['../group__tutorial-advanced.html#tutorial_advanced_methods',1,'']]],
  ['the_20debug_20object_20after_20you_20enable_20a_20debug_20channel_20why_20not_20the_20other_20way_20around_11',['14. Why do you turn on the debug object after you enable a debug channel, why not the other way around?',['../group__tutorial-faq.html#faq_order',1,'']]],
  ['the_20field_20width_20of_20the_20label_20determined_12',['23. Why does it print spaces between the label and the colon? How is the field width of the label determined?',['../group__tutorial-faq.html#faq_labelwidth',1,'']]],
  ['the_20label_20and_20the_20colon_20how_20is_20the_20field_20width_20of_20the_20label_20determined_13',['23. Why does it print spaces between the label and the colon? How is the field width of the label determined?',['../group__tutorial-faq.html#faq_labelwidth',1,'']]],
  ['the_20label_20determined_14',['23. Why does it print spaces between the label and the colon? How is the field width of the label determined?',['../group__tutorial-faq.html#faq_labelwidth',1,'']]],
  ['the_20macro_15',['16. Do I need to type that semi-colon after the macro? Why isn&apos;t it part of the macro?',['../group__tutorial-faq.html#faq_semicolon',1,'']]],
  ['the_20macro_20still_20evaluated_20when_20the_20debug_20channel_20and_20or_20debug_20object_20are_20turned_20off_16',['18. Is the second field of the macro still evaluated when the Debug Channel and/or Debug Object are turned off?',['../group__tutorial-faq.html#faq_evaluation',1,'']]],
  ['the_20macro_20why_20isn_20t_20it_20part_20of_20the_20macro_17',['16. Do I need to type that semi-colon after the macro? Why isn&apos;t it part of the macro?',['../group__tutorial-faq.html#faq_semicolon',1,'']]],
  ['the_20maximum_20length_20of_20a_20label_18',['20. What is the maximum length of a label?',['../group__tutorial-faq.html#faq_label',1,'']]],
  ['the_20other_20way_20around_19',['14. Why do you turn on the debug object after you enable a debug channel, why not the other way around?',['../group__tutorial-faq.html#faq_order',1,'']]],
  ['the_20second_20field_20of_20the_20macro_20still_20evaluated_20when_20the_20debug_20channel_20and_20or_20debug_20object_20are_20turned_20off_20',['18. Is the second field of the macro still evaluated when the Debug Channel and/or Debug Object are turned off?',['../group__tutorial-faq.html#faq_evaluation',1,'']]],
  ['this_20define_20make_20my_20code_20non_20portable_21',['1. Won&apos;t this define make my code non-portable?',['../group__tutorial-faq.html#faq_gnu_source',1,'']]],
  ['to_20configure_20libcwd_20when_20using_20gitache_22',['How to configure libcwd when using gitache',['../group__configuration-options-and-macros.html#autotoc_md126',1,'']]],
  ['to_20type_20that_20semi_20colon_20after_20the_20macro_20why_20isn_20t_20it_20part_20of_20the_20macro_23',['16. Do I need to type that semi-colon after the macro? Why isn&apos;t it part of the macro?',['../group__tutorial-faq.html#faq_semicolon',1,'']]],
  ['to_20type_20the_20debug_20around_20it_24',['6. Why do I need to type the &lt;span class=&quot;tt&quot;&gt;Debug(  )&lt;/span&gt; around it?',['../group__tutorial-faq.html#faq_debug',1,'']]],
  ['to_20use_20the_20dc_3a_3a_20prefix_25',['21. Why do I have to use the &lt;span class=&quot;tt&quot;&gt;dc::&lt;/span&gt; prefix?',['../group__tutorial-faq.html#faq_prefix',1,'']]],
  ['turn_20debug_20channels_20off_20again_20can_20i_20do_20that_20recursively_26',['8. Can I turn Debug Channels off again? Can I do that recursively?',['../group__tutorial-faq.html#faq_recursive',1,'']]],
  ['turn_20debug_20objects_20off_20again_20can_20i_20do_20that_20recursively_27',['11. Can I turn Debug Objects off again? Can I do that recursively?',['../group__tutorial-faq.html#faq_recursive2',1,'']]],
  ['turn_20on_20the_20debug_20object_20after_20you_20enable_20a_20debug_20channel_20why_20not_20the_20other_20way_20around_28',['14. Why do you turn on the debug object after you enable a debug channel, why not the other way around?',['../group__tutorial-faq.html#faq_order',1,'']]],
  ['turned_20off_29',['18. Is the second field of the macro still evaluated when the Debug Channel and/or Debug Object are turned off?',['../group__tutorial-faq.html#faq_evaluation',1,'']]],
  ['turned_20off_20at_20creation_30',['13. Why are Debug Objects turned off at creation?',['../group__tutorial-faq.html#faq_whyoff',1,'']]],
  ['type_20that_20semi_20colon_20after_20the_20macro_20why_20isn_20t_20it_20part_20of_20the_20macro_31',['16. Do I need to type that semi-colon after the macro? Why isn&apos;t it part of the macro?',['../group__tutorial-faq.html#faq_semicolon',1,'']]],
  ['type_20the_20debug_20around_20it_32',['6. Why do I need to type the &lt;span class=&quot;tt&quot;&gt;Debug(  )&lt;/span&gt; around it?',['../group__tutorial-faq.html#faq_debug',1,'']]]
];
