var searchData=
[
  ['dc_3a_3a_20prefix_0',['21. Why do I have to use the &lt;span class=&quot;tt&quot;&gt;dc::&lt;/span&gt; prefix?',['../group__tutorial-faq.html#faq_prefix',1,'']]],
  ['dc_3a_3acontinued_20and_20dc_3a_3afinish_1',['Using continued_cf, dc::continued and dc::finish',['../group__nesting-debug-output.html#using_continued',1,'']]],
  ['dc_3a_3afinish_2',['Using continued_cf, dc::continued and dc::finish',['../group__nesting-debug-output.html#using_continued',1,'']]],
  ['dc_3a_3anotice_20hello_20world_3',['&lt;span class=&quot;tt&quot;&gt;Dout(dc::notice, &quot;Hello World&quot;);&lt;/span&gt;',['../group__tutorial-hello-world.html#autotoc_md134',1,'']]],
  ['dc_3a_3anotice_20on_4',['&lt;span class=&quot;tt&quot;&gt;Debug(dc::notice.on());&lt;/span&gt;',['../group__tutorial-hello-world.html#tutorial_hello_world_turn_on_channel',1,'']]],
  ['debug_20and_20dout_5',['5. Why are you using macros for &lt;span class=&quot;tt&quot;&gt;Debug&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;Dout&lt;/span&gt;?',['../group__tutorial-faq.html#faq_macros',1,'']]],
  ['debug_20around_20it_6',['6. Why do I need to type the &lt;span class=&quot;tt&quot;&gt;Debug(  )&lt;/span&gt; around it?',['../group__tutorial-faq.html#faq_debug',1,'']]],
  ['debug_20channel_7',['9. Why do you call it a Debug &lt;em&gt;Channel&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Channel?',['../group__tutorial-faq.html#faq_channel',1,'']]],
  ['debug_20channel_20and_20or_20debug_20object_20are_20turned_20off_8',['18. Is the second field of the macro still evaluated when the Debug Channel and/or Debug Object are turned off?',['../group__tutorial-faq.html#faq_evaluation',1,'']]],
  ['debug_20channel_20name_20collisions_9',['Debug channel name collisions',['../group__the-custom-debug-h-file.html#debug_channel_name_collisions',1,'']]],
  ['debug_20channel_20what_20is_20a_20debug_20channel_10',['9. Why do you call it a Debug &lt;em&gt;Channel&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Channel?',['../group__tutorial-faq.html#faq_channel',1,'']]],
  ['debug_20channel_20why_20not_20the_20other_20way_20around_11',['14. Why do you turn on the debug object after you enable a debug channel, why not the other way around?',['../group__tutorial-faq.html#faq_order',1,'']]],
  ['debug_20channels_12',['Running over all Debug Channels',['../group__tutorial-advanced.html#tutorial_advanced_running',1,'']]],
  ['debug_20channels_20and_20name_20spaces_13',['Debug Channels and name spaces',['../group__tutorial-advanced.html#tutorial_advanced_debug',1,'']]],
  ['debug_20channels_20and_20namespace_14',['Debug channels and namespace',['../group__the-custom-debug-h-file.html#debug_channels_and_namespace',1,'']]],
  ['debug_20channels_20exist_20can_20i_20make_20my_20own_15',['7. Which Debug Channels exist? Can I make my own?',['../group__tutorial-faq.html#faq_debugchannels',1,'']]],
  ['debug_20channels_20in_20my_20own_20name_20space_16',['22. Can I put my debug channels in my own name space?',['../group__tutorial-faq.html#faq_ownnamespace',1,'']]],
  ['debug_20channels_20off_20again_20can_20i_20do_20that_20recursively_17',['8. Can I turn Debug Channels off again? Can I do that recursively?',['../group__tutorial-faq.html#faq_recursive',1,'']]],
  ['debug_20dc_3a_3anotice_20on_18',['&lt;span class=&quot;tt&quot;&gt;Debug(dc::notice.on());&lt;/span&gt;',['../group__tutorial-hello-world.html#tutorial_hello_world_turn_on_channel',1,'']]],
  ['debug_20h_19',['4. What is defined &lt;em&gt;exactly&lt;/em&gt; in &lt;span class=&quot;tt&quot;&gt;libcwd/debug.h&lt;/span&gt;?',['../group__tutorial-faq.html#faq_debug_h',1,'']]],
  ['debug_20libcw_5fdo_20on_20',['&lt;span class=&quot;tt&quot;&gt;Debug(libcw_do.on());&lt;/span&gt;',['../group__tutorial-hello-world.html#autotoc_md133',1,'']]],
  ['debug_20namespace_5fdebug_3a_3ainit_21',['&lt;span class=&quot;tt&quot;&gt;Debug(NAMESPACE_DEBUG::init());&lt;/span&gt;',['../group__tutorial-hello-world.html#tutorial_hello_world_main_reached',1,'']]],
  ['debug_20object_22',['Debug Object',['../group__tutorial-faq.html#faq_owndebugobject',1,'10. Can I make my own Debug Object?'],['../group__tutorial-faq.html#faq_setostream',1,'12. How do I set a new &lt;span class=&quot;tt&quot;&gt;ostream&lt;/span&gt; for a given Debug Object?'],['../group__tutorial-faq.html#faq_object',1,'15. Why do you call it a Debug &lt;em&gt;Object&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Object?']]],
  ['debug_20object_23',['Methods of the debug object',['../group__tutorial-advanced.html#tutorial_advanced_methods',1,'']]],
  ['debug_20object_20after_20you_20enable_20a_20debug_20channel_20why_20not_20the_20other_20way_20around_24',['14. Why do you turn on the debug object after you enable a debug channel, why not the other way around?',['../group__tutorial-faq.html#faq_order',1,'']]],
  ['debug_20object_20are_20turned_20off_25',['18. Is the second field of the macro still evaluated when the Debug Channel and/or Debug Object are turned off?',['../group__tutorial-faq.html#faq_evaluation',1,'']]],
  ['debug_20object_20can_20i_20still_20use_20dout_26',['17. I made my own Debug Object, can I still use &lt;span class=&quot;tt&quot;&gt;Dout&lt;/span&gt;?',['../group__tutorial-faq.html#faq_libcwdout',1,'']]],
  ['debug_20object_20what_20is_20a_20debug_20object_27',['15. Why do you call it a Debug &lt;em&gt;Object&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Object?',['../group__tutorial-faq.html#faq_object',1,'']]],
  ['debug_20objects_20off_20again_20can_20i_20do_20that_20recursively_28',['11. Can I turn Debug Objects off again? Can I do that recursively?',['../group__tutorial-faq.html#faq_recursive2',1,'']]],
  ['debug_20objects_20turned_20off_20at_20creation_29',['13. Why are Debug Objects turned off at creation?',['../group__tutorial-faq.html#faq_whyoff',1,'']]],
  ['debug_20output_30',['Debug Output',['../quick-reference.html#autotoc_md6',1,'']]],
  ['debug_20output_31',['Formatting debug output',['../group__tutorial-advanced.html#tutorial_advanced_formatting',1,'']]],
  ['dec_202005_32',['13 Dec 2005',['../release-notes.html#autotoc_md31',1,'']]],
  ['define_20make_20my_20code_20non_20portable_33',['1. Won&apos;t this define make my code non-portable?',['../group__tutorial-faq.html#faq_gnu_source',1,'']]],
  ['defined_20exactly_20in_20libcwd_20debug_20h_34',['4. What is defined &lt;em&gt;exactly&lt;/em&gt; in &lt;span class=&quot;tt&quot;&gt;libcwd/debug.h&lt;/span&gt;?',['../group__tutorial-faq.html#faq_debug_h',1,'']]],
  ['defining_35',['Defining',['../group__function-objects.html#autotoc_md128',1,'']]],
  ['defining_20and_20initializing_20function_20objects_36',['Defining and initializing &lt;span class=&quot;tt&quot;&gt;Function&lt;/span&gt; objects',['../group__function-objects.html#autotoc_md127',1,'']]],
  ['determined_37',['23. Why does it print spaces between the label and the colon? How is the field width of the label determined?',['../group__tutorial-faq.html#faq_labelwidth',1,'']]],
  ['do_20i_20have_20to_20use_20the_20dc_3a_3a_20prefix_38',['21. Why do I have to use the &lt;span class=&quot;tt&quot;&gt;dc::&lt;/span&gt; prefix?',['../group__tutorial-faq.html#faq_prefix',1,'']]],
  ['do_20i_20need_20to_20type_20that_20semi_20colon_20after_20the_20macro_20why_20isn_20t_20it_20part_20of_20the_20macro_39',['16. Do I need to type that semi-colon after the macro? Why isn&apos;t it part of the macro?',['../group__tutorial-faq.html#faq_semicolon',1,'']]],
  ['do_20i_20need_20to_20type_20the_20debug_20around_20it_40',['6. Why do I need to type the &lt;span class=&quot;tt&quot;&gt;Debug(  )&lt;/span&gt; around it?',['../group__tutorial-faq.html#faq_debug',1,'']]],
  ['do_20i_20set_20a_20new_20ostream_20for_20a_20given_20debug_20object_41',['12. How do I set a new &lt;span class=&quot;tt&quot;&gt;ostream&lt;/span&gt; for a given Debug Object?',['../group__tutorial-faq.html#faq_setostream',1,'']]],
  ['do_20that_20recursively_42',['do that recursively',['../group__tutorial-faq.html#faq_recursive2',1,'11. Can I turn Debug Objects off again? Can I do that recursively?'],['../group__tutorial-faq.html#faq_recursive',1,'8. Can I turn Debug Channels off again? Can I do that recursively?']]],
  ['do_20you_20call_20it_20a_20debug_20channel_20what_20is_20a_20debug_20channel_43',['9. Why do you call it a Debug &lt;em&gt;Channel&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Channel?',['../group__tutorial-faq.html#faq_channel',1,'']]],
  ['do_20you_20call_20it_20a_20debug_20object_20what_20is_20a_20debug_20object_44',['15. Why do you call it a Debug &lt;em&gt;Object&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Object?',['../group__tutorial-faq.html#faq_object',1,'']]],
  ['do_20you_20turn_20on_20the_20debug_20object_20after_20you_20enable_20a_20debug_20channel_20why_20not_20the_20other_20way_20around_45',['14. Why do you turn on the debug object after you enable a debug channel, why not the other way around?',['../group__tutorial-faq.html#faq_order',1,'']]],
  ['documentation_46',['Documentation',['../index.html#autotoc_md2',1,'']]],
  ['does_20it_20print_20spaces_20between_20the_20label_20and_20the_20colon_20how_20is_20the_20field_20width_20of_20the_20label_20determined_47',['23. Why does it print spaces between the label and the colon? How is the field width of the label determined?',['../group__tutorial-faq.html#faq_labelwidth',1,'']]],
  ['dout_48',['Dout',['../group__tutorial-faq.html#faq_libcwdout',1,'17. I made my own Debug Object, can I still use &lt;span class=&quot;tt&quot;&gt;Dout&lt;/span&gt;?'],['../group__tutorial-faq.html#faq_macros',1,'5. Why are you using macros for &lt;span class=&quot;tt&quot;&gt;Debug&lt;/span&gt; and &lt;span class=&quot;tt&quot;&gt;Dout&lt;/span&gt;?'],['../group__nesting-debug-output.html#section_nesting_calling',1,'Calling functions inside Dout']]],
  ['dout_20dc_3a_3anotice_20hello_20world_49',['&lt;span class=&quot;tt&quot;&gt;Dout(dc::notice, &quot;Hello World&quot;);&lt;/span&gt;',['../group__tutorial-hello-world.html#autotoc_md134',1,'']]]
];
