var searchData=
[
  ['object_0',['Object',['../group__tutorial-faq.html#faq_owndebugobject',1,'10. Can I make my own Debug Object?'],['../group__tutorial-faq.html#faq_setostream',1,'12. How do I set a new &lt;span class=&quot;tt&quot;&gt;ostream&lt;/span&gt; for a given Debug Object?'],['../group__tutorial-faq.html#faq_object',1,'15. Why do you call it a Debug &lt;em&gt;Object&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Object?']]],
  ['object_1',['Methods of the debug object',['../group__tutorial-advanced.html#tutorial_advanced_methods',1,'']]],
  ['object_20after_20you_20enable_20a_20debug_20channel_20why_20not_20the_20other_20way_20around_2',['14. Why do you turn on the debug object after you enable a debug channel, why not the other way around?',['../group__tutorial-faq.html#faq_order',1,'']]],
  ['object_20are_20turned_20off_3',['18. Is the second field of the macro still evaluated when the Debug Channel and/or Debug Object are turned off?',['../group__tutorial-faq.html#faq_evaluation',1,'']]],
  ['object_20can_20i_20still_20use_20dout_4',['17. I made my own Debug Object, can I still use &lt;span class=&quot;tt&quot;&gt;Dout&lt;/span&gt;?',['../group__tutorial-faq.html#faq_libcwdout',1,'']]],
  ['object_20what_20is_20a_20debug_20object_5',['15. Why do you call it a Debug &lt;em&gt;Object&lt;/em&gt;? What &lt;em&gt;is&lt;/em&gt; a Debug Object?',['../group__tutorial-faq.html#faq_object',1,'']]],
  ['objects_6',['Defining and initializing &lt;span class=&quot;tt&quot;&gt;Function&lt;/span&gt; objects',['../group__function-objects.html#autotoc_md127',1,'']]],
  ['objects_20off_20again_20can_20i_20do_20that_20recursively_7',['11. Can I turn Debug Objects off again? Can I do that recursively?',['../group__tutorial-faq.html#faq_recursive2',1,'']]],
  ['objects_20turned_20off_20at_20creation_8',['13. Why are Debug Objects turned off at creation?',['../group__tutorial-faq.html#faq_whyoff',1,'']]],
  ['oct_202004_9',['8 Oct 2004',['../release-notes.html#autotoc_md39',1,'']]],
  ['october_202000_10',['11 October 2000',['../release-notes.html#autotoc_md113',1,'']]],
  ['of_20a_20label_11',['20. What is the maximum length of a label?',['../group__tutorial-faq.html#faq_label',1,'']]],
  ['of_20libraries_12',['Header files of libraries',['../group__the-custom-debug-h-file.html#header_files_of_libraries',1,'']]],
  ['of_20the_20debug_20object_13',['Methods of the debug object',['../group__tutorial-advanced.html#tutorial_advanced_methods',1,'']]],
  ['of_20the_20label_20determined_14',['23. Why does it print spaces between the label and the colon? How is the field width of the label determined?',['../group__tutorial-faq.html#faq_labelwidth',1,'']]],
  ['of_20the_20macro_15',['16. Do I need to type that semi-colon after the macro? Why isn&apos;t it part of the macro?',['../group__tutorial-faq.html#faq_semicolon',1,'']]],
  ['of_20the_20macro_20still_20evaluated_20when_20the_20debug_20channel_20and_20or_20debug_20object_20are_20turned_20off_16',['18. Is the second field of the macro still evaluated when the Debug Channel and/or Debug Object are turned off?',['../group__tutorial-faq.html#faq_evaluation',1,'']]],
  ['off_17',['18. Is the second field of the macro still evaluated when the Debug Channel and/or Debug Object are turned off?',['../group__tutorial-faq.html#faq_evaluation',1,'']]],
  ['off_20again_20can_20i_20do_20that_20recursively_18',['off again Can I do that recursively',['../group__tutorial-faq.html#faq_recursive2',1,'11. Can I turn Debug Objects off again? Can I do that recursively?'],['../group__tutorial-faq.html#faq_recursive',1,'8. Can I turn Debug Channels off again? Can I do that recursively?']]],
  ['off_20at_20creation_19',['13. Why are Debug Objects turned off at creation?',['../group__tutorial-faq.html#faq_whyoff',1,'']]],
  ['on_20',['on',['../group__tutorial-hello-world.html#tutorial_hello_world_turn_on_channel',1,'&lt;span class=&quot;tt&quot;&gt;Debug(dc::notice.on());&lt;/span&gt;'],['../group__tutorial-hello-world.html#autotoc_md133',1,'&lt;span class=&quot;tt&quot;&gt;Debug(libcw_do.on());&lt;/span&gt;']]],
  ['on_20the_20debug_20object_20after_20you_20enable_20a_20debug_20channel_20why_20not_20the_20other_20way_20around_21',['14. Why do you turn on the debug object after you enable a debug channel, why not the other way around?',['../group__tutorial-faq.html#faq_order',1,'']]],
  ['or_20debug_20object_20are_20turned_20off_22',['18. Is the second field of the macro still evaluated when the Debug Channel and/or Debug Object are turned off?',['../group__tutorial-faq.html#faq_evaluation',1,'']]],
  ['ostream_20for_20a_20given_20debug_20object_23',['12. How do I set a new &lt;span class=&quot;tt&quot;&gt;ostream&lt;/span&gt; for a given Debug Object?',['../group__tutorial-faq.html#faq_setostream',1,'']]],
  ['other_20way_20around_24',['14. Why do you turn on the debug object after you enable a debug channel, why not the other way around?',['../group__tutorial-faq.html#faq_order',1,'']]],
  ['output_25',['Debug Output',['../quick-reference.html#autotoc_md6',1,'']]],
  ['output_26',['Formatting debug output',['../group__tutorial-advanced.html#tutorial_advanced_formatting',1,'']]],
  ['over_20all_20debug_20channels_27',['Running over all Debug Channels',['../group__tutorial-advanced.html#tutorial_advanced_running',1,'']]],
  ['own_28',['7. Which Debug Channels exist? Can I make my own?',['../group__tutorial-faq.html#faq_debugchannels',1,'']]],
  ['own_20debug_20object_29',['10. Can I make my own Debug Object?',['../group__tutorial-faq.html#faq_owndebugobject',1,'']]],
  ['own_20debug_20object_20can_20i_20still_20use_20dout_30',['17. I made my own Debug Object, can I still use &lt;span class=&quot;tt&quot;&gt;Dout&lt;/span&gt;?',['../group__tutorial-faq.html#faq_libcwdout',1,'']]],
  ['own_20name_20space_31',['22. Can I put my debug channels in my own name space?',['../group__tutorial-faq.html#faq_ownnamespace',1,'']]]
];
