ircproxy The Ultimate Cyborg
AuthState Class Reference
#include <AuthState.h>
Detailed Description
State information very early in a new connection.
Definition at line 29 of file AuthState.h.
Public Member Functions
AuthState (ServerConnection &server_connection)
Contruct a new AuthState object, starting a new authentication cycle.
~AuthState ()
@ brief Destructor of AuthState.
void set_auth_ping_argument (std::string const &auth_ping_argument)
Remember the argument of the first PING.
std::string const & auth_ping_argument (void) const
Return argument of the first PING.
void auth_notice_looking_up_hostname (MatcherEventType const &event_type)
This function is called when a NOTICE AUTH message is received from the server.
void auth_notice_fin_hostname (MatcherEventType const &event_type)
This function is called when a NOTICE AUTH message is received from the server.
void auth_notice_looking_up_ident (MatcherEventType const &event_type)
This function is called when a NOTICE AUTH message is received from the server.
void auth_notice_fin_ident (MatcherEventType const &event_type)
This function is called when a NOTICE AUTH message is received from the server.
void auth_timeout (timer_event_type_ct const &expired_at)
This function is called one second after connection attempt.
void send_pong_and_mode (ExpressionEventType const &event_type)
Call ServerConnection::send_pong_and_mode.
Private Attributes
ServerConnection & M_server_connection
Reference to the underlying server connection.
Bool M_auth_one_second_passed
Set to true one second after connect.
Watched< std::string > M_auth_ping_argument
The argument of the first PING message.
Bool M_doing_hostname_lookup
Set to true if the notice '*** Looking up your hostname' was received.
Bool M_finished_hostname_lookup
Set to true if the hostname lookup finished.
Bool M_doing_ident_lookup
Set to true if the notice '*** Checking Ident' was received.
Bool M_finished_ident_lookup
Set to true if the ident lookup finished.
Constructor & Destructor Documentation
AuthState::AuthState (ServerConnection & server_connection)
Contruct a new AuthState object, starting a new authentication cycle.
Definition at line 28 of file AuthState.cc.
References auth_notice_looking_up_hostname(), auth_notice_looking_up_ident(), auth_timeout(), Identity::authentication(), IdentityReference::identity(), M_auth_one_second_passed, M_auth_ping_argument, M_doing_hostname_lookup, M_doing_ident_lookup, M_finished_hostname_lookup, M_finished_ident_lookup, M_server_connection, ServerSession::message_event_server(), debug::channels::dc::objects, ServerConnection::secondary_connection(), Authentication::send_authentication(), send_pong_and_mode(), and ServerConnection::server_session().
                                                        : event_client_ct(), M_server_connection(server_connection)
#ifdef CWDEBUG
      , M_auth_one_second_passed("AuthState::M_auth_one_second_passed"),
      M_auth_ping_argument("AuthState::M_auth_ping_argument"),
      M_doing_hostname_lookup("AuthState::M_doing_hostname_lookup"),
      M_finished_hostname_lookup("AuthState::M_finished_hostname_lookup"),
      M_doing_ident_lookup("AuthState::M_doing_ident_lookup"),
      M_finished_ident_lookup("AuthState::M_finished_ident_lookup")
#endif
{
  Dout(dc::objects, "Constructing AuthState(" << server_connection << ')');
  // We can't send a MODE <mynick> messages right away.
  // Instead we have to wait 1 second to see if the server is sending us NOTICE AUTH messages or not.
  // If it is, we have to wait until it's done with that.
  // Set M_doing_hostname_lookup if appropriate, and M_finished_hostname_lookup when finished.
  MatchRequest match_request1(M_server_connection.secondary_connection());
  match_request1(keys::NOTICE).exactmatch("AUTH", 0).exactmatch("*** Looking up your hostname", 1);
  M_server_connection.server_session().message_event_server()(match_request1, *this, &AuthState::auth_notice_looking_up_hostname);
  // Set M_doing_ident_lookup if appropriate, and M_finished_ident_lookup when finished.
  MatchRequest match_request2(M_server_connection.secondary_connection());
  match_request2(keys::NOTICE).exactmatch("AUTH", 0).exactmatch("*** Checking Ident", 1);
  M_server_connection.server_session().message_event_server()(match_request2, *this, &AuthState::auth_notice_looking_up_ident);
  // Set M_auth_one_second_passed 1 second from now.
  timeval delay = { 1, 0 };
  timerRequest(delay, *this, &AuthState::auth_timeout);
  // As soon as it is safe to sent PONG and MODE in one burst, call send_pong_and_mode().
  ON_TRUE(
      ((*M_auth_one_second_passed &&
        (!*M_doing_hostname_lookup || *M_finished_hostname_lookup) &&
        (!*M_doing_ident_lookup || *M_finished_ident_lookup)) ||
       (*M_finished_hostname_lookup &&
        *M_finished_ident_lookup)) &&
      *M_auth_ping_argument != ConstExpression<std::string>(""),
       *this, &AuthState::send_pong_and_mode);
  // Start the authentication.
  M_server_connection.identity().authentication().send_authentication(M_server_connection);
}
AuthState::~AuthState ()
@ brief Destructor of AuthState.
Definition at line 83 of file AuthState.cc.
References debug::channels::dc::objects.
{
  Dout(dc::objects, "Destructing AuthState " << *this << ".");
  cancel_all_requests();
}
Member Function Documentation
void AuthState::set_auth_ping_argument (std::string const & auth_ping_argument) [inline]
Remember the argument of the first PING.
Definition at line 43 of file AuthState.h.
References M_auth_ping_argument.
{ M_auth_ping_argument = auth_ping_argument; }
std::string const& AuthState::auth_ping_argument (void) const [inline]
Return argument of the first PING.
Definition at line 45 of file AuthState.h.
References M_auth_ping_argument, and Watched< T >::value().
{ return M_auth_ping_argument.value(); }
void AuthState::auth_notice_looking_up_hostname (MatcherEventType const & event_type)
This function is called when a NOTICE AUTH message is received from the server.
Never call this function directly.
Definition at line 103 of file AuthState.cc.
References auth_notice_fin_hostname(), DoutEntering, M_doing_hostname_lookup, M_server_connection, ServerSession::message_event_server(), ServerConnection::secondary_connection(), ServerConnection::server_session(), and ServerConnection::successful_connection().
Referenced by AuthState().
{
  DoutEntering(dc::debug, "AuthState::auth_notice_looking_up_hostname(" << event_type << ")");
  M_doing_hostname_lookup = true;
  M_server_connection.successful_connection();  // We didn't get throttled.
  MatchRequest match_request(M_server_connection.secondary_connection());
  match_request(keys::NOTICE).exactmatch("AUTH", 0).wildcard("*your hostname*", 1);
  M_server_connection.server_session().message_event_server()(match_request, *this, &AuthState::auth_notice_fin_hostname);
}
void AuthState::auth_notice_fin_hostname (MatcherEventType const & event_type)
This function is called when a NOTICE AUTH message is received from the server.
Never call this function directly.
Definition at line 118 of file AuthState.cc.
References DoutEntering, and M_finished_hostname_lookup.
Referenced by auth_notice_looking_up_hostname().
{
  DoutEntering(dc::debug, "AuthState::auth_notice_fin_hostname(" << event_type << ")");
  M_finished_hostname_lookup = true;
}
void AuthState::auth_notice_looking_up_ident (MatcherEventType const & event_type)
This function is called when a NOTICE AUTH message is received from the server.
Never call this function directly.
Definition at line 128 of file AuthState.cc.
References auth_notice_fin_ident(), DoutEntering, M_doing_ident_lookup, M_server_connection, ServerSession::message_event_server(), ServerConnection::secondary_connection(), ServerConnection::server_session(), and ServerConnection::successful_connection().
Referenced by AuthState().
{
  DoutEntering(dc::debug, "AuthState::auth_notice_looking_up_ident(" << event_type << ")");
  M_doing_ident_lookup = true;
  M_server_connection.successful_connection();  // We didn't get throttled.
  MatchRequest match_request(M_server_connection.secondary_connection());
  match_request(keys::NOTICE).exactmatch("AUTH", 0).wildcard("*ident response*", 1);
  M_server_connection.server_session().message_event_server()(match_request, *this, &AuthState::auth_notice_fin_ident);
}
void AuthState::auth_notice_fin_ident (MatcherEventType const & event_type)
This function is called when a NOTICE AUTH message is received from the server.
Never call this function directly.
Definition at line 143 of file AuthState.cc.
References DoutEntering, and M_finished_ident_lookup.
Referenced by auth_notice_looking_up_ident().
{
  DoutEntering(dc::debug, "AuthState::auth_notice_fin_ident(" << event_type << ")");
  M_finished_ident_lookup = true;
}
void AuthState::auth_timeout (timer_event_type_ct const & expired_at)
This function is called one second after connection attempt.
Never call this function directly.
Definition at line 93 of file AuthState.cc.
References DoutEntering, and M_auth_one_second_passed.
Referenced by AuthState().
{
  DoutEntering(dc::debug, "AuthState::auth_timeout(" << expired_at.get_expire_time() << ")");
  M_auth_one_second_passed = true;
}
void AuthState::send_pong_and_mode (ExpressionEventType const & event_type)
Call ServerConnection::send_pong_and_mode.
Definition at line 75 of file AuthState.cc.
References M_server_connection, and ServerConnection::send_pong_and_mode().
Referenced by AuthState().
{
  M_server_connection.send_pong_and_mode(event_type);
}
Member Data Documentation
ServerConnection& AuthState::M_server_connection [private]
Reference to the underlying server connection.
Definition at line 31 of file AuthState.h.
Referenced by auth_notice_looking_up_hostname(), auth_notice_looking_up_ident(), AuthState(), and send_pong_and_mode().
Bool AuthState::M_auth_one_second_passed [private]
Set to true one second after connect.
Definition at line 32 of file AuthState.h.
Referenced by auth_timeout(), and AuthState().
Watched<std::string> AuthState::M_auth_ping_argument [private]
The argument of the first PING message.
Definition at line 33 of file AuthState.h.
Referenced by auth_ping_argument(), AuthState(), and set_auth_ping_argument().
Bool AuthState::M_doing_hostname_lookup [private]
Set to true if the notice '*** Looking up your hostname' was received.
Definition at line 34 of file AuthState.h.
Referenced by auth_notice_looking_up_hostname(), and AuthState().
Bool AuthState::M_finished_hostname_lookup [private]
Set to true if the hostname lookup finished.
Definition at line 35 of file AuthState.h.
Referenced by auth_notice_fin_hostname(), and AuthState().
Bool AuthState::M_doing_ident_lookup [private]
Set to true if the notice '*** Checking Ident' was received.
Definition at line 36 of file AuthState.h.
Referenced by auth_notice_looking_up_ident(), and AuthState().
Bool AuthState::M_finished_ident_lookup [private]
Set to true if the ident lookup finished.
Definition at line 37 of file AuthState.h.
Referenced by auth_notice_fin_ident(), and AuthState().
The documentation for this class was generated from the following files:
AuthState.h
AuthState.cc
Copyright © 2005-2007 Carlo Wood. All rights reserved.