ircproxy The Ultimate Cyborg
IdentityReference Class Reference
#include <IdentityReference.h>
Detailed Description
Base class for classes that always are related to exactly one Identity.
Definition at line 22 of file IdentityReference.h.
Public Member Functions
Identity const & identity (void) const
Returns a const reference to the underlying identity.
Identity & identity (void)
Returns a reference to the underlying identity.
bool has_identity (void) const
Returns true when this object is associated with an Identity.
Protected Member Functions
IdentityReference (void)
Default constructor.
IdentityReference (Identity *identity)
Construct an IdentityReference instance for identity identity.
void set_identity (Identity *identity)
Initialize the underlying Identity pointer.
Private Attributes
Identity * M_identity
Pointer to the identity that this session is related to.
Constructor & Destructor Documentation
IdentityReference::IdentityReference (void) [inline, protected]
Default constructor.
Definition at line 28 of file IdentityReference.h.
: M_identity(NULL) { }
IdentityReference::IdentityReference (Identity * identity) [inline, protected]
Construct an IdentityReference instance for identity identity.
Definition at line 30 of file IdentityReference.h.
: M_identity(identity) { }
Member Function Documentation
void IdentityReference::set_identity (Identity * identity) [inline, protected]
Initialize the underlying Identity pointer.
Definition at line 33 of file IdentityReference.h.
References ASSERT, and M_identity.
Referenced by ClientSession::new_message_received().
{ ASSERT(!M_identity); M_identity = identity; }
Identity const& IdentityReference::identity (void) const [inline]
Returns a const reference to the underlying identity.
Definition at line 37 of file IdentityReference.h.
References M_identity.
Referenced by AuthState::AuthState(), ServerConnection::connect(), ServerSession::construct_network_object(), ClientSession::create_private_target(), Authentication::decode_pass(), ServerSession::detected_network(), ServerConnection::do_connect(), PrivateTarget::do_names_output(), ServerSession::found_network_name(), Authentication::get(), ServerSession::get_nick(), PrivateTarget::handle_command(), ServerConnection::invisible_event(), UserAnswer::is_match(), ServerSession::network_connection_terminated(), QuestionTarget::new_client_message_received(), PrivateTarget::new_client_message_received(), Channel::new_client_message_received(), ClientSession::new_client_nick_received(), ServerSession::new_message_received(), ClientSession::new_message_received(), Channel::new_server_message_received(), operator<<(), ClientSession::process_message(), ClientSession::queue_msg_me_as_is(), ServerConnection::received_first_umode(), Authentication::received_nick_and_user(), ServerConnection::received_server_port_answer(), Authentication::send_authentication(), ServerSession::send_rejoins(), ClientSession::serversession_lost(), ServerConnection::session_lost(), and ClientSession::~ClientSession().
{ return *M_identity; }
Identity& IdentityReference::identity (void) [inline]
Returns a reference to the underlying identity.
Definition at line 40 of file IdentityReference.h.
References M_identity.
{ return *M_identity; }
bool IdentityReference::has_identity (void) const [inline]
Returns true when this object is associated with an Identity.
Definition at line 43 of file IdentityReference.h.
References M_identity.
Referenced by ClientSession::new_message_received(), operator<<(), and ClientSession::~ClientSession().
{ return M_identity; }
Member Data Documentation
Identity* IdentityReference::M_identity [private]
Pointer to the identity that this session is related to.
Definition at line 24 of file IdentityReference.h.
Referenced by has_identity(), identity(), and set_identity().
The documentation for this class was generated from the following file:
IdentityReference.h
Copyright © 2005-2007 Carlo Wood. All rights reserved.