ircproxy The Ultimate Cyborg
ISupport Class Reference
#include <ISupport.h>
Detailed Description
Stores the ISUPPORT reply (005) key/value pairs of the network.
Definition at line 26 of file ISupport.h.
Public Types
typedef std::map< std::string,
std::string > key_value_map_type
The type of M_key_value_map.
Public Member Functions
void begin (void)
This function is called when a new connection is initiated (when receiving numeric 004).
void end (void)
This function is called as soon as possible after the last 005 message is received.
void add (std::string const &param)
This function is called for every "key=value" pair in each 005 message.
bool get (std::string const &key, std::string &value)
If key exists, returns true and writes the corresponding value to value, otherwise returns false.
Private Attributes
ServerConnection & M_server_connection
Reference to the underlying server connection.
key_value_map_type M_key_value_map
The map storing all numeric 005 key/value pairs.
Member Typedef Documentation
typedef std::map<std::string, std::string> ISupport::key_value_map_type
The type of M_key_value_map.
Definition at line 29 of file ISupport.h.
Member Function Documentation
void ISupport::begin (void)
This function is called when a new connection is initiated (when receiving numeric 004).
Definition at line 24 of file ISupport.cc.
References M_key_value_map.
Referenced by ServerSession::new_message_received().
{
  M_key_value_map.clear();
}
void ISupport::end (void)
This function is called as soon as possible after the last 005 message is received.
Definition at line 29 of file ISupport.cc.
References ServerSession::found_network_name(), M_server_connection, and ServerConnection::server_session().
Referenced by ServerSession::new_message_received().
{
  M_server_connection.server_session().found_network_name();
}
void ISupport::add (std::string const & param)
This function is called for every "key=value" pair in each 005 message.
Definition at line 34 of file ISupport.cc.
References DoutEntering, and M_key_value_map.
Referenced by ServerSession::new_message_received().
{
  DoutEntering(dc::debug, "ISupport::add(" << param << ")");
  std::string::size_type pos = param.find('=');
  if (pos == std::string::npos)
    M_key_value_map.insert(key_value_map_type::value_type(param, std::string()));
  else
    M_key_value_map.insert(key_value_map_type::value_type(param.substr(0, pos), param.substr(pos + 1)));
}
bool ISupport::get (std::string const & key, std::string & value)
If key exists, returns true and writes the corresponding value to value, otherwise returns false.
Definition at line 44 of file ISupport.cc.
References M_key_value_map.
Referenced by ServerSession::detected_network().
{
  key_value_map_type::const_iterator iter = M_key_value_map.find(key);
  if (iter == M_key_value_map.end())
    return false;
  value = iter->second;
  return true;
}
Member Data Documentation
ServerConnection& ISupport::M_server_connection [private]
Reference to the underlying server connection.
Definition at line 32 of file ISupport.h.
Referenced by end().
key_value_map_type ISupport::M_key_value_map [private]
The map storing all numeric 005 key/value pairs.
Definition at line 33 of file ISupport.h.
Referenced by add(), begin(), and get().
The documentation for this class was generated from the following files:
ISupport.h
ISupport.cc
Copyright © 2005-2007 Carlo Wood. All rights reserved.