ircproxy The Ultimate Cyborg
ClientMessageIn Class Reference
#include <MessageIn.h>
Detailed Description
An IRC message as received from a client.
Definition at line 187 of file MessageIn.h.
Public Member Functions
ClientMessageIn (ClientSession *client_session)
Construct a ClientMessageIn that was received via client session client_session.
ClientMessageIn (ClientMessageIn const &msg)
Copy-constructor.
~ClientMessageIn ()
Destructor.
ClientSession & client_session (void) const
Accessor for M_client_session.
Protected Member Functions
virtual bool is_server_message (void) const
Return true if this is a ServerMessageIn.
virtual ClientSession & priv_client_session (void) const
The session of the derived class.
virtual ServerSession & priv_server_session (void) const
The session of the derived class.
Private Attributes
ClientSession * M_client_session
The client session over which this message was received.
Constructor & Destructor Documentation
ClientMessageIn::ClientMessageIn (ClientSession * client_session) [inline]
Construct a ClientMessageIn that was received via client session client_session.
Definition at line 192 of file MessageIn.h.
: M_client_session(client_session) { }
ClientMessageIn::ClientMessageIn (ClientMessageIn const & msg) [inline]
Copy-constructor.
Definition at line 195 of file MessageIn.h.
References debug::channels::dc::objects.
                                                : MessageIn(msg), M_client_session(msg.M_client_session)
        { Dout(dc::objects, "Copy-constructing ClientMessageIn from " << msg); }
ClientMessageIn::~ClientMessageIn () [inline]
Destructor.
Definition at line 198 of file MessageIn.h.
References debug::channels::dc::objects.
{ Dout(dc::objects, "Destructing ClientMessageIn " << *this); }
Member Function Documentation
ClientSession& ClientMessageIn::client_session (void) const [inline]
Accessor for M_client_session.
Definition at line 202 of file MessageIn.h.
Referenced by QuestionTarget::new_client_message_received(), PrivateTarget::new_client_message_received(), NoticeTarget::new_client_message_received(), Nick::new_client_message_received(), Identity::new_client_message_received(), Channel::new_client_message_received(), operator<<(), and Prefix::Prefix().
{ return *M_client_session; }
virtual bool ClientMessageIn::is_server_message (void) const [inline, protected, virtual]
Return true if this is a ServerMessageIn.
Implements MessageIn.
Definition at line 205 of file MessageIn.h.
{ return false; }
virtual ClientSession& ClientMessageIn::priv_client_session (void) const [inline, protected, virtual]
The session of the derived class.
Implements MessageIn.
Definition at line 207 of file MessageIn.h.
{ return client_session(); }
virtual ServerSession& ClientMessageIn::priv_server_session (void) const [inline, protected, virtual]
The session of the derived class.
Implements MessageIn.
Definition at line 208 of file MessageIn.h.
{ DoutFatal(dc::core, "Calling MessageIn::server_session() for ClientMessageIn"); }
Member Data Documentation
ClientSession* ClientMessageIn::M_client_session [private]
The client session over which this message was received.
Definition at line 189 of file MessageIn.h.
The documentation for this class was generated from the following file:
MessageIn.h
Copyright © 2005-2007 Carlo Wood. All rights reserved.