ircproxy The Ultimate Cyborg
UserAnswerRequestData Class Reference
#include <UserAnswer.h>
Detailed Description
Request data passed to the event server.
Definition at line 76 of file UserAnswer.h.
Public Member Functions
UserAnswerRequestData (ClientSession &client_session, question_nt question_number, std::string const &question)
Construct UserAnswerRequestData for client session client_session with question index question_number and question string question.
std::string const & question (void) const
Return the associated question string.
boost::shared_ptr< UserQuestion > user_question (void)
Return the associated question.
ClientSession & client_session (void)
Return associated client session.
ClientSession const & client_session (void) const
Return associated client session.
Private Attributes
ClientSession & M_client_session
The related client session.
boost::shared_ptr< UserQuestion > M_question
Pointer to the associated question.
Constructor & Destructor Documentation
UserAnswerRequestData::UserAnswerRequestData (ClientSession & client_session, question_nt question_number, std::string const & question) [inline]
Construct UserAnswerRequestData for client session client_session with question index question_number and question string question.
Definition at line 83 of file UserAnswer.h.
                                                                                                               :
      M_client_session(client_session), M_question(NEW(UserQuestion(question_number, question))) { }
Member Function Documentation
std::string const& UserAnswerRequestData::question (void) const [inline]
Return the associated question string.
Definition at line 87 of file UserAnswer.h.
References M_question.
Referenced by operator<<().
{ return M_question->question(); }
boost::shared_ptr<UserQuestion> UserAnswerRequestData::user_question (void) [inline]
Return the associated question.
Definition at line 89 of file UserAnswer.h.
References M_question.
Referenced by UserAnswerEventRequestBase::UserAnswerEventRequestBase().
{ return M_question; }
ClientSession& UserAnswerRequestData::client_session (void) [inline]
Return associated client session.
Definition at line 91 of file UserAnswer.h.
References M_client_session.
Referenced by operator<<(), and UserAnswerEventRequestBase::UserAnswerEventRequestBase().
{ return M_client_session; }
ClientSession const& UserAnswerRequestData::client_session (void) const [inline]
Return associated client session.
Definition at line 93 of file UserAnswer.h.
References M_client_session.
{ return M_client_session; }
Member Data Documentation
ClientSession& UserAnswerRequestData::M_client_session [private]
The related client session.
Definition at line 78 of file UserAnswer.h.
Referenced by client_session().
boost::shared_ptr<UserQuestion> UserAnswerRequestData::M_question [private]
Pointer to the associated question.
Definition at line 79 of file UserAnswer.h.
Referenced by question(), and user_question().
The documentation for this class was generated from the following file:
UserAnswer.h
Copyright © 2005-2007 Carlo Wood. All rights reserved.