ircproxy The Ultimate Cyborg
UserAnswerEventRequestQueue Class Reference
#include <UserAnswer.h>
Detailed Description
The UserAnswer event request queue class.
Definition at line 122 of file UserAnswer.h.
Public Member Functions
void destroy_requests (void)
Destroy any requests for events left in the queue.
void trigger (UserAnswerEventRequestBase::event_type_ct const &event_type)
Trigger an event.
Protected Member Functions
void add_request (UserAnswerEventRequestBase *request)
Add event request request to the queue.
~UserAnswerEventRequestQueue ()
Destructor.
Private Types
typedef std::deque
< UserAnswerEventRequestBase * > event_requests_ct
The type of the event request queue.
Private Attributes
Counter M_event_requests_locked
Non-zero if M_event_requests is being processed in a loop.
event_requests_ct M_event_requests
The actual event request queue.
event_requests_ct M_event_requests_tmp
Temporary event request queue for when M_event_requests is locked.
Member Typedef Documentation
typedef std::deque<UserAnswerEventRequestBase*> UserAnswerEventRequestQueue::event_requests_ct [private]
The type of the event request queue.
Definition at line 124 of file UserAnswer.h.
Constructor & Destructor Documentation
UserAnswerEventRequestQueue::~UserAnswerEventRequestQueue () [inline, protected]
Destructor.
Definition at line 139 of file UserAnswer.h.
References destroy_requests().
{ destroy_requests(); }
Member Function Documentation
void UserAnswerEventRequestQueue::add_request (UserAnswerEventRequestBase * request) [inline, protected]
Add event request request to the queue.
Definition at line 131 of file UserAnswer.h.
References M_event_requests, M_event_requests_locked, and M_event_requests_tmp.
Referenced by trigger().
      {
        if (M_event_requests_locked)
          M_event_requests_tmp.push_back(request);
        else
          M_event_requests.push_back(request);
      }
void UserAnswerEventRequestQueue::destroy_requests (void) [inline]
Destroy any requests for events left in the queue.
Definition at line 142 of file UserAnswer.h.
References ASSERT, M_event_requests, and M_event_requests_locked.
Referenced by ~UserAnswerEventRequestQueue().
      {
        ASSERT(!M_event_requests_locked);
        while (!M_event_requests.empty())
        {
          M_event_requests.front()->release();
          M_event_requests.pop_front();
        }
      }
void UserAnswerEventRequestQueue::trigger (UserAnswerEventRequestBase::event_type_ct const & event_type) [inline]
Trigger an event.
Definition at line 152 of file UserAnswer.h.
References add_request(), DoutEntering, M_event_requests, M_event_requests_locked, and M_event_requests_tmp.
      {
        DoutEntering(dc::notice, "UserAnswerEventRequestQueue::trigger(" <<
            libcwd::type_info_of<UserAnswerEventRequestBase::event_type_ct>().demangled_name() <<
            " const& " << event_type << ")");
        {
          Increment tmp(M_event_requests_locked);
          event_requests_ct::iterator iter = M_event_requests.begin();
          while (iter != M_event_requests.end())
          {
            if ((*iter)->canceled())
            {
              Dout(dc::notice, "Removing canceled " << **iter);
              (*iter)->release();
              iter = M_event_requests.erase(iter);
            }
            else if (event_type.is_match((*iter)->target()))
            {
              Dout(dc::notice, "Calling handle() for " << **iter);
              (*iter)->handle(event_type);
              (*iter)->release();
              iter = M_event_requests.erase(iter);
            }
            else
              ++iter;
          }
        }
        if (M_event_requests_locked == 0)
          while (!M_event_requests_tmp.empty())
          {
            add_request(M_event_requests_tmp.front());
            M_event_requests_tmp.pop_front();
          }
      }
Member Data Documentation
Counter UserAnswerEventRequestQueue::M_event_requests_locked [private]
Non-zero if M_event_requests is being processed in a loop.
Definition at line 126 of file UserAnswer.h.
Referenced by add_request(), destroy_requests(), and trigger().
event_requests_ct UserAnswerEventRequestQueue::M_event_requests [private]
The actual event request queue.
Definition at line 127 of file UserAnswer.h.
Referenced by add_request(), destroy_requests(), and trigger().
event_requests_ct UserAnswerEventRequestQueue::M_event_requests_tmp [private]
Temporary event request queue for when M_event_requests is locked.
Definition at line 128 of file UserAnswer.h.
Referenced by add_request(), and trigger().
The documentation for this class was generated from the following file:
UserAnswer.h
Copyright © 2005-2007 Carlo Wood. All rights reserved.