ircproxy The Ultimate Cyborg
JustInTimePrefix Class Reference
#include <JustInTime.h>
Detailed Description
A just-in-time Prefix.
Definition at line 120 of file JustInTime.h.
Public Member Functions
JustInTimePrefix (Prefix const &token)
Construct a JustInTimePrefix with value token.
virtual std::string value (ClientSession const &session) const
Return the underlying value.
virtual void write_to (std::ostream &os, ClientSession const &session) const
Write the underlying token, including seperators, to an ostream.
virtual bool is_prefix (void)
Return true if this is a Prefix.
Private Member Functions
virtual std::string value_impl (ClientSession const &session) const
Return the underlying value.
Private Attributes
Prefix M_token
The prefix.
Constructor & Destructor Documentation
JustInTimePrefix::JustInTimePrefix (Prefix const & token) [inline]
Construct a JustInTimePrefix with value token.
Definition at line 129 of file JustInTime.h.
: M_token(token) { }
Member Function Documentation
virtual std::string JustInTimePrefix::value_impl (ClientSession const & session) const [inline, private, virtual]
Return the underlying value.
Definition at line 125 of file JustInTime.h.
References M_token, and Prefix::out_prefix().
Referenced by value(), and write_to().
{ return  M_token.out_prefix(session, true); }
virtual std::string JustInTimePrefix::value (ClientSession const & session) const [inline, virtual]
Return the underlying value.
Implements JustInTimeToken.
Definition at line 131 of file JustInTime.h.
References value_impl().
{ return value_impl(session); }
virtual void JustInTimePrefix::write_to (std::ostream & os, ClientSession const & session) const [inline, virtual]
Write the underlying token, including seperators, to an ostream.
Implements JustInTimeToken.
Definition at line 134 of file JustInTime.h.
References value_impl().
{ os << ':' << value_impl(session) << ' '; }
virtual bool JustInTimePrefix::is_prefix (void) [inline, virtual]
Return true if this is a Prefix.
Reimplemented from JustInTimeToken.
Definition at line 137 of file JustInTime.h.
{ return true; }
Member Data Documentation
Prefix JustInTimePrefix::M_token [private]
The prefix.
Definition at line 122 of file JustInTime.h.
Referenced by value_impl().
The documentation for this class was generated from the following file:
JustInTime.h
Copyright © 2005-2007 Carlo Wood. All rights reserved.