ircproxy The Ultimate Cyborg
JustInTimeTarget Class Reference
#include <JustInTime.h>
Detailed Description
A just-in-time target.
Definition at line 84 of file JustInTime.h.
Public Member Functions
JustInTimeTarget (boost::shared_ptr< Target > const &target)
Constructor.
virtual std::string value (ClientSession const &session) const
Return the underlying value.
virtual void write_to (std::ostream &os, ClientSession const &session) const
Write the underlying token, including seperators, to an ostream.
Private Member Functions
std::string value_impl (ClientSession const &session) const
Return the underlying value.
Private Attributes
boost::shared_ptr< Target > M_target
Underlaying token.
Constructor & Destructor Documentation
JustInTimeTarget::JustInTimeTarget (boost::shared_ptr< Target > const & target) [inline]
Constructor.
Definition at line 93 of file JustInTime.h.
: M_target(target) { }
Member Function Documentation
std::string JustInTimeTarget::value_impl (ClientSession const & session) const [inline, private]
Return the underlying value.
Definition at line 89 of file JustInTime.h.
References M_target.
Referenced by value(), and write_to().
{ return M_target->out_name(session); }
virtual std::string JustInTimeTarget::value (ClientSession const & session) const [inline, virtual]
Return the underlying value.
Implements JustInTimeToken.
Definition at line 95 of file JustInTime.h.
References value_impl().
{ return value_impl(session); }
virtual void JustInTimeTarget::write_to (std::ostream & os, ClientSession const & session) const [inline, virtual]
Write the underlying token, including seperators, to an ostream.
Implements JustInTimeToken.
Definition at line 98 of file JustInTime.h.
References value_impl().
{ os << ' ' << value_impl(session); }
Member Data Documentation
boost::shared_ptr<Target> JustInTimeTarget::M_target [private]
Underlaying token.
Definition at line 86 of file JustInTime.h.
Referenced by value_impl().
The documentation for this class was generated from the following file:
JustInTime.h
Copyright © 2005-2007 Carlo Wood. All rights reserved.