ircproxy The Ultimate Cyborg
ServerMessageIn Class Reference
#include <MessageIn.h>
Detailed Description
An IRC message as received from a server.
Definition at line 215 of file MessageIn.h.
Public Member Functions
ServerMessageIn (ServerSession *server_session)
Construct a ServerMessageIn that was received via server session server_session.
ServerMessageIn (ServerMessageIn const &msg)
Copy-constructor.
~ServerMessageIn ()
Destructor.
ServerSession & server_session (void) const
Accessor for M_server_session.
Protected Member Functions
virtual bool is_server_message (void) const
Return true if this is a ServerMessageIn.
virtual ClientSession & priv_client_session (void) const
The session of the derived class.
virtual ServerSession & priv_server_session (void) const
The session of the derived class.
Private Attributes
ServerSession * M_server_session
The server session over which this message was received.
Constructor & Destructor Documentation
ServerMessageIn::ServerMessageIn (ServerSession * server_session) [inline]
Construct a ServerMessageIn that was received via server session server_session.
Definition at line 220 of file MessageIn.h.
: M_server_session(server_session) { }
ServerMessageIn::ServerMessageIn (ServerMessageIn const & msg) [inline]
Copy-constructor.
Definition at line 223 of file MessageIn.h.
References debug::channels::dc::objects.
                                                : MessageIn(msg), M_server_session(msg.M_server_session)
        { Dout(dc::objects, "Copy-constructing ServerMessageIn from " << msg); }
ServerMessageIn::~ServerMessageIn () [inline]
Destructor.
Definition at line 227 of file MessageIn.h.
{ Dout(dc::objects, "Destructing ServerMessageIn " << *this); }
Member Function Documentation
ServerSession& ServerMessageIn::server_session (void) const [inline]
Accessor for M_server_session.
Definition at line 234 of file MessageIn.h.
Referenced by Matcher::match(), ServerSession::new_message_received(), Nick::new_server_message_received(), Identity::new_server_message_received(), Channel::new_server_message_received(), operator<<(), Prefix::Prefix(), and ClientSession::queue_msg_me_as_is().
{ return *M_server_session; }
virtual bool ServerMessageIn::is_server_message (void) const [inline, protected, virtual]
Return true if this is a ServerMessageIn.
Implements MessageIn.
Definition at line 237 of file MessageIn.h.
{ return true; }
virtual ClientSession& ServerMessageIn::priv_client_session (void) const [inline, protected, virtual]
The session of the derived class.
Implements MessageIn.
Definition at line 239 of file MessageIn.h.
{ DoutFatal(dc::core, "Calling ServerMessageIn::priv_client_session()"); }
virtual ServerSession& ServerMessageIn::priv_server_session (void) const [inline, protected, virtual]
The session of the derived class.
Implements MessageIn.
Definition at line 240 of file MessageIn.h.
{ return server_session(); }
Member Data Documentation
ServerSession* ServerMessageIn::M_server_session [private]
The server session over which this message was received.
Definition at line 217 of file MessageIn.h.
The documentation for this class was generated from the following file:
MessageIn.h
Copyright © 2005-2007 Carlo Wood. All rights reserved.