ircproxy The Ultimate Cyborg
Channel Class Reference
#include <Channel.h>
Detailed Description
An IRC Channel.
Definition at line 35 of file Channel.h.
Public Types
typedef std::map< std::string,
Member > members_type
The type returned by members().
Public Member Functions
Channel (Identity &identity, std::string const &target_name, Network &private_network, int)
Construct a Channel instance for identity identity with name target_name on private network private_network.
~Channel ()
Destructor.
virtual void new_client_message_received (ClientMessageIn const &msg)
Received a channel message.
virtual void new_server_message_received (ServerMessageIn const &msg)
Received a channel message.
members_type & members (void)
Accessor to the members map.
members_type const & members (void) const
Accessor to the members map.
void set_received_names (void)
This is called when the first end of NAMES (numeric 366) is being received.
void reset_received_names (void)
This is called when a channel is rejoined after a reconnect.
void set_creation_time (time_t creation_time)
This is called when numeric 329 is being received.
bool received_names (void) const
Return true if the first end of NAMES (numeric 366) has been received.
time_t creation_time (void) const
Return the creation time of the channel, or 0 when not known.
bool has_key (void) const
Returns true if Channel::key is valid.
std::string const & key (void) const
Returns the last channel key that was seen.
Private Member Functions
Channel (Identity &identity, std::string const &target_name, Network &network)
Construct a Channel instance for identity identity with name target_name on network network.
Private Attributes
members_type M_members
The members on this channel.
bool M_received_names
True if we received the NAMES reply after joining.
time_t M_creation_time
The time as received from numeric 329, or 0 if nothing was received (yet).
std::string M_key
Last known channel key, if any.
Member Typedef Documentation
typedef std::map<std::string, Member> Channel::members_type
The type returned by members().
Definition at line 38 of file Channel.h.
Constructor & Destructor Documentation
Channel::Channel (Identity & identity, std::string const & target_name, Network & network) [inline, private]
Construct a Channel instance for identity identity with name target_name on network network.
Definition at line 50 of file Channel.h.
References ASSERT, Network::is_private(), and debug::channels::dc::objects.
                                                                              :
      Target(&network), IdentityReference(&identity),
      M_received_names(false), M_creation_time(0)
      {
        ASSERT(!network.is_private());
        Dout(dc::objects, "Constructing Channel(" << identity << ", \"" << target_name << "\", " << network << ") " << static_cast<IdentityReference&>(*this));
      }
public:
Channel::Channel (Identity & identity, std::string const & target_name, Network & private_network, int) [inline]
Construct a Channel instance for identity identity with name target_name on private network private_network.
Definition at line 59 of file Channel.h.
References ASSERT, Network::is_private(), and debug::channels::dc::objects.
                                                                                           :
      Target(&private_network), IdentityReference(&identity),
      M_received_names(true), M_creation_time(0)
      {
        ASSERT(private_network.is_private());
        Dout(dc::objects, "Constructing private Channel(" << identity << ", \"" << target_name << "\", " << private_network << ") " <<
            static_cast<IdentityReference&>(*this));
      }
#ifdef CWDEBUG
Channel::~Channel () [inline]
Destructor.
Definition at line 69 of file Channel.h.
{ Dout(dc::objects, "Destructing Channel " << *this); }
Member Function Documentation
void Channel::new_client_message_received (ClientMessageIn const & msg) [virtual]
Received a channel message.
Implements Target.
Definition at line 31 of file Channel.cc.
References ASSERT, Identity::client_session(), ClientMessageIn::client_session(), default_priority(), DoutEntering, Prefix::empty(), Prefix::get_nick(), IdentityReference::identity(), ClientSession::joined_channels(), MessageIn::key(), MessageIn::param(), MessageIn::params(), ServerSession::queue_msg(), and Identity::server_session().
{
  DoutEntering(dc::debug, "Channel::new_client_message_received(" << msg << ") for target \"" << in_name(msg.client_session()) << "\".");
  using namespace keys;
  switch (msg.key())
  {
    case JOIN:
    {
      Prefix prefix(msg);
      ASSERT(prefix.empty() || prefix.get_nick()->is_me());
      ClientSession::joined_channels_type::iterator iter = identity().client_session().joined_channels().find(msg.param(0));
      if (iter == identity().client_session().joined_channels().end())
      {
        // Pass the JOIN on as-is for unknown channel.
        MessageOut msgout(default_priority(msg.key()));
        identity().server_session().queue_msg(msgout << prefix << msg.key() << msg.params(0));
      }
      else
        Dout(dc::warning, "Ignoring a JOIN for a channel that we are already on.");
      break;
    }
    case MODE:
    case PRIVMSG:
    case NOTICE:
    case PART:
    case CPRIVMSG:
    case CNOTICE:
    case KICK:
    case NAMES:
    case TOPIC:
    {
      // FIXME.
      // For now, just pass it to the server as-is.
      // Extract the prefix of the input message.
      Prefix prefix(msg);
      // Construct a message with default priority.
      MessageOut msgout(default_priority(msg.key()));
      // Pass the message to the server.
      identity().server_session().queue_msg(msgout << prefix << msg.key() << msg.params(0));
      break;
    }
  }
}
void Channel::new_server_message_received (ServerMessageIn const & msg) [virtual]
Received a channel message.
Implements Target.
Definition at line 82 of file Channel.cc.
References Target::add_joined_nick(), edragon::caught(), Identity::client_session(), default_priority(), DoutEntering, Target::get_joined_nick(), Prefix::get_nick(), IdentityReference::identity(), MessageIn::key(), MessageIn::param(), MessageIn::params(), MessageIn::prefix_str(), ServerSession::queue_msg(), ClientSession::queue_msg(), Identity::server_session(), ServerMessageIn::server_session(), Target::serverside_get_channel(), and Target::sub_channel().
{
  DoutEntering(dc::debug, "Channel::new_server_message_received(" << msg << ") for target \"" << in_name(msg.server_session()) << "\".");
  using namespace keys;
  switch (msg.key())
  {
    case PART:
    {
      Prefix prefix(msg);
      boost::shared_ptr<Nick> nick(prefix.get_nick());
      MessageOut msgout(default_priority(msg.key()));
      identity().client_session().queue_msg(msgout << prefix << msg.key() << msg.params(0));
      if (nick->is_me())
        sub_channel(identity());
      else
        sub_joined_nick(nick);
      break;
    }
    case JOIN:
    {
      Prefix prefix(msg);
      boost::shared_ptr<Nick> nick(prefix.get_nick());
      boost::shared_ptr<Channel> channel = Target::serverside_get_channel(identity(), msg.param(0), false);
      MessageOut msgout(default_priority(msg.key()));
      identity().client_session().queue_msg(msgout << prefix << msg.key() << channel);
      Target::add_joined_nick(identity(), nick->in_name(msg.server_session()), channel);
      break;
    }
    case KICK:
    {
      Prefix prefix(msg);
      boost::shared_ptr<Channel> channel = Target::serverside_get_channel(identity(), msg.param(0), false);
      boost::shared_ptr<Nick> nick = Target::get_joined_nick(identity(), msg.param(1), channel);
      MessageOut msgout(default_priority(msg.key()));
      identity().client_session().queue_msg(msgout << prefix << msg.key() << channel << nick << msg.params(2));
      if (nick->is_me())
        sub_channel(identity());
      else
        sub_joined_nick(nick);
      break;
    }
    case PRIVMSG:
    {
      std::string prefix(msg.prefix_str());
      std::string::size_type pos = prefix.find('!');
      std::string text(msg.param(1));
      if (pos != std::string::npos)
      {
        ++pos;
        if (prefix[pos] == '~')
          ++pos;
      }
      if (pos != std::string::npos &&
          (prefix.substr(pos) == "carlo@10.11.0.4" || prefix.substr(pos) == "carlo@terp.frl" || prefix.substr(pos) == "carlo@aleric.users.undernet.org") &&
          text[0] == '!')
      {
        std::string::size_type command_end = text.find(' ');
        std::string argument;
        if (command_end != std::string::npos)
        {
          argument = text.substr(command_end + 1);
          --command_end;
        }
        std::string command = text.substr(1, command_end);
        boost::shared_ptr<Channel> channel = Target::serverside_get_channel(identity(), msg.param(0), false);
        MessageOut msgout(default_priority(PRIVMSG));
        if (command == "use_count")
        {
          if (!argument.empty())
          {
            try
            {
              boost::shared_ptr<Channel> channel2 = Target::serverside_get_channel(identity(), argument, false);
              identity().server_session().queue_msg(msgout << PRIVMSG << channel <<
                  ":channel2.use_count() =" << channel2.use_count());
            }
            catch (unknown_target& error)
            {
              Debug(edragon::caught(error));
              identity().server_session().queue_msg(msgout << PRIVMSG << channel << ":No such channel:" << argument);
            }
          }
          else
            identity().server_session().queue_msg(msgout << PRIVMSG << channel <<
                ":channel.use_count() =" << channel.use_count());
        }
        else
        {
          identity().server_session().queue_msg(msgout << PRIVMSG << channel <<
              ":No such command: \"" << JustInTimeCatenate(command) << JustInTimeCatenate("\""));
        }
      }
      /* FALL_THROUGH */
    }
    case MODE:
    case NOTICE:
    case NAMES:
    case TOPIC:
    default:
    {
      Dout(dc::warning, "Unhandled channel message " << msg << ". Passing to client as-is.");
      // Pass to client as-is.
      Prefix prefix(msg);
      MessageOut msgout(default_priority(msg.key()));
      identity().client_session().queue_msg(msgout << prefix << msg.key() << msg.params(0));
    }
  }
}
members_type& Channel::members (void) [inline]
Accessor to the members map.
Definition at line 80 of file Channel.h.
References M_members.
Referenced by Target::sub_channel().
{ return M_members; }
members_type const& Channel::members (void) const [inline]
Accessor to the members map.
Definition at line 82 of file Channel.h.
References M_members.
{ return M_members; }
void Channel::set_received_names (void) [inline]
This is called when the first end of NAMES (numeric 366) is being received.
Definition at line 87 of file Channel.h.
References M_received_names.
{ M_received_names = true; }
void Channel::reset_received_names (void) [inline]
This is called when a channel is rejoined after a reconnect.
Definition at line 90 of file Channel.h.
References M_received_names.
{ M_received_names = false; }
void Channel::set_creation_time (time_t creation_time) [inline]
This is called when numeric 329 is being received.
Definition at line 93 of file Channel.h.
References M_creation_time.
{ M_creation_time = creation_time; }
bool Channel::received_names (void) const [inline]
Return true if the first end of NAMES (numeric 366) has been received.
Definition at line 96 of file Channel.h.
References M_received_names.
{ return M_received_names; }
time_t Channel::creation_time (void) const [inline]
Return the creation time of the channel, or 0 when not known.
Definition at line 99 of file Channel.h.
References M_creation_time.
{ return M_creation_time; }
bool Channel::has_key (void) const [inline]
Returns true if Channel::key is valid.
Definition at line 102 of file Channel.h.
References M_key.
{ return !M_key.empty(); }
std::string const& Channel::key (void) const [inline]
Returns the last channel key that was seen.
Definition at line 105 of file Channel.h.
References M_key.
{ return M_key; }
Member Data Documentation
members_type Channel::M_members [private]
The members on this channel.
Definition at line 41 of file Channel.h.
Referenced by members().
bool Channel::M_received_names [private]
True if we received the NAMES reply after joining.
Definition at line 42 of file Channel.h.
Referenced by received_names(), reset_received_names(), and set_received_names().
time_t Channel::M_creation_time [private]
The time as received from numeric 329, or 0 if nothing was received (yet).
Definition at line 43 of file Channel.h.
Referenced by creation_time(), and set_creation_time().
std::string Channel::M_key [private]
Last known channel key, if any.
Definition at line 44 of file Channel.h.
Referenced by has_key(), and key().
The documentation for this class was generated from the following files:
Channel.h
Channel.cc
Copyright © 2005-2007 Carlo Wood. All rights reserved.