ircproxy The Ultimate Cyborg
NoticeTarget Class Reference
#include <NoticeTarget.h>
Detailed Description
A fake channel that is used for communication between user and ircproxy.
This class is used to send notices to the user.
Definition at line 32 of file NoticeTarget.h.
Public Member Functions
NoticeTarget (ClientSession &client_session, std::string const &target_name, Network &network)
Construct a NoticeTarget instance for client session client_session with target name target_name on network network.
~NoticeTarget ()
Destructor.
NoticeTarget (NoticeTarget const &notice_target)
Copy-constructor.
virtual void new_client_message_received (ClientMessageIn const &msg)
Called when a new (client) message is received for this target.
Protected Member Functions
virtual char const * channel_modes (void)
The channel modes for this target, as sent to the client.
Private Attributes
std::string M_notice
The notice to send.
Constructor & Destructor Documentation
NoticeTarget::NoticeTarget (ClientSession & client_session, std::string const & target_name, Network & network) [inline]
Construct a NoticeTarget instance for client session client_session with target name target_name on network network.
Definition at line 38 of file NoticeTarget.h.
References debug::channels::dc::objects.
                                                                                              :
      PrivateTarget(client_session, target_name, network)
      { Dout(dc::objects, "Constructing NoticeTarget(" <<
          client_session << ", \"" << target_name << "\", " << network << ")"); }
#ifdef CWDEBUG
NoticeTarget::~NoticeTarget () [inline]
Destructor.
Definition at line 44 of file NoticeTarget.h.
{ Dout(dc::objects, "Destructing NoticeTarget " << *this); }
NoticeTarget::NoticeTarget (NoticeTarget const & notice_target) [inline]
Copy-constructor.
Definition at line 46 of file NoticeTarget.h.
References debug::channels::dc::objects.
                                                  : PrivateTarget(notice_target)
      { Dout(dc::objects, "Copy-constructing NoticeTarget from " << notice_target); }
Member Function Documentation
void NoticeTarget::new_client_message_received (ClientMessageIn const & msg) [virtual]
Called when a new (client) message is received for this target.
This function handles incoming messages for this target.
Reimplemented from PrivateTarget.
Definition at line 29 of file NoticeTarget.cc.
References ClientMessageIn::client_session(), DoutEntering, MessageIn::key(), and PrivateTarget::new_client_message_received().
{
  DoutEntering(dc::debug, "NoticeTarget::new_client_message_received(" << msg << ") for target \"" << in_name(msg.client_session()) << "\".");
  switch(msg.key())
  {
    using namespace keys;
#ifdef CWDEBUG
    case WHO:
      DoutFatal(dc::core, "WHO should be handled by calling PrivateTarget::handle_who");
      break;
#endif
    default:
      PrivateTarget::new_client_message_received(msg);
      break;
  }
}
virtual char const* NoticeTarget::channel_modes (void) [inline, protected, virtual]
The channel modes for this target, as sent to the client.
Reimplemented from PrivateTarget.
Definition at line 55 of file NoticeTarget.h.
{ return "mnt"; }
Member Data Documentation
std::string NoticeTarget::M_notice [private]
The notice to send.
Definition at line 34 of file NoticeTarget.h.
The documentation for this class was generated from the following files:
NoticeTarget.h
NoticeTarget.cc
Copyright © 2005-2007 Carlo Wood. All rights reserved.