ircproxy The Ultimate Cyborg
MatchRequest Class Reference
#include <Matcher.h>
Detailed Description
A match request.
Definition at line 262 of file Matcher.h.
Public Member Functions
MatchRequest (bool sink=false)
Construct a MatchRequest instance.
MatchRequest & operator() (int command)
Request a match event for command command.
MatchRequest & anystring (int param, bool single_param=true)
Request a match for any string at parameter param (and on if single_param is false).
MatchRequest & nonemptystring (int param, bool single_param=true)
Request a match event for any non-empty string at parameter param (and on if single_param is false).
MatchRequest & anyserver (int param)
Request a match if parameter param contains any server name.
MatchRequest & localserver (int param)
Request a match if parameter param contains our server.
MatchRequest & anynick (int param)
Request a match if parameter param contains any nick name.
MatchRequest & mynick (int param)
Request a match if parameter param contains our nick name.
MatchRequest & anychannel (int param)
Request a match if parameter param contains any channel name.
MatchRequest & anyglobalchannel (int param)
Request a match if parameter param contains any global channel name.
MatchRequest & anylocalchannel (int param)
Request a match if parameter param contains any local channel name.
MatchRequest & wildcard (std::string const &arg, int param, bool single_param=true)
Request a match if parameter param (and on if single_param is false) matches mask arg.
MatchRequest & regexp (std::string const &arg, int param, bool single_param=true)
Request a match if parameter param (and on if single_param is false) matches regular expression arg.
MatchRequest & exactmatch (std::string const &arg, int param, bool single_param=true)
Request a match if parameter param (and on if single_param is false) matches the string arg exactly.
bool is_match (ServerMessageIn const &msg) const
Returns true if all match conditions are fullfilled.
MatchRequestList const & match_request_list (void) const
For debugging purposes. Returns the internal MatchRequestList.
Private Attributes
boost::shared_ptr
< MatchRequestList > M_match_request_list
Shared pointer to the match request list.
Constructor & Destructor Documentation
MatchRequest::MatchRequest (bool sink = false) [inline]
Construct a MatchRequest instance.
Definition at line 268 of file Matcher.h.
: M_match_request_list(NEW(MatchRequestList)), M_sink(sink) { }
Member Function Documentation
MatchRequest& MatchRequest::operator() (int command) [inline]
Request a match event for command command.
Definition at line 271 of file Matcher.h.
    {
      M_match_request_list->M_conditions.clear();
      M_match_request_list->M_command = command;
      return *this;
    }
MatchRequest& MatchRequest::anystring (int param, bool single_param = true) [inline]
Request a match for any string at parameter param (and on if single_param is false).
Definition at line 278 of file Matcher.h.
References Matcher::create().
    {
      M_match_request_list->M_conditions.insert(Matcher::create(param, anystring_mt, single_param));
      return *this;
    }
MatchRequest& MatchRequest::nonemptystring (int param, bool single_param = true) [inline]
Request a match event for any non-empty string at parameter param (and on if single_param is false).
Definition at line 284 of file Matcher.h.
References Matcher::create().
    {
      M_match_request_list->M_conditions.insert(Matcher::create(param, nonemptystring_mt, single_param));
      return *this;
    }
MatchRequest& MatchRequest::anyserver (int param) [inline]
Request a match if parameter param contains any server name.
Definition at line 290 of file Matcher.h.
References Matcher::create().
    {
      M_match_request_list->M_conditions.insert(Matcher::create(param, anyserver_mt, true));
      return *this;
    }
MatchRequest& MatchRequest::localserver (int param) [inline]
Request a match if parameter param contains our server.
Definition at line 296 of file Matcher.h.
References Matcher::create().
    {
      M_match_request_list->M_conditions.insert(Matcher::create(param, localserver_mt, true));
      return *this;
    }
MatchRequest& MatchRequest::anynick (int param) [inline]
Request a match if parameter param contains any nick name.
Definition at line 302 of file Matcher.h.
References Matcher::create().
    {
      M_match_request_list->M_conditions.insert(Matcher::create(param, anynick_mt, true));
      return *this;
    }
MatchRequest& MatchRequest::mynick (int param) [inline]
Request a match if parameter param contains our nick name.
Definition at line 308 of file Matcher.h.
References Matcher::create().
Referenced by ServerConnection::send_pong_and_mode().
    {
      M_match_request_list->M_conditions.insert(Matcher::create(param, mynick_mt, true));
      return *this;
    }
MatchRequest& MatchRequest::anychannel (int param) [inline]
Request a match if parameter param contains any channel name.
Definition at line 314 of file Matcher.h.
References Matcher::create().
    {
      M_match_request_list->M_conditions.insert(Matcher::create(param, anychannel_mt, true));
      return *this;
    }
MatchRequest& MatchRequest::anyglobalchannel (int param) [inline]
Request a match if parameter param contains any global channel name.
Definition at line 320 of file Matcher.h.
References Matcher::create().
    {
      M_match_request_list->M_conditions.insert(Matcher::create(param, anyglobalchannel_mt, true));
      return *this;
    }
MatchRequest& MatchRequest::anylocalchannel (int param) [inline]
Request a match if parameter param contains any local channel name.
Definition at line 326 of file Matcher.h.
References Matcher::create().
    {
      M_match_request_list->M_conditions.insert(Matcher::create(param, anylocalchannel_mt, true));
      return *this;
    }
MatchRequest& MatchRequest::wildcard (std::string const & arg, int param, bool single_param = true) [inline]
Request a match if parameter param (and on if single_param is false) matches mask arg.
Definition at line 332 of file Matcher.h.
References Matcher::create().
    {
      M_match_request_list->M_conditions.insert(Matcher::create(param, wildcard_mt, arg, single_param));
      return *this;
    }
MatchRequest& MatchRequest::regexp (std::string const & arg, int param, bool single_param = true) [inline]
Request a match if parameter param (and on if single_param is false) matches regular expression arg.
Definition at line 338 of file Matcher.h.
References Matcher::create().
Referenced by ServerSession::new_message_received().
    {
      M_match_request_list->M_conditions.insert(Matcher::create(param, regexp_mt, arg, single_param));
      return *this;
    }
MatchRequest& MatchRequest::exactmatch (std::string const & arg, int param, bool single_param = true) [inline]
Request a match if parameter param (and on if single_param is false) matches the string arg exactly.
Definition at line 344 of file Matcher.h.
References Matcher::create().
    {
      M_match_request_list->M_conditions.insert(Matcher::create(param, exactmatch_mt, arg, single_param));
      return *this;
    }
bool MatchRequest::is_match (ServerMessageIn const & msg) const [inline]
Returns true if all match conditions are fullfilled.
Definition at line 350 of file Matcher.h.
Referenced by ServerSession::new_message_received().
{ return M_match_request_list->is_match(msg); }
MatchRequestList const& MatchRequest::match_request_list (void) const [inline]
For debugging purposes. Returns the internal MatchRequestList.
Definition at line 353 of file Matcher.h.
Referenced by operator<<().
{ return *M_match_request_list; }
Member Data Documentation
boost::shared_ptr<MatchRequestList> MatchRequest::M_match_request_list [private]
Shared pointer to the match request list.
Definition at line 264 of file Matcher.h.
The documentation for this class was generated from the following file:
Matcher.h
Copyright © 2005-2007 Carlo Wood. All rights reserved.