ircproxy The Ultimate Cyborg
Matcher_noarg Class Reference
#include <Matcher.h>
Detailed Description
A Matcher base class for matchers that do not take an extra argument.
Definition at line 110 of file Matcher.h.
Public Member Functions
Matcher_noarg (int param, match0_type mt, bool single_param)
Construct a Matcher_noarg object of type mt that will match against parameter param (and on, if single_param is false).
virtual void print_type_on (std::ostream &os) const
For debugging purposes. Write the class name to os.
virtual void print_on (std::ostream &os) const
For debugging purposes. Write the match type to os.
virtual int sort_value (void)
Implementation of pure virtual function Matcher::sort_value().
Protected Member Functions
virtual bool match_impl (ServerSession const &server_session, char const *start, size_t len)
Match implementation interface filled in by derived classes.
Protected Attributes
match0_type M_mt
The match type.
Constructor & Destructor Documentation
Matcher_noarg::Matcher_noarg (int param, match0_type mt, bool single_param) [inline]
Construct a Matcher_noarg object of type mt that will match against parameter param (and on, if single_param is false).
Definition at line 116 of file Matcher.h.
: Matcher(param, single_param), M_mt(mt) { }
Member Function Documentation
virtual void Matcher_noarg::print_type_on (std::ostream & os) const [inline, virtual]
For debugging purposes. Write the class name to os.
Implements Matcher.
Definition at line 120 of file Matcher.h.
{ os << "Matcher_noarg"; }
virtual void Matcher_noarg::print_on (std::ostream & os) const [inline, virtual]
For debugging purposes. Write the match type to os.
Reimplemented from Matcher.
Definition at line 122 of file Matcher.h.
{ os << "mt:" << M_mt; }
bool Matcher_noarg::match_impl (ServerSession const & server_session, char const * start, size_t len) [protected, virtual]
Match implementation interface filled in by derived classes.
Implements Matcher.
Definition at line 27 of file Matcher.cc.
References NickPair::in_nick(), is_channel(), M_mt, debug::channels::dc::matcher, ServerSession::nicks(), ServerConnection::server(), and ServerSession::server_connection().
{
  switch(M_mt)
  {
    case anystring_mt:
      return true;
    case nonemptystring_mt:
      return len > 0;
    case anyserver_mt:
    {
      for (char const* p = start; p < start + len; ++p)
        if (*p == '.')
          return true;
      return false;
    }
    case localserver_mt:
    {
      Dout(dc::matcher|continued_cf, "localserver_mt: get_irc_name() = \"" <<
          server_session.server_connection().server()->get_irc_name() << "\"; input = \"" << buf2str(start, len) << "\", ");
      bool result = server_session.server_connection().server()->get_irc_name().compare(0, std::string::npos, start, len) == 0;
      Dout(dc::finish, "returning " << (result ? "true" : "false"));
      return result;
    }
    case anynick_mt:
      return len > 0 && !is_channel(start);
    case mynick_mt:
    {
      Dout(dc::matcher|continued_cf, "mynick_mt: server_in_nick() = \"" <<
          server_session.nicks().in_nick() << "\"; input = \"" << buf2str(start, len) << "\", ");
      bool result = server_session.nicks().in_nick().compare(0, std::string::npos, start, len) == 0;
      Dout(dc::finish, "returning " << (result ? "true" : "false"));
      return result;
    }
    case anychannel_mt:
      return len > 0 && is_channel(start);
    case anyglobalchannel_mt:
      return len > 0 && *start == '#';
    case anylocalchannel_mt:
      return len > 0 && *start == '&';
  }
  // Never reached.
  return false;
}
virtual int Matcher_noarg::sort_value (void) [inline, virtual]
Implementation of pure virtual function Matcher::sort_value().
Implements Matcher.
Definition at line 130 of file Matcher.h.
References M_mt.
{ return M_mt; }
Member Data Documentation
match0_type Matcher_noarg::M_mt [protected]
The match type.
Definition at line 112 of file Matcher.h.
Referenced by match_impl(), and sort_value().
The documentation for this class was generated from the following files:
Matcher.h
Matcher.cc
Copyright © 2005-2007 Carlo Wood. All rights reserved.