ircproxy The Ultimate Cyborg
JustInTimeMsgPart Class Reference
#include <JustInTime.h>
Detailed Description
A just-in-time MsgPart.
Definition at line 141 of file JustInTime.h.
Public Member Functions
JustInTimeMsgPart (MsgPart const &token)
Construct a JustInTimeMsgPart with value token.
virtual std::string value (ClientSession const &) const
Return the underlying value.
virtual void write_to (std::ostream &os, ClientSession const &) const
Write the underlying token, including seperators, to an ostream.
Private Attributes
MsgPart M_token
The MsgPart.
Constructor & Destructor Documentation
JustInTimeMsgPart::JustInTimeMsgPart (MsgPart const & token) [inline]
Construct a JustInTimeMsgPart with value token.
Definition at line 146 of file JustInTime.h.
: M_token(token) { }
Member Function Documentation
virtual std::string JustInTimeMsgPart::value (ClientSession const &) const [inline, virtual]
Return the underlying value.
Implements JustInTimeToken.
Definition at line 148 of file JustInTime.h.
References MessageIn::Part::len(), M_token, and MessageIn::Part::start().
{ return std::string(M_token.start(), M_token.len()); }
virtual void JustInTimeMsgPart::write_to (std::ostream & os, ClientSession const &) const [inline, virtual]
Write the underlying token, including seperators, to an ostream.
Implements JustInTimeToken.
Definition at line 151 of file JustInTime.h.
References MessageIn::Part::len(), M_token, and MessageIn::Part::start().
{ os << ' '; os.write(M_token.start(), M_token.len()); }
Member Data Documentation
MsgPart JustInTimeMsgPart::M_token [private]
The MsgPart.
Definition at line 143 of file JustInTime.h.
Referenced by value(), and write_to().
The documentation for this class was generated from the following file:
JustInTime.h
Copyright © 2005-2007 Carlo Wood. All rights reserved.