ircproxy The Ultimate Cyborg
ServerSession Class Reference
#include <ServerSession.h>
Detailed Description
A server session, from connect till disconnect.
This class represents a server session: from that we successfully connect to a server until the connection is closed or lost again.
Definition at line 47 of file ServerSession.h.
Public Types
typedef target_hold_map_type joined_channels_type
The type of M_joined_channels.
typedef std::map< std::string,
boost::shared_ptr< Channel > > join_pipeline_type
The type of M_join_pipeline.
Public Member Functions
ServerSession (Identity &identity, ServerConnection &server_connection)
Construct a ServerSession instance for identity identity and server connection server_connection.
~ServerSession ()
Destructor.
void start_authentication (void)
Called from ServerConnection::do_connect. Takes care of sending PASS/NICK/USER/PONG/MODE.
void set_auth_ping_argument (std::string const &auth_ping_argument)
Called from ServerConnection::decode_ping with the argument of the first PING.
std::string const & auth_ping_argument (void) const
Return argument of the first PING.
void construct_network_object (std::string const &network_name, std::string const &domain)
Create a new network object with name network_name and domain domain (if any).
void detected_network (networks_type::iterator network_iter)
Initialize network. This function is called as soon as the network we are connected to is known.
void authentication_successful (void)
Called when the authentication was successful (when receiving the 001 numeric).
void fatal_error (char const *error_msg)
A fatal error occured. Calling this function will terminate the ServerSession.
void found_network_name (void)
Called when the name of the Network is known (after numeric 005).
MatcherEventServer & message_event_server (void)
Return a reference to the event server for incoming messages.
MatcherEventServer const & message_event_server (void) const
Return a const reference to the event server for incoming messages.
NickPair & nicks (void)
Server session nick pair.
NickPair const & nicks (void) const
Server session nick pair.
joined_channels_type & joined_channels (void)
Return reference to map with joined channels.
joined_channels_type const & joined_channels (void) const
Return const reference to map with joined channels.
UserMode & user_mode (void)
Return my user mode.
UserMode const & user_mode (void) const
Return my user mode.
void queue_msg (MessageOut const &msg)
Queue message msg.
void queue_msg_as_is (ClientMessageIn const &msg)
Queue message msg with default priority without changing it.
WhoRequest current_who_request (void)
Return the first element of M_who_queue.
void pop_who_request (void)
Pop the first element of M_who_queue.
void send_nick_write_event (PseudoMessageEventType const &, std::string nick)
A write event of a pseudo NICK message happened. Actually write the NICK message.
void send_who_write_event (PseudoMessageEventType const &event_type, WhoRequest who_request)
A write event of a pseudo WHO message happened. Actually write the WHO message.
void force_quit (timer_event_type_ct const &)
Called 1 second after sending a QUIT and the connection still wasn't terminated.
ISupport const & i_support (void) const
Accessor for M_i_support.
ISupport & i_support (void)
Accessor for M_i_support.
boost::shared_ptr< Channel > join_pipeline (std::string const &channel_name)
Return a pointer to the channel in the pipeline, if any. Channel is removed from pipeline.
void set_disconnect_reason (std::string const &disconnect_reason)
Set the disconnect reason to disconnect_reason.
ServerConnection & server_connection (void) const
Accessor for underlying server connection object.
boost::shared_ptr< Nick > get_nick (std::string const &nick_name, bool create=false)
Get or create a Nick for nick_name.
Public Attributes
Bool M_detected_network
True if the network is fully detected.
Protected Member Functions
virtual void new_message_received (ServerMessageIn const &)
Incoming event from ServerSessionInput.
virtual void network_connection_terminated (void)
A read(2) on the socket returned 0.
Private Member Functions
void send_rejoins (void)
Send a JOIN to the server for every channel we are on.
Private Attributes
ServerConnection & M_server_connection
The owning object.
MatcherEventServer M_message_event_server
Event server for incoming messages.
NickPair M_server_session_nicks
Server side nick pair.
joined_channels_type M_joined_channels
Serverside lookup map for channels joined by this identity.
UserMode M_user_mode
My user mode.
boost::shared_ptr< AuthState > M_auth_state
Pointer object with temporary authentication state information.
Queue M_output_queue
Queue for output messages.
std::queue< WhoRequest > M_who_queue
Queue storing WHO request messages.
ISupport M_i_support
Object that stores the numeric 005 information.
std::string M_network_name
Temporary storage of the network name as decoded from numeric 001, until numeric 005 is received.
std::string M_umodes
The user modes as received in numeric 004.
join_pipeline_type M_join_pipeline
Channels for which we sent a JOIN as part of a reconnect.
std::string M_disconnect_reason
An error message that should be sent to the client if the connection is lost, if any.
Static Private Attributes
static int S_server_sessions = 0
Total number of server session objects.
Member Typedef Documentation
typedef target_hold_map_type ServerSession::joined_channels_type
The type of M_joined_channels.
Definition at line 49 of file ServerSession.h.
typedef std::map<std::string, boost::shared_ptr<Channel> > ServerSession::join_pipeline_type
The type of M_join_pipeline.
Definition at line 50 of file ServerSession.h.
Constructor & Destructor Documentation
ServerSession::ServerSession (Identity & identity, ServerConnection & server_connection) [inline]
Construct a ServerSession instance for identity identity and server connection server_connection.
Definition at line 73 of file ServerSession.h.
References debug::channels::dc::objects, and S_server_sessions.
                                                                           :
        IdentityReference(&identity), M_server_connection(server_connection),
        M_server_session_nicks(*this), M_output_queue(server_connection, 0.5, 5, 5),
        M_i_support(server_connection)
#ifdef CWDEBUG
      , M_detected_network("M_detected_network")
#endif
        {
          Dout(dc::objects, "Constructing ServerSession(" << identity << ", " << server_connection << ")");
          ++S_server_sessions;
        }
    //! Destructor.
ServerSession::~ServerSession ()
Destructor.
Definition at line 334 of file ServerSession.cc.
References M_server_connection, debug::channels::dc::objects, ServerConnection::reconnect(), S_server_sessions, ServerConnection::secondary_connection(), and ServerConnection::session_lost().
{
#ifdef CWDEBUG
  debug::SecondaryConnection dummy(M_server_connection.secondary_connection());
#endif
  Dout(dc::objects, "Destructing ServerSession" << *this);
  M_server_connection.session_lost();
  cancel_all_requests();
  // Notify the application when the last server session is terminated.
  if (--S_server_sessions == 0 && !M_server_connection.reconnect())
    Application::instance().last_server_session_destroyed();
}
Member Function Documentation
void ServerSession::start_authentication (void)
Called from ServerConnection::do_connect. Takes care of sending PASS/NICK/USER/PONG/MODE.
Definition at line 322 of file ServerSession.cc.
References M_auth_state, and M_server_connection.
Referenced by ServerConnection::do_connect().
{
  M_auth_state.reset(NEW(AuthState(M_server_connection)));
}
void ServerSession::set_auth_ping_argument (std::string const & auth_ping_argument) [inline]
Called from ServerConnection::decode_ping with the argument of the first PING.
Definition at line 91 of file ServerSession.h.
References M_auth_state.
Referenced by ServerConnection::decode_ping().
{ if (M_auth_state.get()) M_auth_state->set_auth_ping_argument(auth_ping_argument); }
std::string const& ServerSession::auth_ping_argument (void) const [inline]
Return argument of the first PING.
Definition at line 94 of file ServerSession.h.
References ASSERT, and M_auth_state.
Referenced by ServerConnection::send_pong_and_mode().
{ ASSERT(M_auth_state.get()); return M_auth_state->auth_ping_argument(); }
void ServerSession::construct_network_object (std::string const & network_name, std::string const & domain)
Create a new network object with name network_name and domain domain (if any).
Definition at line 442 of file ServerSession.cc.
References detected_network(), IdentityReference::identity(), network_domain_question, and Identity::send_notice().
Referenced by found_network_name(), and Identity::received_network_domain_answer().
{
  networks_type& networks = Application::instance().networks();
  networks_type::iterator iter;
  std::ostringstream buf;
  buf << "Added NEW network: \"" << network_name << "\"";
  if (domain.empty())
  {
    iter = networks.insert(networks.end(), Network(network_name));
    buf << '.';
  }
  else
  {
    iter = networks.insert(networks.end(), Network(network_name, domain));
    buf << ", with common domain \"" << domain << "\".";
  }
  identity().send_notice(buf.str(), network_domain_question);
  detected_network(iter);
}
void ServerSession::detected_network (networks_type::iterator network_iter)
Initialize network. This function is called as soon as the network we are connected to is known.
Definition at line 462 of file ServerSession.cc.
References ASSERT, DoutEntering, ISupport::get(), IdentityReference::identity(), IRCStringCompare(), M_detected_network, M_i_support, M_server_connection, M_umodes, debug::channels::dc::maps, Identity::mynick(), ServerConnection::secondary_connection(), and ServerConnection::server().
Referenced by construct_network_object(), and found_network_name().
{
  DoutEntering(dc::debug, "Identity::detected_network(" << *network_iter << ")");
  boost::shared_ptr<Server> current_server(M_server_connection.server());
  Dout(dc::notice, "Current server is " << *current_server.get());
  // Update the current server as we connected successfully.
  ASSERT(is_open());
  ASSERT(remote_port() == current_server->port());
  current_server->add_port(current_server->port());
  Dout(dc::notice, "Added remote port " << current_server->port() << " to server " << *current_server.get());
  Dout(dc::debug, "*network_iter is now: " << *network_iter);
  // Set the network pointer of the current Server object.
  current_server->set_network(&(*network_iter));
  if (!M_server_connection.secondary_connection())
  {
    // Set the network pointer in my own Nick object.
    identity().mynick()->set_network(&(*network_iter));
    // Make sure my Nick is inserted in the networks targets map.
    Dout(dc::maps, "Inserting my nick \"" << identity().mynick()->in_name(*this) << "\" in Network map.");
    network_iter->targets().insert(target_lookup_map_type::value_type(identity().mynick()->in_name(*this), identity().mynick()));
    ASSERT(network_iter->targets().find(identity().mynick()->in_name(*this)) != network_iter->targets().end());
  }
  // Find the current server in the list of known servers for this network.
  std::string server_name = current_server->get_irc_name();
  Network::servers_type::iterator server = network_iter->servers().begin();
  while (server != network_iter->servers().end())
  {
    if (IRCStringCompare(server_name, (*server)->get_irc_name()) == 0)
      break;
    ++server;
  }
  if (server == network_iter->servers().end())
    network_iter->servers().push_back(current_server);
  M_detected_network = true;
  // Initialize WHO flag table.
  std::string prefix;
  if (!M_i_support.get("PREFIX", prefix))
  {
    prefix = "(ov)@+";
    Dout(dc::warning, "No PREFIX ISUPPORT. Using " << prefix);
  }
  network_iter->init_who_flag_table(M_umodes, prefix);
}
void ServerSession::authentication_successful (void)
Called when the authentication was successful (when receiving the 001 numeric).
Definition at line 327 of file ServerSession.cc.
References M_auth_state.
Referenced by new_message_received().
{
  M_auth_state.reset();
}
void ServerSession::fatal_error (char const * error_msg)
A fatal error occured. Calling this function will terminate the ServerSession.
Definition at line 313 of file ServerSession.cc.
{
  if (!must_be_removed())               // Only write one error at a time.
    *this << "QUIT :Fatal error: " << error_msg << "\r\n";
  // The next method sets 'must_be_removed()' to true,
  // flushes the error and deletes this object (non-blocking).
  del();
}
void ServerSession::found_network_name (void)
Called when the name of the Network is known (after numeric 005).
Definition at line 389 of file ServerSession.cc.
References ASSERT, Identity::client_session(), construct_network_object(), detected_network(), ServerConnection::disconnect(), IdentityReference::identity(), IRCStringCompare(), M_network_name, M_server_connection, network_domain_question, Identity::network_name(), Identity::received_network_domain_answer(), Identity::send_notice(), ServerConnection::server(), server_port_question, Identity::set_network_name(), and ClientSession::user_answer_event_server.
Referenced by ISupport::end().
{
  Dout(dc::notice, "network = \"" << M_network_name << "\".");
  if (identity().network_name() != unknown_network_name && identity().network_name() != M_network_name)
  {
    Dout(dc::warning, "Identity " << identity().key() << " was connected to network " << identity().network_name() <<
        " but now tries to connect to network " << M_network_name << '!');
    std::string notice("Detected a possible network switch (from ");
    notice += identity().network_name();
    notice += " to ";
    notice += M_network_name;
    notice += "). Bailing out!";
    identity().send_notice(notice, server_port_question);
    M_server_connection.disconnect();
    return;
  }
  identity().send_notice("Successfully connected.", server_port_question);
  identity().set_network_name(M_network_name);
  // Try to find if we already know this network.
  networks_type& networks = Application::instance().networks();
  networks_type::iterator iter = networks.begin();
  while (iter != networks.end())
  {
    if (IRCStringCompare(iter->name(), M_network_name) == 0)
      break;
    ++iter;
  }
  if (iter == networks.end())
  {
    std::string server_name = M_server_connection.server()->get_irc_name();
    std::string::size_type pos = server_name.rfind('.');
    ASSERT(pos > 0);
    pos = server_name.rfind('.', pos - 1);
    if (pos != std::string::npos)
    {
      std::string domain = server_name.substr(pos + 1);
      std::transform(domain.begin(), domain.end(), domain.begin(), ToLower);
      std::ostringstream the_question;
      the_question << "Does the " << M_network_name << " IRC network use \"" <<
          domain << "\" as common domain for all servers (type: Yes|No)?";
      identity().client_session().user_answer_event_server
          (UserAnswerRequestData(identity().client_session(), network_domain_question, the_question.str()),
          identity(), &Identity::received_network_domain_answer,
          std::pair<std::string, std::string>(M_network_name, domain));
    }
    else
      construct_network_object(M_network_name, "");     // No common domain.
  }
  else
    detected_network(iter);
}
MatcherEventServer& ServerSession::message_event_server (void) [inline]
Return a reference to the event server for incoming messages.
Definition at line 112 of file ServerSession.h.
References M_message_event_server.
Referenced by AuthState::auth_notice_looking_up_hostname(), AuthState::auth_notice_looking_up_ident(), AuthState::AuthState(), and ServerConnection::send_pong_and_mode().
{ return M_message_event_server; }
MatcherEventServer const& ServerSession::message_event_server (void) const [inline]
Return a const reference to the event server for incoming messages.
Definition at line 114 of file ServerSession.h.
References M_message_event_server.
{ return M_message_event_server; }
NickPair& ServerSession::nicks (void) [inline]
Server session nick pair.
Definition at line 117 of file ServerSession.h.
References M_server_session_nicks.
Referenced by Matcher_noarg::match_impl(), new_message_received(), Identity::new_server_message_received(), Authentication::send_authentication(), send_nick_write_event(), and ServerConnection::send_pong_and_mode().
{ return M_server_session_nicks; }
NickPair const& ServerSession::nicks (void) const [inline]
Server session nick pair.
Definition at line 120 of file ServerSession.h.
References M_server_session_nicks.
{ return M_server_session_nicks; }
joined_channels_type& ServerSession::joined_channels (void) [inline]
Return reference to map with joined channels.
Definition at line 123 of file ServerSession.h.
References M_joined_channels.
Referenced by Target::add_channel(), send_rejoins(), Target::serverside_add_channel(), Target::serverside_get_channel(), Target::sub_channel(), and Identity::~Identity().
{ return M_joined_channels; }
joined_channels_type const& ServerSession::joined_channels (void) const [inline]
Return const reference to map with joined channels.
Definition at line 126 of file ServerSession.h.
References M_joined_channels.
{ return M_joined_channels; }
UserMode& ServerSession::user_mode (void) [inline]
Return my user mode.
Definition at line 129 of file ServerSession.h.
References M_user_mode.
Referenced by new_message_received(), and ServerConnection::send_pong_and_mode().
{ return M_user_mode; }
UserMode const& ServerSession::user_mode (void) const [inline]
Return my user mode.
Definition at line 132 of file ServerSession.h.
References M_user_mode.
{ return M_user_mode; }
void ServerSession::queue_msg (MessageOut const & msg) [inline]
Queue message msg.
Definition at line 135 of file ServerSession.h.
References DoutEntering, M_output_queue, and Queue::queue_msg().
Referenced by ServerConnection::decode_ping(), Identity::new_client_message_received(), Channel::new_client_message_received(), ClientSession::new_client_nick_received(), Channel::new_server_message_received(), queue_msg_as_is(), and send_rejoins().
{ DoutEntering(dc::debug, "ServerSession::queue_msg(" << msg << ")"); M_output_queue.queue_msg(msg); }
void ServerSession::queue_msg_as_is (ClientMessageIn const & msg)
Queue message msg with default priority without changing it.
Definition at line 382 of file ServerSession.cc.
References default_priority(), MessageIn::key(), MessageIn::params(), and queue_msg().
Referenced by Identity::new_client_message_received().
{
  Prefix prefix(msg);
  MessageOut msgout(default_priority(msg.key()));
  queue_msg(msgout << prefix << msg.key() << msg.params(0));
}
WhoRequest ServerSession::current_who_request (void) [inline]
Return the first element of M_who_queue.
Definition at line 141 of file ServerSession.h.
References ASSERT, and M_who_queue.
        {
          ASSERT(!M_who_queue.empty());
          Dout(dc::debug, "ServerSession::current_who_request returns " << M_who_queue.front() << ". Number of items: " << M_who_queue.size());
          return M_who_queue.front();
        }
void ServerSession::pop_who_request (void) [inline]
Pop the first element of M_who_queue.
Definition at line 149 of file ServerSession.h.
References ASSERT, and M_who_queue.
Referenced by Identity::new_server_message_received().
        {
          ASSERT(!M_who_queue.empty());
          M_who_queue.pop();
          Dout(dc::debug, "Calling ServerSession::pop_who_request. Remaining number of items: " << M_who_queue.size());
        }
void ServerSession::send_nick_write_event (PseudoMessageEventType const & , std::string nick) [inline]
A write event of a pseudo NICK message happened. Actually write the NICK message.
Definition at line 157 of file ServerSession.h.
References nicks(), and NickPair::send_nick().
Referenced by ClientSession::new_client_nick_received().
{ nicks().send_nick(nick); }
void ServerSession::send_who_write_event (PseudoMessageEventType const & event_type, WhoRequest who_request)
A write event of a pseudo WHO message happened. Actually write the WHO message.
Definition at line 347 of file ServerSession.cc.
References ASSERT, DoutEntering, M_who_queue, WhoRequest::mask(), WhoRequest::mask_contains_space(), WhoRequest::mask_is_target(), WhoRequest::mask_target(), WhoRequest::options(), and WhoOptions::str().
Referenced by Identity::new_client_message_received().
{
  ASSERT(!debug::secondary_connection);
  DoutEntering(dc::debug, "ServerSession::send_who_write_event((PseudoMessageEventType&){" << (void*)&event_type << "), " << who_request << ")");
  // Actually sent the WHO message to the server.
  std::string options(who_request.options().str());
  bool has_options = !options.empty();
  if (who_request.mask_contains_space())
  {
    if (has_options)
      *this << "WHO dummy";
    else
      *this << "WHO :" << who_request.mask();
  }
  else if (who_request.mask_is_target())
    *this << "WHO " << who_request.mask_target()->out_name(*this);
  else
    *this << "WHO " << who_request.mask();
  if (has_options)
  {
    *this << ' ' << options;
    if (who_request.mask_contains_space())
    {
      *this << " :";
      if (who_request.mask_is_target())
        *this << who_request.mask_target()->out_name(*this);
      else
        *this << who_request.mask();
    }
  }
  *this << "\r\n";
  Dout(dc::debug, "Pushing " << who_request << " onto M_who_queue.");
  M_who_queue.push(who_request);
}
void ServerSession::force_quit (timer_event_type_ct const &)
Called 1 second after sending a QUIT and the connection still wasn't terminated.
Definition at line 515 of file ServerSession.cc.
References ServerConnection::disconnect(), DoutEntering, and M_server_connection.
{
  DoutEntering(dc::debug, "ServerSession::force_quit(" << expired_at.get_expire_time() << ")");
  M_server_connection.disconnect();
}
ISupport const& ServerSession::i_support (void) const [inline]
Accessor for M_i_support.
Definition at line 166 of file ServerSession.h.
References M_i_support.
{ return M_i_support; }
ISupport& ServerSession::i_support (void) [inline]
Accessor for M_i_support.
Definition at line 169 of file ServerSession.h.
References M_i_support.
{ return M_i_support; }
boost::shared_ptr< Channel > ServerSession::join_pipeline (std::string const & channel_name)
Return a pointer to the channel in the pipeline, if any. Channel is removed from pipeline.
Definition at line 227 of file ServerSession.cc.
References M_join_pipeline.
Referenced by new_message_received().
{
  boost::shared_ptr<Channel> result;
  join_pipeline_type::iterator iter = M_join_pipeline.find(channel_name);
  if (iter != M_join_pipeline.end())
  {
    result = iter->second;
    M_join_pipeline.erase(iter);
  }
  return result;
}
void ServerSession::set_disconnect_reason (std::string const & disconnect_reason) [inline]
Set the disconnect reason to disconnect_reason.
Definition at line 175 of file ServerSession.h.
References ASSERT, and M_disconnect_reason.
Referenced by ServerConnection::error_message_received().
{ ASSERT(M_disconnect_reason.empty()); M_disconnect_reason = disconnect_reason; }
ServerConnection& ServerSession::server_connection (void) const [inline]
Accessor for underlying server connection object.
Definition at line 178 of file ServerSession.h.
References M_server_connection.
Referenced by get_nick(), Matcher_noarg::match_impl(), new_message_received(), and Target::serverside_add_channel().
{ return M_server_connection; }
boost::shared_ptr< Nick > ServerSession::get_nick (std::string const & nick_name, bool create = false)
Get or create a Nick for nick_name.
Definition at line 537 of file ServerSession.cc.
References ASSERT, IdentityReference::identity(), is_nick(), Network::is_private(), debug::channels::dc::maps, server_connection(), Network::targets(), and THROW_EXCEPTION.
Referenced by Identity::new_server_message_received().
{
  ASSERT(is_nick(nick_name));
  boost::shared_ptr<Nick> new_nick;
  // Get the network.
  Network& network(identity().server_connection().network());
  ASSERT(!network.is_private());
  // Get the nick, if any, or else create one.
  target_lookup_map_type::iterator network_iter = network.targets().find(nick_name);
  if (network_iter != network.targets().end())
    new_nick = boost::static_pointer_cast<Nick>(network_iter->second.lock());
  else if (create)
  {
    Nick* nick = new Nick(*this, nick_name);
    AllocTag(nick, nick_name);
    new_nick.reset(nick);
    Dout(dc::maps, "Inserting " << nick_name << " in Network map.");
#if defined(CWDEBUG) || defined(DEBUG)
    std::pair<target_lookup_map_type::iterator, bool> res =
#endif
        network.targets().insert(target_lookup_map_type::value_type(nick_name, new_nick));
    ASSERT(res.second);
  }
  else
    THROW_EXCEPTION(unknown_target(), "The identity " << identity().key() << " has no server side nick \"" << nick_name << "\"");
  return new_nick;
}
void ServerSession::new_message_received (ServerMessageIn const & msg) [protected, virtual]
Incoming event from ServerSessionInput.
Definition at line 32 of file ServerSession.cc.
References ISupport::add(), ASSERT, authentication_successful(), ISupport::begin(), ServerConnection::change_state(), ClientSession::client_out_nick(), Identity::client_session(), ServerConnection::decode_ping(), default_priority(), ServerConnection::disconnect(), DoutEntering, ISupport::end(), ServerConnection::error_message_received(), IdentityReference::identity(), NickPair::in_nick(), MatchRequest::is_match(), join_pipeline(), MessageIn::key(), login_sent, M_i_support, M_join_pipeline, M_message_event_server, M_network_name, M_server_connection, M_server_session_nicks, M_umodes, Identity::mynick(), Identity::new_server_message_received(), UserMode::new_server_message_received(), NickPair::nick_received(), nicks(), MessageIn::param(), MessageIn::params(), MessageIn::params_size(), MessageIn::prefix_str(), ClientSession::queue_msg(), ClientSession::queue_msg_me_as_is(), real_nick_accepted, real_nick_sent, MatchRequest::regexp(), ServerConnection::secondary_connection(), Identity::secondary_server_connection(), NickPair::send_nick(), Identity::send_notice(), send_rejoins(), ServerConnection::server(), server_connection(), server_port_question, ServerMessageIn::server_session(), Target::serverside_add_channel(), Identity::set_hostname(), ServerConnection::state(), Identity::swap_primary_and_secondary_connection(), and user_mode().
{
#ifdef CWDEBUG
  // Suppress all debug output related to PING messages.
  bool suppress_debug_output =
      (msg.key() == keys::PING && Application::instance().suppress_ping()) ||
      ((msg.key() == 352 || msg.key() == 354 || msg.key() == 315) && Application::instance().suppress_who());
  Debug(if (suppress_debug_output) libcw_do.off());
#endif
  DoutEntering(dc::debug, "ServerSession::new_message_received(" << msg << ")");
  // Trigger message match events.
  if (M_message_event_server.trigger(MatcherEventType(msg)))
  {
    Debug(if (suppress_debug_output) libcw_do.on());
    return;
  }
  // Decode messages that can happen prior to network detection here.
  // Other messages are decoded in default:.
  bool pre_network_message = true;              // non-Default.
  bool fully_processed = true;                  // No reason to call Identity::new_server_message_received.
  switch(msg.key())
  {
    case 1:
    {
      // My own nick name should equal parameter 0.
      ASSERT(msg.param(0) == nicks().in_nick());
      ASSERT(M_server_connection.secondary_connection() || msg.param(0) == identity().mynick()->in_name(*this));
      authentication_successful();
      M_server_connection.server()->set_irc_name(msg.prefix_str());
      MatchRequest match_request;
      match_request(1).regexp("Welcome to [Tt]he [^ ]* IRC [Nn]etwork", 1);
      if (!match_request.is_match(msg))
      {
        std::ostringstream buf;
        buf << "Unrecognized 001 format [" << msg.param(1) << "]. Bailing out.";
        identity().send_notice(buf.str(), server_port_question);
        M_server_connection.disconnect();
      }
      else
        M_network_name.assign(msg.param(1), 15, msg.param(1).find(' ', 16) - 15);
      break;
    }
    case 4:
    {
      // We can use this numeric to detect the start of a possible sequence of 005 messages.
      // See also the call to i_support().end().
      M_i_support.begin();
      // Store the supported user modes.
      M_umodes = msg.param(3);
      // Store the server version.
      M_server_connection.server()->version().set_version(msg.param(2), timerRequest.get_now().tv_sec);
      break;
    }
    case 5:
    {
      // Decode the params. Param 0 is my nick, param n-1 is "is supported by this server".
      for (unsigned int n = 1; n < msg.params_size() - 1; ++n)
        M_i_support.add(msg.param(n));
      break;
    }
    case 251:
    {
      // This means that all 005 numerics have been received.
      M_i_support.end();
      break;
    }
    case 2:
    case 3:
    case 252:
    case 253:
    case 254:
    case 255:
    case 372:
    case 375:
    case 376:
      break;
    default:
    {
      pre_network_message = false;
      // Decode messages that do not only happen once per (re)connect.
      switch (msg.key())
      {
        using namespace keys;
        case ERROR:
          M_server_connection.error_message_received(msg);
          break;
        case PING:                      // No target
          M_server_connection.decode_ping(msg);
          break;
        case NICK:
        {
          if (!M_server_session_nicks.nick_received(msg.param(0)))
          {
            fully_processed = false;
            break;
          }
          // It was my own nick change.
          identity().mynick()->serverside_nick_changed_to(msg.server_session(), M_server_session_nicks.in_nick());
          if (!M_server_connection.secondary_connection())
          {
            // FIXME: We should only pass nick changes to the client that the client itself requested.
            ASSERT(identity().client_session().client_in_nick() == msg.param(0));
            Prefix prefix(msg);
            // For now, pass everything on to the client.
            MessageOut msgout(default_priority(keys::NICK));
            // FIXME: client_out_nick() should be updated first (is currently equal to client_in_nick, so no change needed now).
            identity().client_session().queue_msg(msgout << prefix << keys::NICK << identity().client_session().client_out_nick());
            identity().mynick()->clientside_nick_changed_to(identity().client_session(), identity().client_session().client_out_nick());
          }
          if (M_server_connection.state() == real_nick_sent)
          {
            M_server_connection.change_state(real_nick_sent, real_nick_accepted);
            send_rejoins();
          }
          break;
        }
        case MODE:
          if (msg.param(0) == nicks().in_nick())
            user_mode().new_server_message_received(msg);
          else
            fully_processed = false;
          break;
        case 221:
          break;
        case 396:       // ... is now your hidden host
        {
          server_connection().change_state(login_sent, real_nick_sent);
          // Numeric 396 has the hidden hostname in parameter 1.
          identity().set_hostname(msg.param(1));
          if (!server_connection().secondary_connection())
          {
            identity().client_session().queue_msg_me_as_is(msg);
            nicks().send_nick(identity().client_session().client_in_nick());
          }
          else
            send_rejoins();
          break;
        }
        case JOIN:
        {
          // Handle JOIN's from the pipeline.
          boost::shared_ptr<Channel> channel(join_pipeline(msg.param(0)));
          if (!channel.get())
          {
            // Not in the pipeline. Process normally.
            ASSERT(!server_connection().secondary_connection());
            fully_processed = false;
            break;
          }
          Target::serverside_add_channel(*this, channel);
          if (!server_connection().secondary_connection())
            channel->reset_received_names();
          else if (M_join_pipeline.empty())
          {
            // This was the last join.
            // FIXME: switch ServerConnection etc.
            identity().swap_primary_and_secondary_connection();
            identity().secondary_server_connection()->disconnect();
          }
          break;
        }
        default:
          fully_processed = false;
          break;
      }
      break;
    }
  }
  if (pre_network_message)
  {
    // Pass message on as-is, only replacing my own nick name at param 0.
    Prefix prefix(msg);
    MessageOut msgout(default_priority(msg.key()));
    identity().client_session().queue_msg(msgout << prefix << msg.key() << identity().client_session().client_out_nick() << msg.params(1));
  }
  else if (!fully_processed)
  {
    if (!M_server_connection.secondary_connection())
    {
      // Decode messages other than PING, ERROR, own nick changes.
      identity().new_server_message_received(msg);
    }
#ifdef CWDEBUG
    else
      Dout(dc::warning, "IGNORING secondary server message: " << msg);
#endif
  }
  // Turn debug output on again, if it was suppressed.
  Debug(if (suppress_debug_output) libcw_do.on());
}
void ServerSession::network_connection_terminated (void) [protected, virtual]
A read(2) on the socket returned 0.
Definition at line 521 of file ServerSession.cc.
References DoutEntering, IdentityReference::identity(), M_disconnect_reason, M_server_connection, ServerConnection::secondary_connection(), Identity::send_notice(), and ServerConnection::server().
{
#ifdef CWDEBUG
  debug::SecondaryConnection dummy(M_server_connection.secondary_connection());
#endif
  DoutEntering(dc::debug, "ServerSession::network_connection_terminated()");
  std::string disconnect_reason;
  if (M_disconnect_reason.empty())
    disconnect_reason = "EOF from server";
  else
    disconnect_reason = M_disconnect_reason;
  identity().send_notice("Lost connection with " + M_server_connection.server()->get_irc_name() + ": " + disconnect_reason);
}
void ServerSession::send_rejoins (void) [private]
Send a JOIN to the server for every channel we are on.
Definition at line 239 of file ServerSession.cc.
References ASSERT, Identity::client_session(), default_priority(), DoutEntering, IdentityReference::identity(), ClientSession::joined_channels(), joined_channels(), M_join_pipeline, and queue_msg().
Referenced by new_message_received().
{
  DoutEntering(dc::debug, "ServerSession::send_rejoins()");
  // Sent a JOIN for each channel that the client still thinks it is on.
  MessageOut msgout(default_priority(keys::JOIN));
  msgout << keys::JOIN;
  size_t total_buffer_size = 8; // "JOIN \r\n\0"
  bool first_channel = true;
  bool first_key = true;
  std::string keys;
  // First do all channels that have a key.
  for (int with_keys = 1; with_keys >= 0; --with_keys)
  {
    for (ClientSession::joined_channels_type::iterator iter = identity().client_session().joined_channels().begin();
         iter != identity().client_session().joined_channels().end(); ++iter)
    {
      boost::shared_ptr<Channel> channel(boost::static_pointer_cast<Channel>(iter->second));
      if (with_keys == channel->has_key())
      {
        for(;;)
        {
          total_buffer_size +=
              (first_channel ? 0 : 1) +                 // 1 for comma.
              channel->out_name(*this).size() +
              (with_keys ? 1 + channel->key().size() : 0);      // 1 for space or comma.
          if (total_buffer_size <= 512)                 // We always break out here the first or second time,
            break;                                              // because 8 + MAXCHANLEN (~200) + 1 + MAXKEYLEN (23) <= 512.
          if (!first_key)
            msgout << keys;
          queue_msg(msgout);                            // Send message constructed so far.
          msgout << keys::JOIN;                         // This resets the msgout.
          total_buffer_size = 8;
          first_channel = true;
          first_key = true;
        }
        if (first_channel)
        {
          msgout << channel;
          first_channel = false;
        }
        else
        {
          msgout << JustInTimeCatenate(',');
          msgout << JustInTimeCatenate(channel);
        }
        if (with_keys)
        {
          if (first_key)
          {
            keys = channel->key();
            first_key = false;
          }
          else
          {
            keys += ',';
            keys += channel->key();
          }
        }
        // Remember that we sent a re-JOIN for this channel.
#if defined(CWDEBUG) || defined(DEBUG)
        std::pair<join_pipeline_type::iterator, bool> res =
#endif
            M_join_pipeline.insert(join_pipeline_type::value_type(channel->out_name(*this), channel));
        ASSERT(res.second);
      }
    }
  }
  // Finish up.
  if (!first_key)
    msgout << keys;
  if (!first_channel)
    queue_msg(msgout);
}
Member Data Documentation
ServerConnection& ServerSession::M_server_connection [private]
The owning object.
Definition at line 53 of file ServerSession.h.
Referenced by detected_network(), force_quit(), found_network_name(), network_connection_terminated(), new_message_received(), server_connection(), start_authentication(), and ~ServerSession().
MatcherEventServer ServerSession::M_message_event_server [private]
Event server for incoming messages.
Definition at line 54 of file ServerSession.h.
Referenced by message_event_server(), and new_message_received().
NickPair ServerSession::M_server_session_nicks [private]
Server side nick pair.
Definition at line 55 of file ServerSession.h.
Referenced by new_message_received(), and nicks().
joined_channels_type ServerSession::M_joined_channels [private]
Serverside lookup map for channels joined by this identity.
Definition at line 56 of file ServerSession.h.
Referenced by joined_channels().
UserMode ServerSession::M_user_mode [private]
My user mode.
Definition at line 57 of file ServerSession.h.
Referenced by user_mode().
boost::shared_ptr<AuthState> ServerSession::M_auth_state [private]
Pointer object with temporary authentication state information.
Definition at line 58 of file ServerSession.h.
Referenced by auth_ping_argument(), authentication_successful(), set_auth_ping_argument(), and start_authentication().
Queue ServerSession::M_output_queue [private]
Queue for output messages.
Definition at line 59 of file ServerSession.h.
Referenced by queue_msg().
std::queue<WhoRequest> ServerSession::M_who_queue [private]
Queue storing WHO request messages.
Definition at line 60 of file ServerSession.h.
Referenced by current_who_request(), pop_who_request(), and send_who_write_event().
ISupport ServerSession::M_i_support [private]
Object that stores the numeric 005 information.
Definition at line 61 of file ServerSession.h.
Referenced by detected_network(), i_support(), and new_message_received().
std::string ServerSession::M_network_name [private]
Temporary storage of the network name as decoded from numeric 001, until numeric 005 is received.
Definition at line 62 of file ServerSession.h.
Referenced by found_network_name(), and new_message_received().
int ServerSession::S_server_sessions = 0 [static, private]
Total number of server session objects.
Definition at line 63 of file ServerSession.h.
Referenced by ServerSession(), and ~ServerSession().
std::string ServerSession::M_umodes [private]
The user modes as received in numeric 004.
Definition at line 64 of file ServerSession.h.
Referenced by detected_network(), and new_message_received().
join_pipeline_type ServerSession::M_join_pipeline [private]
Channels for which we sent a JOIN as part of a reconnect.
Definition at line 65 of file ServerSession.h.
Referenced by join_pipeline(), new_message_received(), and send_rejoins().
std::string ServerSession::M_disconnect_reason [private]
An error message that should be sent to the client if the connection is lost, if any.
Definition at line 66 of file ServerSession.h.
Referenced by network_connection_terminated(), and set_disconnect_reason().
Bool ServerSession::M_detected_network
True if the network is fully detected.
Definition at line 69 of file ServerSession.h.
Referenced by detected_network(), and ServerConnection::send_pong_and_mode().
The documentation for this class was generated from the following files:
ServerSession.h
ServerSession.cc
Copyright © 2005-2007 Carlo Wood. All rights reserved.