ircproxy The Ultimate Cyborg
ClientSession Class Reference
#include <ClientSession.h>
Detailed Description
A client session, from connect till disconnect.
This class represents a client session: from that a client successfully connects to the application's listen socket, until the connection is closed or lost again.
Definition at line 45 of file ClientSession.h.
Public Types
typedef std::map< std::string,
boost::shared_ptr< Target >
, IRC_less > private_targets_type
The type of the map with the private targets that the client has joined.
typedef target_hold_map_type joined_channels_type
The type of M_joined_channels.
Public Member Functions
ClientSession (void)
Default constructor.
~ClientSession ()
Destructor.
void fatal_error (char const *error_msg)
A fatal error occured. Calling this function will terminate the ClientSession.
void new_client_nick_received (std::string const &nick)
Called from Identity::new_client_message_received for NICK messages.
std::string const & client_in_nick (void) const
Returns the last NICK as received from the client in this session.
std::string const & client_out_nick (void) const
FIXME.
void process_message (ClientMessageIn const &msg)
Decode message msg.
void queue_message (ClientMessageIn const &msg)
Queue message msg.
void start_queuing_messages (void)
Start queuing messages.
void stop_queuing_messages (DestructEventType const &)
Stop queuing messages.
void add_private_target (boost::shared_ptr< Target > const &target)
Add target to the private targets list.
void del_private_target (std::string const &target_name)
Remove target_name from the private targets list.
private_targets_type & private_targets (void)
Return reference to map with private targets.
private_targets_type const & private_targets (void) const
Return const reference to map with private targets.
joined_channels_type & joined_channels (void)
Return reference to map with known channels.
joined_channels_type const & joined_channels (void) const
Return const reference to map with known channels.
void create_private_target (std::string const &target_name, Network &network)
Check if target already exists, if not, create it and add it to our private targets map.
void queue_msg (MessageOut const &msgout)
Send an output message to this session.
void queue_msg_as_is (ServerMessageIn const &msg)
Pass message msg on to the client with default priority, without changing anything.
void queue_msg_me_as_is (ServerMessageIn const &msg)
Pass message msg on to the client with default priority, changing only the target: my nick.
void serversession_lost (void)
This function is called from ServerSession::session_lost().
boost::shared_ptr< Nick > get_nick (std::string const &nick_name, bool create=false)
Get or create a Nick for nick_name.
Public Attributes
UserAnswerEventServer user_answer_event_server
The UserAnswer event server.
DestructEventServer destruct_event_server
The DestructEvent event server.
Protected Member Functions
virtual void new_message_received (ClientMessageIn const &)
Incoming event from ClientSessionInput.
Private Attributes
std::string M_in_nick
The last NICK as received from the client in this session.
bool M_queue_messages
Set if messages need to be queued instead of processed.
std::deque< ClientMessageIn > M_msg_queue
The message queue.
bool M_first_nick
Set before the first NICK message is received from the client.
private_targets_type M_private_targets
Map with private targets that the client has joined.
joined_channels_type M_joined_channels
Clientside lookup map for channels joined by this identity.
Member Typedef Documentation
typedef std::map<std::string, boost::shared_ptr<Target>, IRC_less> ClientSession::private_targets_type
The type of the map with the private targets that the client has joined.
Definition at line 49 of file ClientSession.h.
typedef target_hold_map_type ClientSession::joined_channels_type
The type of M_joined_channels.
Definition at line 51 of file ClientSession.h.
Constructor & Destructor Documentation
ClientSession::ClientSession (void) [inline]
Default constructor.
Definition at line 67 of file ClientSession.h.
References debug::channels::dc::objects.
                      : event_client_ct(), M_queue_messages(false), M_first_nick(true)
      { Dout(dc::objects, "Constructing ClientSession() " << *this); }
ClientSession::~ClientSession ()
Destructor.
Definition at line 182 of file ClientSession.cc.
References destruct_event_server, IdentityReference::has_identity(), IdentityReference::identity(), debug::channels::dc::objects, Identity::reset_client_session(), and user_answer_event_server.
{
  Dout(dc::objects, "Destructing ClientSession " << *this);
  if (has_identity())
    identity().reset_client_session(this);
  // First erase pending UserAnswer requests.
  user_answer_event_server.destroy_requests();
  // Then trigger the destruct event.
  destruct_event_server.trigger(DestructEventType());
  // Finally cancel all other event requests for this object.
  cancel_all_requests();
}
Member Function Documentation
void ClientSession::fatal_error (char const * error_msg)
A fatal error occured. Calling this function will terminate the ClientSession.
Definition at line 172 of file ClientSession.cc.
References DoutEntering.
Referenced by new_message_received(), and process_message().
{
  DoutEntering(dc::debug, "ClientSession::fatal_error(\"" << error_msg << "\")");
  if (!must_be_removed())               // Only write one error at a time.
    *this << "ERROR :" << error_msg << "\r\n";
  // The next method sets 'must_be_removed()' to true,
  // flushes the error and deletes this object (non-blocking).
  del();
}
void ClientSession::new_client_nick_received (std::string const & nick)
Called from Identity::new_client_message_received for NICK messages.
Definition at line 247 of file ClientSession.cc.
References Identity::authentication(), default_priority(), IdentityReference::identity(), M_first_nick, M_in_nick, Identity::mynick(), ServerSession::queue_msg(), Authentication::received_nick(), ServerSession::send_nick_write_event(), and Identity::server_session().
Referenced by Identity::new_client_message_received().
{
  M_in_nick = nick;
  if (!M_first_nick)
  {
    // Client tries to change nick name.
    PseudoMessageOut pseudo_msg(default_priority(keys::NICK));
    pseudo_msg.writeEventRequest(identity().server_session(), &ServerSession::send_nick_write_event, M_in_nick);
    identity().server_session().queue_msg(pseudo_msg);
  }
  else
  {
    identity().mynick()->set_in_nick(*this, M_in_nick);         // Initialize out client-side nick name.
    identity().authentication().received_nick();
  }
  M_first_nick = false;
}
std::string const& ClientSession::client_in_nick (void) const [inline]
Returns the last NICK as received from the client in this session.
Definition at line 80 of file ClientSession.h.
References M_in_nick.
Referenced by QuestionTarget::new_client_message_received().
{ return M_in_nick; }
std::string const& ClientSession::client_out_nick (void) const [inline]
FIXME.
Definition at line 83 of file ClientSession.h.
References M_in_nick.
Referenced by QuestionTarget::create_channel_and_ask_question(), PrivateTarget::do_names_output(), PrivateTarget::handle_command(), PrivateTarget::new_client_message_received(), ServerSession::new_message_received(), and Identity::notice_target().
{ return M_in_nick; }
void ClientSession::process_message (ClientMessageIn const & msg)
Decode message msg.
Definition at line 121 of file ClientSession.cc.
References edragon::caught(), DoutEntering, fatal_error(), IdentityReference::identity(), Identity::new_client_message_received(), and FatalError::what().
Referenced by new_message_received(), and stop_queuing_messages().
{
  DoutEntering(dc::debug, "ClientSession::process_message(" << msg << ")");
  try
  {
    identity().new_client_message_received(msg);
  }
  catch (FatalError& error)
  {
    Debug(edragon::caught(error));
    fatal_error(error.what());
    return;
  }
}
void ClientSession::queue_message (ClientMessageIn const & msg)
Queue message msg.
Definition at line 151 of file ClientSession.cc.
References DoutEntering, and M_msg_queue.
Referenced by new_message_received().
{
  DoutEntering(dc::debug, "ClientSession::queue_message(" << msg << ")");
  M_msg_queue.push_front(msg);
}
void ClientSession::start_queuing_messages (void)
Start queuing messages.
Definition at line 136 of file ClientSession.cc.
References M_queue_messages.
Referenced by new_message_received().
{
  M_queue_messages = true;
}
void ClientSession::stop_queuing_messages (DestructEventType const &)
Stop queuing messages.
Definition at line 141 of file ClientSession.cc.
References M_msg_queue, M_queue_messages, and process_message().
Referenced by new_message_received().
{
  while (!M_msg_queue.empty())
  {
    process_message(M_msg_queue.back());
    M_msg_queue.pop_back();
  }
  M_queue_messages = false;
}
void ClientSession::add_private_target (boost::shared_ptr< Target > const & target)
Add target to the private targets list.
Definition at line 196 of file ClientSession.cc.
References ASSERT, and M_private_targets.
Referenced by Identity::notice_target().
{
#if defined(DEBUG) || defined(CWDEBUG)
  std::pair<private_targets_type::iterator, bool> result =
#endif
      M_private_targets.insert(private_targets_type::value_type(target->in_name(*this), target));
  ASSERT(result.second);
}
void ClientSession::del_private_target (std::string const & target_name)
Remove target_name from the private targets list.
Definition at line 206 of file ClientSession.cc.
References ASSERT, and M_private_targets.
Referenced by ServerConnection::do_connect(), and PrivateTarget::new_client_message_received().
{
  private_targets_type::iterator iter = M_private_targets.find(target_name);
  ASSERT(iter != M_private_targets.end());
  M_private_targets.erase(iter);
}
private_targets_type& ClientSession::private_targets (void) [inline]
Return reference to map with private targets.
Definition at line 101 of file ClientSession.h.
References M_private_targets.
Referenced by Target::clientside_get_channel(), get_nick(), Identity::new_client_message_received(), and Identity::notice_target().
{ return M_private_targets; }
private_targets_type const& ClientSession::private_targets (void) const [inline]
Return const reference to map with private targets.
Definition at line 104 of file ClientSession.h.
References M_private_targets.
{ return M_private_targets; }
joined_channels_type& ClientSession::joined_channels (void) [inline]
Return reference to map with known channels.
Definition at line 107 of file ClientSession.h.
References M_joined_channels.
Referenced by Target::add_channel(), Target::clientside_get_channel(), Channel::new_client_message_received(), ServerSession::send_rejoins(), serversession_lost(), Target::sub_channel(), and Identity::~Identity().
{ return M_joined_channels; }
joined_channels_type const& ClientSession::joined_channels (void) const [inline]
Return const reference to map with known channels.
Definition at line 110 of file ClientSession.h.
References M_joined_channels.
{ return M_joined_channels; }
void ClientSession::create_private_target (std::string const & target_name, Network & network)
Check if target already exists, if not, create it and add it to our private targets map.
Create a new target target_name and add it to the private targets map, unless it already exists.
Definition at line 214 of file ClientSession.cc.
References ASSERT, DoutEntering, IdentityReference::identity(), is_channel(), is_nick(), Network::is_private(), and M_private_targets.
Referenced by QuestionTarget::create_channel_and_ask_question().
{
  DoutEntering(dc::debug, "ClientSession::create_private_target(\"" << target_name << "\", " << network << ')');
  ASSERT(network.is_private());
  private_targets_type::iterator iter = M_private_targets.find(target_name);
  if (iter == M_private_targets.end())
  {
    Dout(dc::debug, "Not found. Creating new private target.");
    if (is_channel(target_name))
    {
      boost::shared_ptr<Target> new_target(NEW(Channel(identity(), target_name, network, 0)));
      M_private_targets.insert(private_targets_type::value_type(target_name, new_target));
    }
    else
    {
      ASSERT(is_nick(target_name));
      boost::shared_ptr<Target> new_target(NEW(Nick(*this, target_name, network)));
      M_private_targets.insert(private_targets_type::value_type(target_name, new_target));
    }
  }
#ifdef CWDEBUG
  else
    Dout(dc::debug, "Found: " << *iter);
#endif
}
void ClientSession::queue_msg (MessageOut const & msgout)
Send an output message to this session.
Definition at line 240 of file ClientSession.cc.
References DoutEntering, and MessageOut::write_to().
Referenced by Identity::new_client_message_received(), ServerSession::new_message_received(), Identity::new_server_message_received(), Channel::new_server_message_received(), queue_msg_as_is(), and queue_msg_me_as_is().
{
  DoutEntering(dc::debug, "ClientSession::queue_msg(" << msgout << ")");
  // No need to queue anything (yet?), just send it to the client.
  msgout.write_to(*this);
}
void ClientSession::queue_msg_as_is (ServerMessageIn const & msg)
Pass message msg on to the client with default priority, without changing anything.
Definition at line 157 of file ClientSession.cc.
References default_priority(), MessageIn::key(), MessageIn::params(), and queue_msg().
{
  Prefix prefix(msg);
  MessageOut msgout(default_priority(msg.key()));
  queue_msg(msgout << prefix << msg.key() << msg.params(0));
}
void ClientSession::queue_msg_me_as_is (ServerMessageIn const & msg)
Pass message msg on to the client with default priority, changing only the target: my nick.
Definition at line 164 of file ClientSession.cc.
References ASSERT, default_priority(), IdentityReference::identity(), MessageIn::key(), Identity::mynick(), MessageIn::param(), MessageIn::params(), queue_msg(), and ServerMessageIn::server_session().
Referenced by ServerSession::new_message_received().
{
  ASSERT(msg.param(0) == identity().mynick()->in_name(msg.server_session()));
  Prefix prefix(msg);
  MessageOut msgout(default_priority(msg.key()));
  queue_msg(msgout << prefix << msg.key() << identity().mynick() << msg.params(1));
}
void ClientSession::serversession_lost (void)
This function is called from ServerSession::session_lost().
Definition at line 265 of file ClientSession.cc.
References Identity::do_quit(), IdentityReference::identity(), and joined_channels().
Referenced by ServerConnection::session_lost().
{
  // Run over all channels that we're on.
  for (joined_channels_type::iterator channel_iter = joined_channels().begin(); channel_iter != joined_channels().end(); ++channel_iter)
  {
    boost::shared_ptr<Channel> const& channel(boost::static_pointer_cast<Channel>(channel_iter->second));
    // Run over all members.
    for (Channel::members_type::iterator member_iter = channel->members().begin(); member_iter != channel->members().end();)
    {
      // QUIT all members except myself.
      boost::shared_ptr<Nick> const& nick((member_iter++)->second.get_nick());
      if (!nick->is_me())
        identity().do_quit(nick, "ircproxy lost connection");
    }
  }
}
boost::shared_ptr< Nick > ClientSession::get_nick (std::string const & nick_name, bool create = false)
Get or create a Nick for nick_name.
Definition at line 282 of file ClientSession.cc.
References ASSERT, is_nick(), private_targets(), and THROW_EXCEPTION.
Referenced by Identity::new_client_message_received().
{
  ASSERT(is_nick(nick_name));
  // First search in the map with private targets.
  private_targets_type::const_iterator priv_iter = private_targets().find(nick_name);
  if (priv_iter != private_targets().end())
    return boost::static_pointer_cast<Nick>(priv_iter->second);
  // FIXME
  THROW_EXCEPTION(unknown_target(), "There is no client side nick \"" << nick_name << "\" on ClientSession " << *this);
}
void ClientSession::new_message_received (ClientMessageIn const & msg) [protected, virtual]
Incoming event from ClientSessionInput.
Definition at line 37 of file ClientSession.cc.
References destruct_event_server, DoutEntering, fatal_error(), IdentityReference::has_identity(), IdentityReference::identity(), MessageIn::key(), M_queue_messages, MessageIn::param(), process_message(), queue_message(), Identity::set_client_session(), Identity::set_hostname(), IdentityReference::set_identity(), start_queuing_messages(), and stop_queuing_messages().
{
#ifdef CWDEBUG
  // Suppress all debug output related to PING messages.
  bool suppress_debug_output =
      (msg.key() == keys::PING && Application::instance().suppress_ping()) ||
      (msg.key() == keys::WHO && Application::instance().suppress_who());
  Debug(if (suppress_debug_output) libcw_do.off());
#endif
  DoutEntering(dc::debug, "ClientSession::new_message_received(" << msg << ")");
  if (must_be_removed())
  {
    Dout(dc::debug, "Do nothing, ClientSession is marked for removal.");
    // Turn debug output on again, if it was suppressed.
    Debug(if (suppress_debug_output) libcw_do.on());
    // Skip message.
    return;
  }
  if (!has_identity())
  {
    if (msg.key() != keys::PASS)
    {
      // Turn debug output on again, if it was suppressed.
      Debug(if (suppress_debug_output) libcw_do.on());
      Dout(dc::notice, "Received non-PASS message from client without Identity (" << msg << ')');
      // Error. The first message from a client must ALWAYS be a PASS.
      fatal_error("Send PASS first.");
      return;
    }
    Dout(dc::debug, "Received PASS: " << msg);
    std::string password(msg.param(0));
    if (password.empty())
    {
      fatal_error("Empty password.");
      return;
    }
    else
    {
      // Find or create Identity.
      identities_type::iterator iter = Application::instance().identities().find(password);
      if (iter == Application::instance().identities().end())
      {
        // Create new Identity.
        Identity identity(password);
        set_identity(&Application::instance().identities().
            insert(std::pair<std::string, Identity>(password, identity)).first->second);
        Dout(dc::debug, "Created a new Identity.");
      }
      else
      {
        set_identity(&iter->second);
        // If the identity already has another ClientSession, kill that.
        if (identity().has_client_session())
        {
          ClientSession& old_client_session(identity().client_session());
          std::ostringstream error_msg;
          error_msg << "Received new client connection from " << old_client_session.remote_ip();
          old_client_session.fatal_error(error_msg.str().c_str());
          // Wait till the old session is actually destructed before processing
          // messages from this connection.
          start_queuing_messages();
          // Request stop_queuing_messages to be called when old_client_session is destructed.
          old_client_session.destruct_event_server(*this, &ClientSession::stop_queuing_messages);
        }
      }
      identity().set_client_session(this);
      if (identity().hostname() != unknown_hostname)
      {
        std::ostringstream buf;
        buf << remote_ip();
        identity().set_hostname(buf.str());
      }
    }
  }
  if (!M_queue_messages)
    process_message(msg);
  else
    queue_message(msg);
  // Turn debug output on again, if it was suppressed.
  Debug(if (suppress_debug_output) libcw_do.on());
}
Member Data Documentation
std::string ClientSession::M_in_nick [private]
The last NICK as received from the client in this session.
Definition at line 54 of file ClientSession.h.
Referenced by client_in_nick(), client_out_nick(), and new_client_nick_received().
bool ClientSession::M_queue_messages [private]
Set if messages need to be queued instead of processed.
Definition at line 55 of file ClientSession.h.
Referenced by new_message_received(), start_queuing_messages(), and stop_queuing_messages().
std::deque<ClientMessageIn> ClientSession::M_msg_queue [private]
The message queue.
Definition at line 56 of file ClientSession.h.
Referenced by queue_message(), and stop_queuing_messages().
bool ClientSession::M_first_nick [private]
Set before the first NICK message is received from the client.
Definition at line 57 of file ClientSession.h.
Referenced by new_client_nick_received().
private_targets_type ClientSession::M_private_targets [private]
Map with private targets that the client has joined.
Definition at line 58 of file ClientSession.h.
Referenced by add_private_target(), create_private_target(), del_private_target(), and private_targets().
joined_channels_type ClientSession::M_joined_channels [private]
Clientside lookup map for channels joined by this identity.
Definition at line 59 of file ClientSession.h.
Referenced by joined_channels().
UserAnswerEventServer ClientSession::user_answer_event_server
The UserAnswer event server.
Definition at line 62 of file ClientSession.h.
Referenced by ServerConnection::connect(), ServerSession::found_network_name(), QuestionTarget::new_client_message_received(), Identity::received_network_domain_answer(), and ~ClientSession().
DestructEventServer ClientSession::destruct_event_server
The DestructEvent event server.
Definition at line 63 of file ClientSession.h.
Referenced by new_message_received(), and ~ClientSession().
The documentation for this class was generated from the following files:
ClientSession.h
ClientSession.cc
Copyright © 2005-2007 Carlo Wood. All rights reserved.