ircproxy The Ultimate Cyborg
Application Class Reference
#include <Application.h>
Detailed Description
The application singleton.
This class represents the application itself. It is a singleton and needs to be accessed through Application::instance().
Definition at line 38 of file Application.h.
Public Member Functions
~Application () throw ()
Destructor.
networks_type const & networks (void) const
A const reference to an STL container with all known networks.
networks_type & networks (void)
A reference to the STL container with all known networks.
identities_type const & identities (void) const
A const reference to a map with all known identities.
identities_type & identities (void)
A reference to the map with all known identities.
msg_block_ct & dummy_msg_block (void)
A dummy message block that can be used as place holder.
void serialize (PersistXML &xml)
Serialize application to XML.
void last_server_session_destroyed (void)
This function is called from the destructor of the last ServerSession.
Protected Member Functions
virtual void start (void)
Start application.
virtual void finish_options (void)
Process remaining command line arguments.
virtual void print_version (std::ostream &) const
Print version information.
virtual void main_entered (int *argc_ptr, char *const **argv_ptr)
Called immediately after we reached main.
void command_line_option_listen_port (char const *argument)
Process command line option --listen-port port.
Private Member Functions
Application (void)
Constructor.
void handle_signal (SignalType const &)
Called when a signal is received (SIGINT or SIGHUP).
Private Attributes
unsigned short M_listen_port
The listen port the IRC proxy listens on.
bool M_suppress_ping
True if PING/PONG debug messages should be suppressed.
bool M_suppress_who
True if WHO debug messages should be suppressed.
networks_type M_networks
List with all known networks.
identities_type M_identities
Map with all known identities.
memory_block_st * M_memory_block_dummy
Dummy variable used during construction.
msg_block_ct M_msg_block_dummy
Used for MessageIn objects not related to a real message block.
bool M_terminating
Set to true when the application should terminate after the last ServerSession is destructed.
Constructor & Destructor Documentation
Application::Application (void) [private]
Constructor.
Constructs an application object. The application will understand the commandline parameter --listen-port <port>, or -p <port>, next to all default commandline options (see documentation of libcw).
<port> is the port that the application will listen on for new client connections (on localhost).
See also:
Application::finish_options
Definition at line 44 of file Application.cc.
References command_line_option_listen_port().
                             :
    M_listen_port(0),
#ifdef CWDEBUG
    M_suppress_ping(false),
    M_suppress_who(false),
#endif
    M_memory_block_dummy(memory_block_st::create(0)),
    M_msg_block_dummy(M_memory_block_dummy->block_start(), 0, M_memory_block_dummy),
    M_terminating(false)
{
  add_option(&Application::command_line_option_listen_port,
             "listen-port", 'p', "<port>", "Port to listen on for new connections.");
#ifdef CWDEBUG
  add_option(&Application::command_line_option_suppress_ping,
             "suppress-ping", 0, NULL, "Suppress debug output regarding PING/PONG messages.");
  add_option(&Application::command_line_option_suppress_who,
             "suppress-who", 0, NULL, "Suppress debug output regarding WHO messages.");
#endif
}
Application::~Application () throw ()
Destructor.
The destructor does not throw.
Definition at line 68 of file Application.cc.
References M_identities, and M_memory_block_dummy.
{
  // Destroy all Identity's (and thus their target maps), before destroying the networks (and their targets map).
  M_identities.clear();
  // Release memory.
  M_memory_block_dummy->release();
}
Member Function Documentation
void Application::handle_signal (SignalType const & signal_type) [private]
Called when a signal is received (SIGINT or SIGHUP).
Definition at line 213 of file Application.cc.
References DoutEntering, identities(), and M_terminating.
Referenced by start().
{
  DoutEntering(dc::debug, "Application::handle_signal(" << signal_type << ")");
  switch(signal_type.get_signal())
  {
    case SIGHUP:
      Dout( dc::notice, "Received SIGHUP " << signal_type.get_count() << " times." );
      break;
    case SIGINT:
    {
      // QUIT all server connections.
      for (identities_type::iterator iter = identities().begin(); iter != identities().end(); ++iter)
      {
        if (iter->second.has_secondary_server_connection())
          iter->second.secondary_server_connection()->disconnect();
        if (iter->second.has_server_session())
          iter->second.server_connection().quit("ircproxy received SIGINT");    // This set reconnect to false and QUIT's the client.
      }
      // Terminate the application when the last ServerSession is closed.
      M_terminating = true;
      break;
    }
  }
}
networks_type const& Application::networks (void) const [inline]
A const reference to an STL container with all known networks.
Definition at line 64 of file Application.h.
References M_networks.
{ return M_networks; }
networks_type& Application::networks (void) [inline]
A reference to the STL container with all known networks.
Definition at line 67 of file Application.h.
References M_networks.
{ return M_networks; }
identities_type const& Application::identities (void) const [inline]
A const reference to a map with all known identities.
Definition at line 70 of file Application.h.
References M_identities.
Referenced by handle_signal().
{ return M_identities; }
identities_type& Application::identities (void) [inline]
A reference to the map with all known identities.
Definition at line 73 of file Application.h.
References M_identities.
{ return M_identities; }
msg_block_ct& Application::dummy_msg_block (void) [inline]
A dummy message block that can be used as place holder.
Definition at line 76 of file Application.h.
References M_msg_block_dummy.
{ return M_msg_block_dummy; }
void Application::start (void) [protected, virtual]
Start application.
This method is called at the start of the application. It initialized libcwd and creates a new listen socket that listens on Application::M_listen_port. Then the mainloop is started.
Definition at line 102 of file Application.cc.
References PersistXML::close(), handle_signal(), PersistXML::load, M_listen_port, PersistXML::open(), PersistXML::serialize(), and PersistXML::store.
{
#ifdef CWDEBUG
  // Redirect debug output to a file.
  static std::ofstream debug_file;
  debug_file.open("debug.out");
  static debug::TeeStream debug_stream(std::cout, debug_file);
  libcwd::libcw_do.set_ostream(&debug_stream);
#endif
  Dout(dc::notice, "Called Application::start()");
  // Object used to load/store persistant data.
  PersistXML xml;
  unsigned int commandline_listen_port = M_listen_port;
  // If xml file exists, load it.
  struct stat statbuf;
  if (stat("ircproxy.xml", &statbuf) != -1)
  {
    xml.open("ircproxy.xml", PersistXML::load);
    xml.serialize("Application", *this);
    xml.close();
  }
  // Divert signal handling.
  signalRequest(SignalRequestData(SIGINT, sigOneShot|sigReplace),
      Application::instance(), &Application::handle_signal);
  signalRequest(SignalRequestData(SIGHUP),
      Application::instance(), &Application::handle_signal);
  // Determine the listen port of the application.
  if (commandline_listen_port)
    M_listen_port = commandline_listen_port;
  else if (M_listen_port == 0)
    M_listen_port = 6667;                       // Default listen port.
  // Open a listen socket on M_listen_port.
  NEW(ProxyListenSocket(M_listen_port));
  mainloop();
  // Store persistent data.
  xml.open("ircproxy.xml", PersistXML::store);
  xml.serialize("Application", *this);
  xml.close();
  // Get rid of memory leaks of libxml2.
  xmlCleanupParser();
}
void Application::finish_options (void) [protected, virtual]
Process remaining command line arguments.
This method is called when all command options have been processed. If errflg is set, the usage message is printed to std::cerr and the application exists. If no port was specified, then the default port is set to 6667.
Definition at line 193 of file Application.cc.
{
  if (errflg)
  {
    print_usage(std::cerr);
    libcw_exit(2);
  }
}
void Application::print_version (std::ostream & os) const [protected, virtual]
Print version information.
This method is called when the application is called with commandline parameter --version or -v. See documentation of libcw.
Definition at line 208 of file Application.cc.
{
  os << PACKAGE_NAME << " " << VERSION << " by Carlo Wood <carlo@alinoe.com>\n";
}
void Application::main_entered (int * argc_ptr, char *const ** argv_ptr) [protected, virtual]
Called immediately after we reached main.
Initialize libcwd here, allowing the command line handling of libcw to override any debug channels and/or set a debug output file.
Definition at line 89 of file Application.cc.
References debug::init().
{
  Debug(debug::init());
}
void Application::command_line_option_listen_port (char const * argument) [protected]
Process command line option --listen-port port.
This method is called for every --listen-port or -p that is passed on the commandline. argument is set to either "--listen-port" or "-p" respectively. The global variable optarg is the port that is being passed. When <port> is less than or equal 1024 then an error is printed to std:cerr and the application is terminated.
Definition at line 164 of file Application.cc.
References M_listen_port.
Referenced by Application().
{
  M_listen_port = atoi(optarg);
  if (M_listen_port <= 1024)
  {
    std::cerr << application_name << ": " << argument << " : out of range" << std::endl;
    libcw_exit(-1);
  }
}
void Application::serialize (PersistXML & xml)
Serialize application to XML.
Definition at line 240 of file Application.cc.
References M_identities, M_listen_port, M_networks, and PersistXML::serialize().
{
  xml.serialize("M_listen_port", M_listen_port);
  xml.serialize("M_networks", M_networks);
  xml.serialize("M_identities", M_identities);
}
void Application::last_server_session_destroyed (void)
This function is called from the destructor of the last ServerSession.
Definition at line 77 of file Application.cc.
References M_terminating.
{
  if (M_terminating)
    fd_dct::return_when_done(-1);
}
Member Data Documentation
unsigned short Application::M_listen_port [private]
The listen port the IRC proxy listens on.
Definition at line 43 of file Application.h.
Referenced by command_line_option_listen_port(), serialize(), and start().
bool Application::M_suppress_ping [private]
True if PING/PONG debug messages should be suppressed.
Definition at line 45 of file Application.h.
bool Application::M_suppress_who [private]
True if WHO debug messages should be suppressed.
Definition at line 46 of file Application.h.
networks_type Application::M_networks [private]
List with all known networks.
Definition at line 48 of file Application.h.
Referenced by networks(), and serialize().
identities_type Application::M_identities [private]
Map with all known identities.
Definition at line 49 of file Application.h.
Referenced by identities(), serialize(), and ~Application().
memory_block_st* Application::M_memory_block_dummy [private]
Dummy variable used during construction.
Definition at line 50 of file Application.h.
Referenced by ~Application().
msg_block_ct Application::M_msg_block_dummy [private]
Used for MessageIn objects not related to a real message block.
Definition at line 51 of file Application.h.
Referenced by dummy_msg_block().
bool Application::M_terminating [private]
Set to true when the application should terminate after the last ServerSession is destructed.
Definition at line 52 of file Application.h.
Referenced by handle_signal(), and last_server_session_destroyed().
The documentation for this class was generated from the following files:
Application.h
Application.cc
Copyright © 2005-2007 Carlo Wood. All rights reserved.