ircproxy The Ultimate Cyborg
QuestionTarget Class Reference
#include <QuestionTarget.h>
Detailed Description
A fake channel that is used for communication between user and ircproxy.
The application can ask questions to the user. Doing so will cause the user to join a new channel where the question will be displayed. Answering the question has to be done on this channel as a public message.
Those public messages will end up being sent to this QuestionTarget object. Also any queries about the channel by the client will end up being sent to this target.
Definition at line 38 of file QuestionTarget.h.
Public Member Functions
QuestionTarget (ClientSession &client_session, std::string const &target_name, Network &network)
Construct a QuestionTarget with name target_name, defined uniquely for.
~QuestionTarget ()
Destructor.
QuestionTarget (QuestionTarget const &question_target)
Copy-constructor.
void set_user_question (boost::shared_ptr< UserQuestion > const &user_question)
void reset_user_question (void)
void create_channel_and_ask_question (void)
Ask a question.
virtual void new_client_message_received (ClientMessageIn const &msg)
Called when a new (client) message is received for this target.
Private Attributes
boost::shared_ptr< UserQuestion > M_user_question
Shared pointer to the associated UserQuestion.
Constructor & Destructor Documentation
QuestionTarget::QuestionTarget (ClientSession & client_session, std::string const & target_name, Network & network) [inline]
Construct a QuestionTarget with name target_name, defined uniquely for.
Definition at line 45 of file QuestionTarget.h.
References debug::channels::dc::objects.
                                                                                                  :
        PrivateTarget(client_session, target_name, network)
        { Dout(dc::objects, "Constructing QuestionTarget(" <<
            client_session << ", \"" << target_name << "\", " << network << ")"); }
#ifdef CWDEBUG
QuestionTarget::~QuestionTarget () [inline]
Destructor.
Definition at line 51 of file QuestionTarget.h.
{ Dout(dc::objects, "Destructing QuestionTarget " << *this); }
QuestionTarget::QuestionTarget (QuestionTarget const & question_target) [inline]
Copy-constructor.
Definition at line 53 of file QuestionTarget.h.
References debug::channels::dc::objects.
                                                          : PrivateTarget(question_target)
        { Dout(dc::objects, "Copy-constructing QuestionTarget from " << question_target); }
Member Function Documentation
void QuestionTarget::set_user_question (boost::shared_ptr< UserQuestion > const & user_question) [inline]
Assign the corresponding UserQuestion to this object. Called by UserAnswerEventRequestBase::UserAnswerEventRequestBase.
Definition at line 59 of file QuestionTarget.h.
References M_user_question.
{ M_user_question = user_question; }
void QuestionTarget::reset_user_question (void) [inline]
Disconnect UserQuestion from this object again. Called by UserAnswerEventRequestBase::~UserAnswerEventRequestBase.
Definition at line 62 of file QuestionTarget.h.
References M_user_question.
{ M_user_question.reset(); }
void QuestionTarget::create_channel_and_ask_question (void)
Ask a question.
Make the user join the associated channel and ask the question.
Definition at line 82 of file QuestionTarget.cc.
References ClientSession::client_out_nick(), ClientSession::create_private_target(), PrivateTarget::do_names_output(), and M_user_question.
Referenced by new_client_message_received().
{
  client_session() << ":" << client_session().client_out_nick() << " JOIN " << out_name(client_session()) << "\r\n";
  client_session().create_private_target(out_name(client_session()), client_session().identity().private_network());
  do_names_output();
  client_session() << ":Leandro PRIVMSG " << out_name(client_session()) << " :" << M_user_question->question() << "\r\n";
}
void QuestionTarget::new_client_message_received (ClientMessageIn const & msg) [virtual]
Called when a new (client) message is received for this target.
This function handles incoming messages for this target.
Reimplemented from PrivateTarget.
Definition at line 33 of file QuestionTarget.cc.
References ClientSession::client_in_nick(), ClientMessageIn::client_session(), create_channel_and_ask_question(), DoutEntering, Identity::hostname(), Identity::ident(), IdentityReference::identity(), is_channel(), MessageIn::key(), M_user_question, PrivateTarget::new_client_message_received(), MessageIn::param(), and ClientSession::user_answer_event_server.
{
  DoutEntering(dc::debug, "QuestionTarget::new_client_message_received(" << msg << ") for target \"" << in_name(msg.client_session()) << "\".");
  int param = 1;
  switch(msg.key())
  {
    case keys::MODE:
    case keys::NAMES:
    case keys::WHO:
      PrivateTarget::new_client_message_received(msg);
      return;
    case keys::PART:
      // Only ask the question when the request for the question still exists.
      // M_user_question is reset by a call to reset_user_question() from the destructor of the request object.
      if (M_user_question.get())
        create_channel_and_ask_question();              // Make clear we need an answer.
      else
        PrivateTarget::new_client_message_received(msg);
      break;
    case keys::JOIN:
      // We should already BE on the channel. However, bounce the join back to give a broken client the chance to synchronize.
      client_session() << ':' << client_session().client_in_nick() <<
          '!' << client_session().identity().ident() << '@' << client_session().identity().hostname() << " JOIN " << out_name(client_session()) << "\r\n";
      break;
    case keys::CPRIVMSG:
    case keys::CNOTICE:
      if (!is_channel(in_name(msg.client_session())))
        param = -1;
      param = 2;
      /* FALL-THROUGH */
    case keys::PRIVMSG:
    case keys::NOTICE:
      if (param == 1 || param == 2)
      {
        client_session().user_answer_event_server.trigger(UserAnswerEventType(msg.param(param), client_session(), out_name(client_session())));
        break;
      }
      /* FALL-THROUGH */
    default:
      client_session() << ":Leandro PRIVMSG " << out_name(client_session()) << " :Please type the answer in the channel.\r\n";
      break;
  }
}
Member Data Documentation
boost::shared_ptr<UserQuestion> QuestionTarget::M_user_question [private]
Shared pointer to the associated UserQuestion.
Definition at line 40 of file QuestionTarget.h.
Referenced by create_channel_and_ask_question(), new_client_message_received(), reset_user_question(), and set_user_question().
The documentation for this class was generated from the following files:
QuestionTarget.h
QuestionTarget.cc
Copyright © 2005-2007 Carlo Wood. All rights reserved.