ircproxy The Ultimate Cyborg
BoolExpression< inverted > Class Template Reference
#include <Bool.h>
Detailed Description
template<bool inverted>
class BoolExpression< inverted >
An Expression consisting of a single boolean (Bool).
Definition at line 32 of file Bool.h.
Public Types
typedef BoolExpression<!inverted > inverted_type
The type of the inverted expression.
typedef bool evaluation_type
The return type of evaluate_impl.
Public Member Functions
BoolExpression (Bool &b)
Copy constructor.
BoolExpression<!inverted > operator! (void) const
Inversion operator. Returns an inverted expression.
ExpressionEventServer & create_event_server (void)
Create and return an event server that is watching this expression.
bool evaluate_impl (void) const
Evaluate this expression.
void sub_event_server_impl (ExpressionEventServer *)
Implementation of sub_event_server(). Remove event server event_server from the notification list.
virtual void add_event_server (boost::shared_ptr< ExpressionEventServer > const &event_server)
Add event server event_server to notification list.
virtual bool evaluate (void)
Implementation of pure virtual function ExpressionInterface::evaluate.
virtual void sub_event_server (ExpressionEventServer *event_server)
Implementation of pure virtual function ExpressionInterface::sub_event_server.
virtual void print_on (std::ostream &os) const
For debugging purposes. Write the contents of this object to os.
Private Attributes
Bool & M_b
The underlying Bool.
Member Typedef Documentation
template<bool inverted> typedef BoolExpression<!inverted> BoolExpression< inverted >::inverted_type
The type of the inverted expression.
Definition at line 34 of file Bool.h.
template<bool inverted> typedef bool BoolExpression< inverted >::evaluation_type
The return type of evaluate_impl.
Definition at line 35 of file Bool.h.
Constructor & Destructor Documentation
template<bool inverted> BoolExpression< inverted >::BoolExpression (Bool & b) [inline]
Copy constructor.
Definition at line 42 of file Bool.h.
Referenced by BoolExpression< inverted >::create_event_server().
: M_b(b) { }
Member Function Documentation
template<bool inverted> BoolExpression<!inverted> BoolExpression< inverted >::operator! (void) const [inline]
Inversion operator. Returns an inverted expression.
Definition at line 45 of file Bool.h.
References BoolExpression< inverted >::M_b.
{ return BoolExpression<!inverted>(M_b); }
template<bool inverted> ExpressionEventServer & BoolExpression< inverted >::create_event_server (void) [inline]
Create and return an event server that is watching this expression.
Definition at line 21 of file Bool.inl.
References BoolExpression< inverted >::BoolExpression(), and debug::channels::dc::expression.
  {
    boost::shared_ptr<ExpressionInterface> expression(new BoolExpression(*this));
    boost::shared_ptr<ExpressionEventServer> event_server(new ExpressionEventServer(expression));
    expression->add_event_server(event_server);
    return *event_server;
  }
template<bool inverted> bool BoolExpression< inverted >::evaluate_impl (void) const [inline]
Evaluate this expression.
Definition at line 177 of file Bool.h.
References BoolExpression< inverted >::M_b, and Bool::value().
Referenced by BoolExpression< inverted >::evaluate().
{
  return M_b.value() != inverted;
}
template<bool inverted> void BoolExpression< inverted >::sub_event_server_impl (ExpressionEventServer * event_server) [inline]
Implementation of sub_event_server(). Remove event server event_server from the notification list.
Definition at line 184 of file Bool.h.
References BoolExpression< inverted >::M_b, and Bool::sub_event_server().
Referenced by BoolExpression< inverted >::sub_event_server().
{
  M_b.sub_event_server(event_server);
}
template<bool inverted> void BoolExpression< inverted >::add_event_server (boost::shared_ptr< ExpressionEventServer > const & event_server) [inline, virtual]
Add event server event_server to notification list.
Implements ExpressionInterface.
Definition at line 168 of file Bool.h.
References Bool::add_event_server(), and BoolExpression< inverted >::M_b.
{
  M_b.add_event_server(event_server);
}
template<bool inverted> virtual bool BoolExpression< inverted >::evaluate (void) [inline, virtual]
Implementation of pure virtual function ExpressionInterface::evaluate.
Implements ExpressionInterface.
Definition at line 55 of file Bool.h.
References BoolExpression< inverted >::evaluate_impl().
{ return evaluate_impl(); }
template<bool inverted> virtual void BoolExpression< inverted >::sub_event_server (ExpressionEventServer * event_server) [inline, virtual]
Implementation of pure virtual function ExpressionInterface::sub_event_server.
Implements ExpressionInterface.
Definition at line 57 of file Bool.h.
References BoolExpression< inverted >::sub_event_server_impl().
{ sub_event_server_impl(event_server); }
template<bool inverted> void BoolExpression< inverted >::print_on (std::ostream & os) const [inline, virtual]
For debugging purposes. Write the contents of this object to os.
Implements ExpressionInterface.
Definition at line 158 of file Bool.h.
References BoolExpression< inverted >::M_b, and Bool::print_name().
{
  if (inverted)
    os << '!';
  M_b.print_name(os);
}
Member Data Documentation
template<bool inverted> Bool& BoolExpression< inverted >::M_b [private]
The underlying Bool.
Definition at line 38 of file Bool.h.
Referenced by BoolExpression< inverted >::add_event_server(), BoolExpression< inverted >::evaluate_impl(), BoolExpression< inverted >::operator!(), BoolExpression< inverted >::print_on(), and BoolExpression< inverted >::sub_event_server_impl().
The documentation for this class was generated from the following files:
Bool.h
Bool.inl
Copyright © 2005-2007 Carlo Wood. All rights reserved.