ircproxy The Ultimate Cyborg
Prefix Class Reference
#include <Prefix.h>
Detailed Description
A class representing a message prefix.
Definition at line 29 of file Prefix.h.
Public Member Functions
Prefix (void)
The prefix, if it's a server (or any fixed string).
Prefix (ClientMessageIn const &msg)
Constructor.
Prefix (ServerMessageIn const &msg)
Constructor.
Prefix (ServerSession &server_session, std::string const &prefix)
Constructor.
Prefix (ClientSession &client_session, std::string const &prefix)
Constructor.
Prefix (boost::shared_ptr< Nick > const &nick)
Constructor.
Prefix (std::string const &fixed_prefix_str)
Constructor.
Prefix (Prefix const &prefix)
Constructor.
~Prefix ()
Destructor.
std::string out_prefix (ClientSession const &client_session, bool allow_uninitialized=false) const
Return the clientside prefix.
std::string out_prefix (ServerSession const &server_session, bool allow_uninitialized=false) const
Return the serverside prefix.
bool empty (void) const
Return true if there is no prefix.
boost::shared_ptr< Nick > get_nick (void)
Return shared pointer to underlying nick.
boost::shared_ptr< Nick const > get_nick (void) const
Return shared pointer to underlying nick constant.
Private Attributes
std::string M_server_name
The underlying Nick, if it's a user.
Constructor & Destructor Documentation
Prefix::Prefix (void) [inline]
The prefix, if it's a server (or any fixed string).
Default constructor.
Definition at line 35 of file Prefix.h.
References debug::channels::dc::objects.
{ Dout(dc::objects, "Constructing empty Prefix."); }
Prefix::Prefix (ClientMessageIn const & msg)
Constructor.
Definition at line 62 of file Prefix.cc.
References ClientMessageIn::client_session(), MessageIn::has_prefix(), and MessageIn::prefix_str().
{
  if (msg.has_prefix())
    init(msg.client_session(), msg.prefix_str());
}
Prefix::Prefix (ServerMessageIn const & msg)
Constructor.
Definition at line 56 of file Prefix.cc.
References MessageIn::has_prefix(), MessageIn::prefix_str(), and ServerMessageIn::server_session().
{
  if (msg.has_prefix())
    init(msg.server_session(), msg.prefix_str());
}
Prefix::Prefix (ServerSession & server_session, std::string const & prefix) [inline]
Constructor.
Definition at line 41 of file Prefix.h.
{ init(server_session, prefix); }
Prefix::Prefix (ClientSession & client_session, std::string const & prefix) [inline]
Constructor.
Definition at line 43 of file Prefix.h.
{ init(client_session, prefix); }
Prefix::Prefix (boost::shared_ptr< Nick > const & nick) [inline, explicit]
Constructor.
Definition at line 45 of file Prefix.h.
References ASSERT, and debug::channels::dc::objects.
: M_nick(nick) { ASSERT(nick.get()); Dout(dc::objects, "Constructing Prefix from " << nick); }
Prefix::Prefix (std::string const & fixed_prefix_str) [inline]
Constructor.
Definition at line 47 of file Prefix.h.
References debug::channels::dc::objects.
: M_server_name(fixed_prefix_str) { Dout(dc::objects, "Constructing Prefix from fixed string \"" << fixed_prefix_str << "\"."); }
Prefix::Prefix (Prefix const & prefix) [inline]
Constructor.
Definition at line 49 of file Prefix.h.
References debug::channels::dc::objects.
: M_nick(prefix.M_nick), M_server_name(prefix.M_server_name) { Dout(dc::objects, "Copy-constructing Prefix from " << prefix); }
Prefix::~Prefix () [inline]
Destructor.
Definition at line 51 of file Prefix.h.
References debug::channels::dc::objects.
{ Dout(dc::objects, "Destructing Prefix " << *this); }
Member Function Documentation
std::string Prefix::out_prefix (ClientSession const & client_session, bool allow_uninitialized = false) const
Return the clientside prefix.
Definition at line 97 of file Prefix.cc.
References hostname_bit, M_server_name, and username_bit.
Referenced by Identity::new_server_message_received(), and JustInTimePrefix::value_impl().
{
  if (!M_server_name.empty())
    return M_server_name;
  bool username_initialized = (M_nick->data().initialized() & username_bit);
  bool hostname_initialized = (M_nick->data().initialized() & hostname_bit);
  if (M_nick->is_me() && !(username_initialized && hostname_initialized))
    return M_nick->out_name(client_session);
  std::string result = M_nick->out_name(client_session);
  if (!username_initialized && allow_uninitialized)
    result += "!~unknown";
  else
  {
    result += '!';
    result += M_nick->data().username();
  }
  if (!hostname_initialized && allow_uninitialized)
    result += "@unknown.ircproxy.net";
  else
  {
    result += '@';
    result += M_nick->data().hostname();
  }
  return result;
}
std::string Prefix::out_prefix (ServerSession const & server_session, bool allow_uninitialized = false) const
Return the serverside prefix.
Definition at line 69 of file Prefix.cc.
References ASSERT, hostname_bit, M_server_name, and username_bit.
{
  if (!M_server_name.empty())
    return M_server_name;
  bool username_initialized = (M_nick->data().initialized() & username_bit);
  bool hostname_initialized = (M_nick->data().initialized() & hostname_bit);
  ASSERT(!M_nick->is_me() || !debug::secondary_connection);
  if (M_nick->is_me() && !(username_initialized && hostname_initialized))
    return M_nick->out_name(server_session);
  std::string result = M_nick->out_name(server_session);
  if (!username_initialized && allow_uninitialized)
    result += "!~unknown";
  else
  {
    result += '!';
    result += M_nick->data().username();
  }
  if (!hostname_initialized && allow_uninitialized)
    result += "@unknown.ircproxy.net";
  else
  {
    result += '@';
    result += M_nick->data().hostname();
  }
  return result;
}
bool Prefix::empty (void) const [inline]
Return true if there is no prefix.
Definition at line 62 of file Prefix.h.
References M_server_name.
Referenced by Channel::new_client_message_received(), and operator<<().
{ return M_nick.get() == NULL && M_server_name.empty(); }
boost::shared_ptr<Nick> Prefix::get_nick (void) [inline]
Return shared pointer to underlying nick.
Definition at line 65 of file Prefix.h.
Referenced by Channel::new_client_message_received(), Identity::new_server_message_received(), and Channel::new_server_message_received().
{ return M_nick; }
boost::shared_ptr<Nick const> Prefix::get_nick (void) const [inline]
Return shared pointer to underlying nick constant.
Definition at line 68 of file Prefix.h.
{ return M_nick; }
Member Data Documentation
std::string Prefix::M_server_name [private]
The underlying Nick, if it's a user.
Definition at line 32 of file Prefix.h.
Referenced by empty(), and out_prefix().
The documentation for this class was generated from the following files:
Prefix.h
Prefix.cc
Copyright © 2005-2007 Carlo Wood. All rights reserved.