ircproxy The Ultimate Cyborg
Watched< T > Class Template Reference
#include <Watched.h>
Detailed Description
template<typename T>
class Watched< T >
A wrapper class for arbitrary objects of type T that need to be watched.
Definition at line 74 of file Watched.h.
Public Member Functions
Watched (char const *name)
Construct a Watched instance with debug name name.
Watched (char const *name, T const &value)
Construct a Watched instance with debug name name and value value.
Watched (Watched const &b)
Copy constructor.
~Watched ()
Destructor.
void print_name (std::ostream &os) const
Print M_name to os for debugging purposes.
void add_event_server (boost::shared_ptr< ExpressionEventServer > const &event_server)
Add an event server to the event notification list.
void sub_event_server (ExpressionEventServer *event_server)
Remove an event server from the event notification list.
template<typename T2>
Watched & operator= (T2 const &b)
Templated assignment operator.
Watched & operator= (Watched const &b)
Assignment operator.
template<typename T2>
Watched & operator &= (T2 const &b)
Templated bitwise AND assignment operator.
Watched & operator &= (Watched const &b)
Bitwise AND assignment operator.
template<typename T2>
Watched & operator|= (T2 const &b)
Templated bitwise OR assignment operator.
Watched & operator|= (Watched const &b)
Bitwise OR assignment operator.
template<typename T2>
Watched & operator^= (T2 const &b)
Templated bitwise XOR assignment operator.
Watched & operator^= (Watched const &b)
Bitwise XOR assignment operator.
T operator~ (void)
Bitwise NOT operator.
WatchedExpression< T > operator* (void)
Dereference operator. Returns the Watched variable as Expression type.
T const & value (void) const
Return underlying value.
operator T const & ()
Cast operator. Return underlying value.
Private Member Functions
void changed_to (T const &b)
Inform listening Expression event servers that this variable changed value.
Private Attributes
T M_value
The underlying value.
bool M_being_destructed
Set when this object is being destructed.
std::set< boost::shared_ptr
< ExpressionEventServer > > M_event_servers
The event servers that watch expressions depending on this variable.
char const * M_name
A name for this object, for debugging purposes.
Constructor & Destructor Documentation
template<typename T> Watched< T >::Watched (char const * name) [inline, explicit]
Construct a Watched instance with debug name name.
Definition at line 86 of file Watched.h.
: M_being_destructed(false), M_name(name) { }
template<typename T> Watched< T >::Watched (char const * name, T const & value) [inline, explicit]
Construct a Watched instance with debug name name and value value.
Definition at line 88 of file Watched.h.
: M_value(value), M_being_destructed(false), M_name(name) { }
template<typename T> Watched< T >::Watched (Watched< T > const & b) [inline]
Copy constructor.
Definition at line 95 of file Watched.h.
                              : M_value(b.M_value), M_being_destructed(false)
        {
#ifdef CWDEBUG
          if (!b.M_event_servers.empty())
            Dout(dc::warning, "Copy-constructing a Watched<" <<
                type_info_of<T>().demangled_name() << "> that is being used by one or more ExpressionEventServer's");
#endif
        }
template<typename T> Watched< T >::~Watched () [inline]
Destructor.
Destructor. Inform listening Expression event servers that this variable is no longer watched.
Definition at line 305 of file Watched.h.
References Watched< T >::M_being_destructed, and Watched< T >::M_event_servers.
{
  M_being_destructed = true;
  for (std::set<boost::shared_ptr<ExpressionEventServer> >::iterator iter = M_event_servers.begin(); iter != M_event_servers.end();)
    (*iter++)->bool_destructed();
}
Member Function Documentation
template<typename T> void Watched< T >::print_name (std::ostream & os) const [inline]
Print M_name to os for debugging purposes.
Definition at line 108 of file Watched.h.
{ os << M_name; }
template<typename T> void Watched< T >::add_event_server (boost::shared_ptr< ExpressionEventServer > const & event_server) [inline]
Add an event server to the event notification list.
Definition at line 112 of file Watched.h.
    {
      M_event_servers.insert(event_server);
    }
template<typename T> void Watched< T >::sub_event_server (ExpressionEventServer * event_server) [inline]
Remove an event server from the event notification list.
Definition at line 118 of file Watched.h.
    {
      if (M_being_destructed)
        return;
      std::set<boost::shared_ptr<ExpressionEventServer> >::iterator iter = M_event_servers.begin();
      while (iter != M_event_servers.end())
      {
        if ((*iter).get() == event_server)
          break;
        ++iter;
      }
      ASSERT(iter != M_event_servers.end());
      M_event_servers.erase(iter);
    }
template<typename T> template<typename T2> Watched& Watched< T >::operator= (T2 const & b) [inline]
Templated assignment operator.
Definition at line 135 of file Watched.h.
    {
      T previous_value(M_value);
      M_value = b;
      if (M_value != previous_value)
        changed_to(M_value);
      return *this;
    }
template<typename T> Watched& Watched< T >::operator= (Watched< T > const & b) [inline]
Assignment operator.
Definition at line 145 of file Watched.h.
    {
      if (M_value != b.M_value)
        changed_to(b.M_value);
      return *this;
    }
template<typename T> template<typename T2> Watched& Watched< T >::operator &= (T2 const & b) [inline]
Templated bitwise AND assignment operator.
Definition at line 154 of file Watched.h.
    {
      T previous_value(M_value);
      M_value &= b;
      if (M_value != previous_value)
        changed_to(M_value);
      return *this;
    }
template<typename T> Watched& Watched< T >::operator &= (Watched< T > const & b) [inline]
Bitwise AND assignment operator.
Definition at line 164 of file Watched.h.
    {
      T previous_value(M_value);
      M_value &= b.M_value;
      if (M_value != previous_value)
        changed_to(M_value);
      return *this;
    }
template<typename T> template<typename T2> Watched& Watched< T >::operator|= (T2 const & b) [inline]
Templated bitwise OR assignment operator.
Definition at line 175 of file Watched.h.
    {
      T previous_value(M_value);
      M_value |= b;
      if (M_value != previous_value)
        changed_to(M_value);
      return *this;
    }
template<typename T> Watched& Watched< T >::operator|= (Watched< T > const & b) [inline]
Bitwise OR assignment operator.
Definition at line 185 of file Watched.h.
    {
      T previous_value(M_value);
      M_value |= b.M_value;
      if (M_value != previous_value)
        changed_to(M_value);
      return *this;
    }
template<typename T> template<typename T2> Watched& Watched< T >::operator^= (T2 const & b) [inline]
Templated bitwise XOR assignment operator.
Definition at line 196 of file Watched.h.
    {
      T previous_value(M_value);
      M_value ^= b;
      if (M_value != previous_value)
        changed_to(M_value);
      return *this;
    }
template<typename T> Watched& Watched< T >::operator^= (Watched< T > const & b) [inline]
Bitwise XOR assignment operator.
Definition at line 206 of file Watched.h.
    {
      T previous_value(M_value);
      M_value ^= b.M_value;
      if (M_value != previous_value)
        changed_to(M_value);
      return *this;
    }
template<typename T> T Watched< T >::operator~ (void) [inline]
Bitwise NOT operator.
Definition at line 216 of file Watched.h.
{ return ~M_value; }
template<typename T> WatchedExpression<T> Watched< T >::operator* (void) [inline]
Dereference operator. Returns the Watched variable as Expression type.
Definition at line 219 of file Watched.h.
{ return WatchedExpression<T>(*this); }
template<typename T> T const& Watched< T >::value (void) const [inline]
Return underlying value.
Definition at line 222 of file Watched.h.
Referenced by AuthState::auth_ping_argument(), operator &(), operator!=(), operator==(), operator>(), operator>=(), operator^(), and operator|().
{ return M_value; }
template<typename T> Watched< T >::operator T const & () [inline]
Cast operator. Return underlying value.
Definition at line 225 of file Watched.h.
{ return M_value; }
template<typename T> void Watched< T >::changed_to (T const & b) [inline, private]
Inform listening Expression event servers that this variable changed value.
Definition at line 294 of file Watched.h.
References Watched< T >::M_event_servers, and Watched< T >::M_value.
Referenced by Watched< UserModeMask >::operator &=(), Watched< UserModeMask >::operator=(), Watched< UserModeMask >::operator^=(), and Watched< UserModeMask >::operator|=().
{
  M_value = b;
  std::set<boost::shared_ptr<ExpressionEventServer> >::iterator iter = M_event_servers.begin();
  // The call to bool_changed can remove iter from the set<>. Therefore increment iter before calling bool_changed.
  while (iter != M_event_servers.end())
    (*iter++)->bool_changed();
}
Member Data Documentation
template<typename T> T Watched< T >::M_value [private]
The underlying value.
Definition at line 76 of file Watched.h.
Referenced by Watched< T >::changed_to(), Watched< UserModeMask >::operator &=(), Watched< UserModeMask >::operator UserModeMaskconst &(), Watched< UserModeMask >::operator=(), Watched< UserModeMask >::operator^=(), Watched< UserModeMask >::operator|=(), Watched< UserModeMask >::operator~(), and Watched< UserModeMask >::value().
template<typename T> bool Watched< T >::M_being_destructed [private]
Set when this object is being destructed.
Definition at line 77 of file Watched.h.
Referenced by Watched< UserModeMask >::sub_event_server(), and Watched< T >::~Watched().
template<typename T> std::set<boost::shared_ptr<ExpressionEventServer> > Watched< T >::M_event_servers [private]
The event servers that watch expressions depending on this variable.
Definition at line 78 of file Watched.h.
Referenced by Watched< UserModeMask >::add_event_server(), Watched< T >::changed_to(), Watched< UserModeMask >::sub_event_server(), and Watched< T >::~Watched().
template<typename T> char const* Watched< T >::M_name [private]
A name for this object, for debugging purposes.
Definition at line 80 of file Watched.h.
The documentation for this class was generated from the following file:
Watched.h
Copyright © 2005-2007 Carlo Wood. All rights reserved.