ircproxy The Ultimate Cyborg
debug_ostream_operators.cc File Reference
Detailed Description
This file contains the implementation of ostream inserter operators used for debugging.
Definition in file debug_ostream_operators.cc.
#include "sys.h"
#include <iostream>
#include <libcw/support.h>
#include "debug.h"
#include <libcwd/buf2str.h>
#include <libcwd/cwprint.h>
#include "casereturnstr.h"
#include "PersistXML.h"
#include "Network.h"
#include "MessageIn.h"
#include "UserAnswer.h"
#include "Identity.h"
#include "IdentityReference.h"
#include "Authentication.h"
#include "Channel.h"
#include "Nick.h"
#include "ClientSession.h"
#include "QuestionTarget.h"
#include "NoticeTarget.h"
#include "ServerSession.h"
#include "DestructEvent.h"
#include "ServerConnection.h"
#include "Expression.h"
#include "keys.h"
#include "Matcher.h"
#include "Prefix.h"
#include "JustInTime.h"
#include "PseudoMessageEvent.h"
#include "Member.h"
#include "WhoRequest.h"
Namespaces
namespace debug
Functions
char const * debug::state_nt_name (state_nt state)
Return a string literal representing the name of the state_nt state.
char const * debug::openmode_name (PersistXML::openmode_type openmode)
Return a string literal representing the name of the PersistXML::openmode_type openmode.
char const * debug::match0_type_name (match0_type mt)
Return a string literal representing the name of the match0_type mt.
char const * debug::match1_type_name (match1_type mt)
Return a string literal representing the name of the match1_type mt.
char const * debug::command_name (int command)
Return a string literal representing the name of the int command.
std::ostream & operator<< (std::ostream &os, state_nt state)
For debugging purposes. Write a state_nt to os.
std::ostream & operator<< (std::ostream &os, PersistXML::openmode_type openmode)
For debugging purposes. Write a PersistXML::openmode to os.
std::ostream & operator<< (std::ostream &os, match0_type mt)
For debugging purposes. Write a match0_type to os.
std::ostream & operator<< (std::ostream &os, match1_type mt)
For debugging purposes. Write a match1_type to os.
std::ostream & operator<< (std::ostream &os, Application const &)
For debugging purposes. Write an Application to os.
std::ostream & operator<< (std::ostream &os, Network const &network)
For debugging purposes. Write a Network to os.
std::ostream & operator<< (std::ostream &os, Server const &server)
For debugging purposes. Write a Server to os.
std::ostream & operator<< (std::ostream &os, MessageIn const &msg)
For debugging purposes. Write a MessageIn to os.
std::ostream & operator<< (std::ostream &os, ClientMessageIn const &msg)
For debugging purposes. Write a ClientMessageIn to os.
std::ostream & operator<< (std::ostream &os, ServerMessageIn const &msg)
For debugging purposes. Write a ServerMessageIn to os.
std::ostream & operator<< (std::ostream &os, UserAnswerRequestData const &request_data)
For debugging purposes. Write a UserAnswerRequestData to os.
std::ostream & operator<< (std::ostream &os, UserAnswer const &answer)
For debugging purposes. Write a UserAnswer to os.
std::ostream & operator<< (std::ostream &os, UserAnswerEventRequestBase const &request)
For debugging purposes. Write a UserAnswerEventRequestBase to os.
std::ostream & operator<< (std::ostream &os, Identity const &identity)
For debugging purposes. Write a Identity to os.
std::ostream & operator<< (std::ostream &os, ServerConnection const &server_connection)
For debugging purposes. Write a ServerConnection to os.
std::ostream & operator<< (std::ostream &os, IdentityReference const &identity_reference)
For debugging purposes. Write a IdentityReference to os.
std::ostream & operator<< (std::ostream &os, Authentication const &authentication)
For debugging purposes. Write a Authentication to os.
std::ostream & operator<< (std::ostream &os, Channel const &channel)
For debugging purposes. Write a Channel to os.
std::ostream & operator<< (std::ostream &os, Nick const &nick)
For debugging purposes. Write a Nick to os.
std::ostream & operator<< (std::ostream &os, ClientSession const &client_session)
For debugging purposes. Write a ClientSession to os.
std::ostream & operator<< (std::ostream &os, QuestionTarget const &question_target)
For debugging purposes. Write a QuestionTarget to os.
std::ostream & operator<< (std::ostream &os, NoticeTarget const &notice_target)
Print debug info for NoticeTarget instance notice_target.
std::ostream & operator<< (std::ostream &os, ServerSession const &server_session)
For debugging purposes. Write a ServerSession to os.
std::ostream & operator<< (std::ostream &os, Target const &target)
For debugging purposes. Write a Target to os.
std::ostream & operator<< (std::ostream &os, PseudoMessageEventRequestData const &request_data)
For debugging purposes. Write a PseudoMessageEventRequestData to os.
std::ostream & operator<< (std::ostream &os, MessageOutData const &data)
For debugging purposes. Write a MessageOutData to os.
std::ostream & operator<< (std::ostream &os, MessageOut const &message)
For debugging purposes. Write a MessageOut to os.
std::ostream & operator<< (std::ostream &os, Priority const &priority)
For debugging purposes. Write a Priority to os.
std::ostream & operator<< (std::ostream &os, timeval const &time)
For debugging purposes. Write a timeval to os.
std::ostream & operator<< (std::ostream &os, regex_t const &)
For debugging purposes. Write a regex_t to os.
std::ostream & operator<< (std::ostream &os, ExpressionEventType const &event_type)
For debugging purposes. Write a ExpressionEventType to os.
std::ostream & operator<< (std::ostream &os, ExpressionEventServer const &expression_event_server)
For debugging purposes. Write a ExpressionEventServer to os.
std::ostream & operator<< (std::ostream &os, Bool const &b)
For debugging purposes. Write a Bool to os.
std::ostream & operator<< (std::ostream &os, Matcher const &matcher)
For debugging purposes. Write a Matcher to os.
std::ostream & operator<< (std::ostream &os, MatchRequestList const &match_request_list)
For debugging purposes. Write a MatchRequestList to os.
std::ostream & operator<< (std::ostream &os, MatchRequest const &match_request)
For debugging purposes. Write a MatchRequest to os.
std::ostream & operator<< (std::ostream &os, MatcherEventType const &event_type)
For debugging purposes. Write a MatcherEventType to os.
std::ostream & operator<< (std::ostream &os, MatcherEventRequestBase const &request)
For debugging purposes. Write a MatcherEventRequestBase to os.
std::ostream & operator<< (std::ostream &os, Prefix const &prefix)
For debugging purposes. Write a Prefix to os.
std::ostream & operator<< (std::ostream &os, Member const &member)
Print debug info for Member instance member.
std::ostream & operator<< (std::ostream &os, WhoOptions const &options)
Print debug info for WhoOptions instance who_options.
std::ostream & operator<< (std::ostream &os, WhoRequest const &who_request)
Print debug info for WhoRequest instance who_request.
std::ostream & operator<< (std::ostream &os, SignalType const &signal)
Print debug info for SignalType instance signal.
std::ostream & operator<< (std::ostream &os, ServerVersion const &server_version)
Print debug info for ServerVersion instance server_version.
std::ostream & operator<< (std::ostream &os, AuthState const &auth_state)
Print debug info for AuthState instance auth_state.
Function Documentation
std::ostream& operator<< (std::ostream & os, state_nt state)
For debugging purposes. Write a state_nt to os.
Definition at line 169 of file debug_ostream_operators.cc.
References debug::state_nt_name().
{
  return os << debug::state_nt_name(state);
}
std::ostream& operator<< (std::ostream & os, PersistXML::openmode_type openmode)
For debugging purposes. Write a PersistXML::openmode to os.
Definition at line 175 of file debug_ostream_operators.cc.
References debug::openmode_name().
{
  return os << debug::openmode_name(openmode);
}
std::ostream& operator<< (std::ostream & os, match0_type mt)
For debugging purposes. Write a match0_type to os.
Definition at line 181 of file debug_ostream_operators.cc.
References debug::match0_type_name().
{
  return os << debug::match0_type_name(mt);
}
std::ostream& operator<< (std::ostream & os, match1_type mt)
For debugging purposes. Write a match1_type to os.
Definition at line 187 of file debug_ostream_operators.cc.
References debug::match1_type_name().
{
  return os << debug::match1_type_name(mt);
}
std::ostream& operator<< (std::ostream & os, Application const &)
For debugging purposes. Write an Application to os.
Print debug info for Application instance application.
Definition at line 193 of file debug_ostream_operators.cc.
{
  return os << "(application)";
}
std::ostream& operator<< (std::ostream & os, Network const & network)
For debugging purposes. Write a Network to os.
Print debug info for Network instance network.
Definition at line 199 of file debug_ostream_operators.cc.
References Network::domain(), Network::has_domain(), Network::name(), and Network::servers().
{
  os << "{name:" << network.name();
  if (network.has_domain())
    os << ", domain:" << network.domain();
  os << ", servers:{";
  Network::servers_type::const_iterator iter = network.servers().begin();
  if (iter != network.servers().end())
  {
    os << *iter;
    while (++iter != network.servers().end())
      os << ", " << *iter;
  }
  return os << "}}";
}
std::ostream& operator<< (std::ostream & os, Server const & server)
For debugging purposes. Write a Server to os.
Print debug info for Server instance server.
Definition at line 216 of file debug_ostream_operators.cc.
References Server::get_irc_name(), Server::hostname(), Server::last_connection_event(), and Server::ports().
{
  os << "{hostname:" << server.hostname() <<
        ", irc_name:" << server.get_irc_name() <<
        ", ports:{";
  Server::ports_type::const_iterator iter = server.ports().begin();
  if (iter != server.ports().end())
  {
    os << *iter;
    while (++iter != server.ports().end())
      os << ", " << *iter;
  }
  os << "}, last_connection_event:" << server.last_connection_event();
  return os << '}';
}
std::ostream& operator<< (std::ostream & os, MessageIn const & msg)
For debugging purposes. Write a MessageIn to os.
Print debug info for MessageIn instance msg.
Definition at line 233 of file debug_ostream_operators.cc.
References MessageIn::command_part(), MessageIn::has_prefix(), MessageIn::key(), MessageIn::params(), MessageIn::prefix_part(), and MessageIn::uninitialized().
{
  os << '{';
  if (msg.uninitialized())
    return os << "<uninitialized>}";
  if (msg.has_prefix())
    os << "prefix:\"" << libcwd::buf2str(msg.prefix_part().start(), msg.prefix_part().len()) << "\", ";
  if (msg.command_part().start())
    os << "command:\"" <<
        libcwd::buf2str(msg.command_part().start(), msg.command_part().len()) << "\" [key:" << msg.key() << "]";
  os << ", params:{";
  MessageIn::params_type::const_iterator iter = msg.params().begin();
  if (iter != msg.params().end())
  {
    os << *iter;
    while(++iter != msg.params().end())
      os << ", " << *iter;
  }
  return os << "}}";
}
std::ostream& operator<< (std::ostream & os, ClientMessageIn const & msg)
For debugging purposes. Write a ClientMessageIn to os.
Print debug info for ClientMessageIn instance msg.
Definition at line 255 of file debug_ostream_operators.cc.
References ClientMessageIn::client_session().
{
  return os << "{client_session:" << msg.client_session() <<
     "; MessageIn:" << *static_cast<MessageIn const*>(&msg) << '}';
}
std::ostream& operator<< (std::ostream & os, ServerMessageIn const & msg)
For debugging purposes. Write a ServerMessageIn to os.
Print debug info for ServerMessageIn instance msg.
Definition at line 262 of file debug_ostream_operators.cc.
References ServerMessageIn::server_session().
{
  return os << "{server_session:" << msg.server_session() <<
     "; MessageIn:" << *static_cast<MessageIn const*>(&msg) << '}';
}
std::ostream& operator<< (std::ostream & os, UserAnswerRequestData const & request_data)
For debugging purposes. Write a UserAnswerRequestData to os.
Print debug info for UserAnswerRequestData instance request_data.
Definition at line 269 of file debug_ostream_operators.cc.
References UserAnswerRequestData::client_session(), and UserAnswerRequestData::question().
{
  return os << '{' << "question:\"" << request_data.question() << "\" [client_session:" << request_data.client_session() << "]}";
}
std::ostream& operator<< (std::ostream & os, UserAnswer const & answer)
For debugging purposes. Write a UserAnswer to os.
Print debug info for UserAnswer instance answer.
Write UserAnswer answer to os.
Definition at line 275 of file debug_ostream_operators.cc.
References UserAnswer::M_answer, UserAnswer::M_client_session, and UserAnswer::M_target_name.
{
  os << '{' << "answer:\"" << answer.M_answer;
  os << "\", client_session:" << answer.M_client_session;
  os << ", target:\"" << answer.M_target_name;
  os << "\"}";
  return os;
}
std::ostream& operator<< (std::ostream & os, UserAnswerEventRequestBase const & request)
For debugging purposes. Write a UserAnswerEventRequestBase to os.
Print debug info for UserAnswerEventRequestBase instance request.
Write UserAnswerEventRequestBase request to os.
Definition at line 285 of file debug_ostream_operators.cc.
References UserAnswerEventRequestBase::M_request_data, and UserAnswerEventRequestBase::M_target.
{
  os << "{request_data:" << request.M_request_data;
  if (request.M_target.get())
    os << ", target:" << *request.M_target.get();
  return os << '}';
}
std::ostream& operator<< (std::ostream & os, Identity const & identity)
For debugging purposes. Write a Identity to os.
Print debug info for Identity instance identity.
Definition at line 294 of file debug_ostream_operators.cc.
References Identity::M_authentication, Identity::M_authpass, Identity::M_client_session, Identity::M_hostname, Identity::M_ident, Identity::M_key, Identity::M_network_name, Identity::M_private_network, and Identity::M_real_name.
{
  os << "{key:" << identity.M_key;
#ifdef VERBOSE_IDENTITY
#ifdef PRINT_AUTHENTICATION
  if (identity.M_authentication.get())
    os << ", authentication:" << *identity.M_authentication.get();
  os << ", server_connection:" << identity.M_server_connection;
  if (!identity.M_authpass.empty())
    os << ", authpass:" << identity.M_authpass;
#endif
  os << ", private_network:" << identity.M_private_network;
  if (identity.M_client_session)
    os << ", client_session:" << *identity.M_client_session;
  os << ", ident:\"" << identity.M_ident <<
        "\", hostname:\"" << identity.M_hostname <<
        "\", real_name:\"" << identity.M_real_name <<
        "\", network_name:\"" << identity.M_network_name << '"';
#endif
  os << '}';
  return os;
}
std::ostream& operator<< (std::ostream & os, ServerConnection const & server_connection)
For debugging purposes. Write a ServerConnection to os.
Print debug info for ServerConnection instance server_connection.
Definition at line 318 of file debug_ostream_operators.cc.
References ServerConnection::connect_delay(), ServerConnection::has_server_session(), ServerConnection::is_connected(), ServerConnection::M_server, ServerConnection::reconnect(), ServerConnection::secondary_connection(), ServerConnection::server_session(), ServerConnection::state(), ServerConnection::timed_out(), and ServerConnection::timed_out_count().
{
  os << "{server:";
  if (server_connection.M_server.get())
    os << *server_connection.M_server.get();
  else
    os << "<none>";
  os << "; server_session:";
  if (server_connection.has_server_session())
    os << server_connection.server_session();
  else
    os << "<NULL>";
  os << "; reconnect:";
  if (server_connection.reconnect())
    os << "true";
  else
    os << "false";
  os << "; connected:";
  if (server_connection.is_connected())
    os << "true";
  else
    os << "false";
  os << "; state:" << server_connection.state();
  os << "; connect_delay:" << server_connection.connect_delay();
  os << "; timed_out:";
  if (server_connection.timed_out())
    os << "true";
  else
    os << "false";
  os << "; timed_out_count:" << server_connection.timed_out_count();
  os << "; secondary_connection:" << server_connection.secondary_connection();
  return os << '}';
}
std::ostream& operator<< (std::ostream & os, IdentityReference const & identity_reference)
For debugging purposes. Write a IdentityReference to os.
Print debug info for IdentityReference instance identity_reference.
Definition at line 353 of file debug_ostream_operators.cc.
References IdentityReference::identity(), and Identity::key().
{
  os << "[identity:" << identity_reference.identity().key() << ']';
  return os;
}
std::ostream& operator<< (std::ostream & os, Authentication const & authentication)
For debugging purposes. Write a Authentication to os.
Print debug info for Authentication instance authentication.
Definition at line 360 of file debug_ostream_operators.cc.
References Authentication::M_ident, Authentication::M_realname, Authentication::M_received_nick, Authentication::M_received_user, Authentication::M_server_pass, and Authentication::M_service_pass.
{
  os << "{server_pass:" <<
#ifdef PRINT_AUTHENTICATION
      authentication.M_server_pass
#else
      "***"
#endif
      ;
  os << ", service_pass:" <<
#ifdef PRINT_AUTHENTICATION
      authentication.M_service_pass
#else
      "***"
#endif
      ;
  os << ", ident:" << authentication.M_ident;
  os << ", realname:" << authentication.M_realname;
  os << ", received_nick:" << authentication.M_received_nick;
  os << ", received_user:" << authentication.M_received_user;
  return os << ' ' << static_cast<IdentityReference const&>(authentication) << '}';
}
std::ostream& operator<< (std::ostream & os, Channel const & channel)
For debugging purposes. Write a Channel to os.
Print debug info for Channel instance channel.
Definition at line 384 of file debug_ostream_operators.cc.
{
  os << "{Channel " << static_cast<Target const&>(channel);
  return os << '}';
}
std::ostream& operator<< (std::ostream & os, Nick const & nick)
For debugging purposes. Write a Nick to os.
Print debug info for Nick instance nick.
Definition at line 391 of file debug_ostream_operators.cc.
{
  os << "{Nick " << static_cast<Target const&>(nick);
  return os;
}
std::ostream& operator<< (std::ostream & os, ClientSession const & client_session)
For debugging purposes. Write a ClientSession to os.
Print debug info for ClientSession instance client_session.
Definition at line 398 of file debug_ostream_operators.cc.
References IdentityReference::has_identity().
{
  os << "{ClientSession ";
  if (client_session.has_identity())
    os << static_cast<IdentityReference const&>(client_session);
  else
    os << "with no Identity";
  return os << '}';
}
std::ostream& operator<< (std::ostream & os, QuestionTarget const & question_target)
For debugging purposes. Write a QuestionTarget to os.
Print debug info for QuestionTarget instance question_target.
Definition at line 409 of file debug_ostream_operators.cc.
{
  os << "{QuestionTarget " << static_cast<Target const&>(question_target) << '}';
  return os;
}
std::ostream& operator<< (std::ostream & os, NoticeTarget const & notice_target)
Print debug info for NoticeTarget instance notice_target.
Definition at line 415 of file debug_ostream_operators.cc.
{
  os << "{NoticeTarget " << static_cast<Target const&>(notice_target) << '}';
  return os;
}
std::ostream& operator<< (std::ostream & os, ServerSession const & server_session)
For debugging purposes. Write a ServerSession to os.
Print debug info for ServerSession instance server_session.
Definition at line 422 of file debug_ostream_operators.cc.
{
  os << "{ServerSession ";
  os << static_cast<IdentityReference const&>(server_session);
  return os << '}';
}
std::ostream& operator<< (std::ostream & os, Target const & target)
For debugging purposes. Write a Target to os.
Print debug info for Target instance target.
Definition at line 430 of file debug_ostream_operators.cc.
{
  //os << "{serverside_name:\"" << target.serverside_name() << "\", clientside_name:\"" << target.clientside_name() << "\", network:" << target.network().name();
  os << "{FIXME";
  return os << '}';
}
std::ostream& operator<< (std::ostream & os, PseudoMessageEventRequestData const & request_data)
For debugging purposes. Write a PseudoMessageEventRequestData to os.
Print debug info for PseudoMessageEventRequestData instance request_data.
Definition at line 438 of file debug_ostream_operators.cc.
{
  os << "{PseudoMessageEventRequestData FIXME";
  return os << '}';
}
std::ostream& operator<< (std::ostream & os, MessageOutData const & data)
For debugging purposes. Write a MessageOutData to os.
Print debug info for MessageOutData instance data.
Definition at line 445 of file debug_ostream_operators.cc.
References MessageOutData::M_priority, and MessageOutData::M_tokens.
{
  os << "{message:";
#if 0
  for (std::vector<boost::shared_ptr<JustInTimeToken> >::const_iterator iter = data.M_tokens.begin(); iter != data.M_tokens.end(); ++iter)
  {
    std::string str1((*iter)->value(serverside));
    std::string str2((*iter)->value(clientside));
    if (str1 == str2)
      os << '{' << libcwd::buf2str(str1.data(), str1.length()) << '}';
    else
      os << "{serverside:" << libcwd::buf2str(str1.data(), str1.length()) << ", clientside:" << libcwd::buf2str(str2.data(), str2.length()) << '}';
  }
#else
  os << "FIXME";
#endif
  os << "}, priority:" << data.M_priority;
  return os << '}';
}
std::ostream& operator<< (std::ostream & os, MessageOut const & message)
For debugging purposes. Write a MessageOut to os.
Print debug info for MessageOut instance message.
Definition at line 466 of file debug_ostream_operators.cc.
References MessageOut::M_data.
{
  os << "{data:" << *message.M_data;
  return os << '}';
}
std::ostream& operator<< (std::ostream & os, Priority const & priority)
For debugging purposes. Write a Priority to os.
Print debug info for Priority instance priority.
Definition at line 473 of file debug_ostream_operators.cc.
{
  // FIXME
  os << "{<priority>";
  return os << '}';
}
std::ostream& operator<< (std::ostream & os, timeval const & time)
For debugging purposes. Write a timeval to os.
Print debug info for timeval instance time.
Definition at line 481 of file debug_ostream_operators.cc.
{
  return os << "{tv_sec:" << time.tv_sec << ", tv_usec:" << time.tv_usec << '}';
}
std::ostream& operator<< (std::ostream & os, regex_t const &)
For debugging purposes. Write a regex_t to os.
Print debug info for regex_t instance regex.
Definition at line 487 of file debug_ostream_operators.cc.
{
  os << "{<compiled>";
  return os << '}';
}
std::ostream& operator<< (std::ostream & os, ExpressionEventType const & event_type)
For debugging purposes. Write a ExpressionEventType to os.
Definition at line 494 of file debug_ostream_operators.cc.
References ExpressionEventType::M_expression, and ExpressionEventType::M_expression_value.
{
  os << "{expression_value:" << (event_type.M_expression_value ? "true" : "false");
  os << ", expression:\"";
  event_type.M_expression->print_on(os);
  return os << "\"}";
}
std::ostream& operator<< (std::ostream & os, ExpressionEventServer const & expression_event_server)
For debugging purposes. Write a ExpressionEventServer to os.
Definition at line 503 of file debug_ostream_operators.cc.
References ExpressionEventServer::M_evaluation, ExpressionEventServer::M_expression, and ExpressionEventServer::M_ok.
{
  os << "{expression:\"";
  expression_event_server.M_expression->print_on(os);
  os << "\", ok:" << (expression_event_server.M_ok ? "true" : "false");
  os << ", evaluation:" << (expression_event_server.M_evaluation ? "true" : "false");
  return os << '}';
}
std::ostream& operator<< (std::ostream & os, Bool const & b)
For debugging purposes. Write a Bool to os.
Write Bool b to os.
Definition at line 513 of file debug_ostream_operators.cc.
References Bool::M_name, and Bool::M_value.
{
  return os << "{value:" << b.M_value << "; name:\"" << b.M_name << "\"}";
}
std::ostream& operator<< (std::ostream & os, Matcher const & matcher)
For debugging purposes. Write a Matcher to os.
Print debug info for Matcher instance matcher.
Definition at line 519 of file debug_ostream_operators.cc.
References Matcher::print_on(), and Matcher::print_type_on().
{
  os << '{';
  matcher.print_type_on(os);
  os << ' ';
  matcher.Matcher::print_on(os);
  os << ", ";
  matcher.print_on(os);
  return os << '}';
}
std::ostream& operator<< (std::ostream & os, MatchRequestList const & match_request_list)
For debugging purposes. Write a MatchRequestList to os.
Print debug info for MatchRequestList instance match_request_list.
Definition at line 531 of file debug_ostream_operators.cc.
References debug::command_name(), MatchRequestList::M_command, and MatchRequestList::M_conditions.
{
  os << "{command: ";
  if (match_request_list.M_command < 0)
    os << debug::command_name(match_request_list.M_command);
  else
    os << match_request_list.M_command;
  os << ", conditions:{";
  std::multiset<boost::shared_ptr<Matcher> >::const_iterator iter = match_request_list.M_conditions.begin();
  if (iter != match_request_list.M_conditions.end())
  {
    os << **iter;
    while(++iter != match_request_list.M_conditions.end())
      os << ", " << **iter;
  }
  return os << "}}";
}
std::ostream& operator<< (std::ostream & os, MatchRequest const & match_request)
For debugging purposes. Write a MatchRequest to os.
Print debug info for MatchRequest instance match_request.
Definition at line 550 of file debug_ostream_operators.cc.
References MatchRequest::match_request_list().
{
  os << "{match_request_list:" << match_request.match_request_list();
  return os << '}';
}
std::ostream& operator<< (std::ostream & os, MatcherEventType const & event_type)
For debugging purposes. Write a MatcherEventType to os.
Print debug info for MatcherEventType instance event_type.
Definition at line 557 of file debug_ostream_operators.cc.
References MatcherEventType::message().
{
  os << "{message:" << event_type.message();
  return os << '}';
}
std::ostream& operator<< (std::ostream & os, MatcherEventRequestBase const & request)
For debugging purposes. Write a MatcherEventRequestBase to os.
Write MatcherEventRequestBase request to os.
Definition at line 564 of file debug_ostream_operators.cc.
References MatcherEventRequestBase::M_request_data.
{
  os << "{request_data:" << request.M_request_data;
  return os << '}';
}
std::ostream& operator<< (std::ostream & os, Prefix const & prefix)
For debugging purposes. Write a Prefix to os.
Print debug info for Prefix instance prefix.
Definition at line 571 of file debug_ostream_operators.cc.
References Nick::data(), Prefix::empty(), NickData::hostname(), hostname_bit, NickData::initialized(), Prefix::nick(), Prefix::server_name(), NickData::username(), and username_bit.
{
  os << '{';
  if (prefix.empty())
    os << "Empty Prefix";
  else if (!prefix.server_name().empty())
    os << prefix.server_name();
  else
  {
#if 0
    if (prefix.nick()->serverside_name() == prefix.nick()->clientside_name())
      os << prefix.nick()->serverside_name();
    else
      os << "{serverside:" << prefix.nick()->serverside_name() << "; clientside:" << prefix.nick()->clientside_name() << '}';
#else
    os << "FIXME";
#endif
    os << '!';
    if ((prefix.nick()->data().initialized() & username_bit))
      os << prefix.nick()->data().username();
    else
      os << "<uninitialized>";
    os << '@';
    if ((prefix.nick()->data().initialized() & hostname_bit))
      os << prefix.nick()->data().hostname();
    else
      os << "<uninitialized>";
  }
  return os << '}';
}
std::ostream& operator<< (std::ostream & os, Member const & member)
Print debug info for Member instance member.
Definition at line 602 of file debug_ostream_operators.cc.
References Member::get_nick().
{
  os << '{';
  os << "nick:" << member.get_nick();
  return os << '}';
}
std::ostream& operator<< (std::ostream & os, WhoOptions const & options)
Print debug info for WhoOptions instance who_options.
Definition at line 609 of file debug_ostream_operators.cc.
References WhoOptions::str().
{
  return os << options.str();
}
std::ostream& operator<< (std::ostream & os, WhoRequest const & who_request)
Print debug info for WhoRequest instance who_request.
Definition at line 614 of file debug_ostream_operators.cc.
References WhoRequest::mask(), and WhoRequest::options().
{
  return os << "{mask:" << who_request.mask() << "; options:" << who_request.options() << '}';
}
std::ostream& operator<< (std::ostream & os, SignalType const & signal)
Print debug info for SignalType instance signal.
Definition at line 619 of file debug_ostream_operators.cc.
{
  return os << "{sig:" << signal.get_signal() << "; count:" << signal.get_count() << '}';
}
std::ostream& operator<< (std::ostream & os, ServerVersion const & server_version)
Print debug info for ServerVersion instance server_version.
Definition at line 624 of file debug_ostream_operators.cc.
{
  return os << libcwd::cwprint(server_version);
}
std::ostream& operator<< (std::ostream & os, AuthState const & auth_state)
Print debug info for AuthState instance auth_state.
Definition at line 629 of file debug_ostream_operators.cc.
{
  return os << libcwd::cwprint(auth_state);
}
Copyright © 2005-2007 Carlo Wood. All rights reserved.