ircproxy The Ultimate Cyborg
IRC_compare.h File Reference
Detailed Description
This file contains the declaration of the IRC string- and character compare functions.
Definition in file IRC_compare.h.
#include <cstddef>
#include <string>
#include "ircd_chattr.h"
Classes
struct IRC_less
Functor to compare strings with IRCStringCompare.
Functions
int IRCStringCompare (char c1, char c2)
Compare two IRC characters in a 'case insensitive' way.
bool IRC_compare (char c1, char c2)
Compare two IRC characters in a 'case insensitive' way.
int IRCStringCompare (char const *s1, char const *s2)
Compare two whole IRC strings in a 'case insensitive' way.
int IRCStringCompare (char const *s1, char const *s2, size_t count)
Compare the first count characters of two IRC strings in a 'case insensitive' way.
int IRCStringCompare (std::string const &s1, std::string const &s2)
Compare two whole IRC strings in a 'case insensitive' way.
int IRCStringCompare (std::string const &s1, std::string const &s2, size_t count)
Compare the first count characters of two IRC strings in a 'case insensitive' way.
int IRCStringCompare (std::string const &s1, char const *s2)
Compare two whole IRC strings in a 'case insensitive' way.
int IRCStringCompare (std::string const &s1, char const *s2, size_t count)
Compare the first count characters of two IRC strings in a 'case insensitive' way.
int IRCStringCompare (char const *s1, std::string const &s2)
Compare two whole IRC strings in a 'case insensitive' way.
int IRCStringCompare (char const *s1, std::string const &s2, size_t count)
Compare the first count characters of two IRC strings in a 'case insensitive' way.
Function Documentation
int IRCStringCompare (char c1, char c2) [inline]
Compare two IRC characters in a 'case insensitive' way.
Definition at line 29 of file IRC_compare.h.
{
  int lc1 = static_cast<unsigned char>(ToLower(c1));
  int lc2 = static_cast<unsigned char>(ToLower(c2));
  if (lc1 < lc2)
    return -1;
  if (lc1 > lc2)
    return 1;
  return 0;
}
bool IRC_compare (char c1, char c2) [inline]
Compare two IRC characters in a 'case insensitive' way.
Definition at line 43 of file IRC_compare.h.
{
  return static_cast<unsigned char>(ToLower(c1)) < static_cast<unsigned char>(ToLower(c2));
}
int IRCStringCompare (char const * s1, char const * s2)
Compare two whole IRC strings in a 'case insensitive' way.
Definition at line 25 of file IRC_compare.cc.
Referenced by ServerSession::detected_network(), ServerSession::found_network_name(), IRCStringCompare(), IRC_less::operator()(), and Identity::received_network_domain_answer().
{
  while (ToLower(*s1) == ToLower(*s2))
  {
    if (!*s1++)
      return 0;
    else
      ++s2;
  }
  return static_cast<unsigned char>(ToLower(*s1)) - static_cast<unsigned char>(ToLower(*s2));
}
int IRCStringCompare (char const * s1, char const * s2, size_t count)
Compare the first count characters of two IRC strings in a 'case insensitive' way.
Definition at line 37 of file IRC_compare.cc.
{
  if (count == 0)
    return 0;
  while (--count != 0 && ToLower(*s1) == ToLower(*s2))
  {
    if (!*s1++)
      return 0;
    else
      ++s2;
  }
  return static_cast<unsigned char>(ToLower(*s1)) - static_cast<unsigned char>(ToLower(*s2));
}
int IRCStringCompare (std::string const & s1, std::string const & s2) [inline]
Compare two whole IRC strings in a 'case insensitive' way.
Definition at line 57 of file IRC_compare.h.
References IRCStringCompare().
{
  return IRCStringCompare(s1.c_str(), s2.c_str());
}
int IRCStringCompare (std::string const & s1, std::string const & s2, size_t count) [inline]
Compare the first count characters of two IRC strings in a 'case insensitive' way.
Definition at line 65 of file IRC_compare.h.
References IRCStringCompare().
{
  return IRCStringCompare(s1.c_str(), s2.c_str(), count);
}
int IRCStringCompare (std::string const & s1, char const * s2) [inline]
Compare two whole IRC strings in a 'case insensitive' way.
Definition at line 71 of file IRC_compare.h.
References IRCStringCompare().
{
  return IRCStringCompare(s1.c_str(), s2);
}
int IRCStringCompare (std::string const & s1, char const * s2, size_t count) [inline]
Compare the first count characters of two IRC strings in a 'case insensitive' way.
Definition at line 79 of file IRC_compare.h.
References IRCStringCompare().
{
  return IRCStringCompare(s1.c_str(), s2, count);
}
int IRCStringCompare (char const * s1, std::string const & s2) [inline]
Compare two whole IRC strings in a 'case insensitive' way.
Definition at line 85 of file IRC_compare.h.
References IRCStringCompare().
{
  return IRCStringCompare(s1, s2.c_str());
}
int IRCStringCompare (char const * s1, std::string const & s2, size_t count) [inline]
Compare the first count characters of two IRC strings in a 'case insensitive' way.
Definition at line 93 of file IRC_compare.h.
References IRCStringCompare().
{
  return IRCStringCompare(s1, s2.c_str(), count);
}
Copyright © 2005-2007 Carlo Wood. All rights reserved.