ircproxy The Ultimate Cyborg
is_channel.h File Reference
Detailed Description
This file contains the definition of the is_channel functions.
Definition in file is_channel.h.
#include <string>
#include <cstring>
#include "debug.h"
Functions
bool is_channel (char const *name)
Returns true if name is a channel name.
bool is_channel (std::string const &name)
Returns true if name is a channel name.
bool is_server (char const *name)
Returns true if name is a server name.
bool is_server (std::string const &name)
Returns true if name is a server name.
bool is_nick (char const *name)
Returns true if name is a nick name.
bool is_nick (std::string const &name)
Returns true if name is a nick name.
Function Documentation
bool is_channel (char const * name) [inline]
Returns true if name is a channel name.
Definition at line 27 of file is_channel.h.
References ASSERT.
Referenced by Target::add_channel(), Target::clientside_get_channel(), ClientSession::create_private_target(), PrivateTarget::handle_command(), is_nick(), Matcher_noarg::match_impl(), QuestionTarget::new_client_message_received(), PrivateTarget::new_client_message_received(), Identity::new_client_message_received(), Identity::notice_target(), Target::serverside_add_channel(), Target::serverside_get_channel(), and Target::sub_channel().
{
  ASSERT(*name != 0);
  return *name == '#' || *name == '&' || (*name == '@' && name[1] == '#');
}
bool is_channel (std::string const & name) [inline]
Returns true if name is a channel name.
Definition at line 34 of file is_channel.h.
References ASSERT.
{
  ASSERT(!name.empty());
  char c = name[0];
  return c == '#' || c == '&' || (c == '@' && name[1] == '#');
}
bool is_server (char const * name) [inline]
Returns true if name is a server name.
Definition at line 42 of file is_channel.h.
Referenced by is_nick().
{
  return std::strchr(name, '.') != NULL;
}
bool is_server (std::string const & name) [inline]
Returns true if name is a server name.
Definition at line 48 of file is_channel.h.
{
  return name.find('.') != std::string::npos;
}
bool is_nick (char const * name) [inline]
Returns true if name is a nick name.
Definition at line 54 of file is_channel.h.
References is_channel(), and is_server().
Referenced by Target::add_joined_nick(), ClientSession::create_private_target(), Target::get_joined_nick(), ServerSession::get_nick(), and ClientSession::get_nick().
{
  return !is_channel(name) && !is_server(name);
}
bool is_nick (std::string const & name) [inline]
Returns true if name is a nick name.
Definition at line 60 of file is_channel.h.
References is_channel(), and is_server().
{
  return !is_channel(name) && !is_server(name);
}
Copyright © 2005-2007 Carlo Wood. All rights reserved.