ircproxy The Ultimate Cyborg
Priority.cc File Reference
Detailed Description
This file contains the implementation of class Priority.
Definition in file Priority.cc.
#include "sys.h"
#include "Priority.h"
Functions
Priority default_priority (int command)
Return the default priority for command.
Function Documentation
Priority default_priority (int command)
Return the default priority for command.
Definition at line 23 of file Priority.cc.
Referenced by ServerConnection::decode_ping(), Identity::new_client_message_received(), Channel::new_client_message_received(), ClientSession::new_client_nick_received(), ServerSession::new_message_received(), Identity::new_server_message_received(), Channel::new_server_message_received(), ServerSession::queue_msg_as_is(), ClientSession::queue_msg_as_is(), ClientSession::queue_msg_me_as_is(), and ServerSession::send_rejoins().
{
  // FIXME
  return Priority();
}
Copyright © 2005-2007 Carlo Wood. All rights reserved.