ircproxy The Ultimate Cyborg
UserModeMask Struct Reference
#include <UserMode.h>
Detailed Description
For internal use only.
Definition at line 44 of file UserMode.h.
Public Member Functions
UserModeMask ()
Default constructor. Constructs a UserModeMask with no usermodes sets.
UserModeMask (char c)
Construct a UserModeMask with only mode c set.
UserModeMask & operator= (char c)
Reset the mask to just mode c.
UserModeMask & operator|= (char c)
Set mode c.
UserModeMask & operator|= (UserModeMask const &um)
Bitwise OR this mask with um.
UserModeMask & operator &= (char c)
Reset all modes except usermode c.
UserModeMask & operator &= (UserModeMask const &um)
Bitwise AND this mask with um.
UserModeMask & operator^= (char c)
Toggle usermode c.
UserModeMask & operator^= (UserModeMask const &um)
Bitwise XOR this mask with um.
Public Attributes
uint32_t uppercase_modes
A mask for uppercase usermodes. Bit 0 represents 'A' and so on.
uint32_t lowercase_modes
A mask for lowercase usermodes. Bit 0 represents 'a' and so on.
Friends
bool operator== (UserModeMask const &um1, UserModeMask const &um2)
Compare two UserModeMask instances.
bool operator!= (UserModeMask const &um1, UserModeMask const &um2)
Compare two UserModeMask instances.
std::ostream & operator<< (std::ostream &os, UserModeMask const &um)
For debugging purpose; write UserModeMask m to os.
Constructor & Destructor Documentation
UserModeMask::UserModeMask () [inline]
Default constructor. Constructs a UserModeMask with no usermodes sets.
Definition at line 49 of file UserMode.h.
: uppercase_modes(0), lowercase_modes(0) { }
UserModeMask::UserModeMask (char c) [inline]
Construct a UserModeMask with only mode c set.
Definition at line 51 of file UserMode.h.
: uppercase_modes(0), lowercase_modes(0) { *this = c; }
Member Function Documentation
UserModeMask & UserModeMask::operator= (char c)
Reset the mask to just mode c.
Definition at line 44 of file UserMode.cc.
References lowercase_modes, make_lowercase_usermode_mask(), make_uppercase_usermode_mask(), and uppercase_modes.
{
  if (std::isupper(c))
  {
    uppercase_modes = make_uppercase_usermode_mask(c);
    lowercase_modes = 0;
  }
  else if (std::islower(c))
  {
    uppercase_modes = 0;
    lowercase_modes = make_lowercase_usermode_mask(c);
  }
  else if (std::isupper(~c))
  {
    uppercase_modes = ~make_uppercase_usermode_mask(~c);
    lowercase_modes = 0;
  }
  else if (std::islower(~c))
  {
    uppercase_modes = 0;
    lowercase_modes = ~make_lowercase_usermode_mask(~c);
  }
  return *this;
}
UserModeMask & UserModeMask::operator|= (char c)
Set mode c.
Definition at line 69 of file UserMode.cc.
References lowercase_modes, make_lowercase_usermode_mask(), make_uppercase_usermode_mask(), and uppercase_modes.
{
  if (std::isupper(c))
    uppercase_modes |= make_uppercase_usermode_mask(c);
  else if (std::islower(c))
    lowercase_modes |= make_lowercase_usermode_mask(c);
  else if (std::isupper(~c))
    uppercase_modes |= ~make_uppercase_usermode_mask(~c);
  else if (std::islower(~c))
    lowercase_modes |= ~make_lowercase_usermode_mask(~c);
  return *this;
}
UserModeMask & UserModeMask::operator|= (UserModeMask const & um)
Bitwise OR this mask with um.
Definition at line 82 of file UserMode.cc.
References lowercase_modes, and uppercase_modes.
{
  uppercase_modes |= um.uppercase_modes;
  lowercase_modes |= um.lowercase_modes;
  return *this;
}
UserModeMask & UserModeMask::operator &= (char c)
Reset all modes except usermode c.
Definition at line 89 of file UserMode.cc.
References lowercase_modes, make_lowercase_usermode_mask(), make_uppercase_usermode_mask(), and uppercase_modes.
{
  if (std::isupper(c))
    uppercase_modes &= make_uppercase_usermode_mask(c);
  else if (std::islower(c))
    lowercase_modes &= make_lowercase_usermode_mask(c);
  else if (std::isupper(~c))
    uppercase_modes &= ~make_uppercase_usermode_mask(~c);
  else if (std::islower(~c))
    lowercase_modes &= ~make_lowercase_usermode_mask(~c);
  return *this;
}
UserModeMask & UserModeMask::operator &= (UserModeMask const & um)
Bitwise AND this mask with um.
Definition at line 102 of file UserMode.cc.
References lowercase_modes, and uppercase_modes.
{
  uppercase_modes &= um.uppercase_modes;
  lowercase_modes &= um.lowercase_modes;
  return *this;
}
UserModeMask & UserModeMask::operator^= (char c)
Toggle usermode c.
Definition at line 109 of file UserMode.cc.
References lowercase_modes, make_lowercase_usermode_mask(), make_uppercase_usermode_mask(), and uppercase_modes.
{
  if (std::isupper(c))
    uppercase_modes ^= make_uppercase_usermode_mask(c);
  else if (std::islower(c))
    lowercase_modes ^= make_lowercase_usermode_mask(c);
  else if (std::isupper(~c))
    uppercase_modes ^= ~make_uppercase_usermode_mask(~c);
  else if (std::islower(~c))
    lowercase_modes ^= ~make_lowercase_usermode_mask(~c);
  return *this;
}
UserModeMask & UserModeMask::operator^= (UserModeMask const & um)
Bitwise XOR this mask with um.
Definition at line 122 of file UserMode.cc.
References lowercase_modes, and uppercase_modes.
{
  uppercase_modes ^= um.uppercase_modes;
  lowercase_modes ^= um.lowercase_modes;
  return *this;
}
Friends And Related Function Documentation
bool operator== (UserModeMask const & um1, UserModeMask const & um2) [friend]
Compare two UserModeMask instances.
Definition at line 69 of file UserMode.h.
  {
    return um1.lowercase_modes == um2.lowercase_modes &&
           um2.uppercase_modes == um2.uppercase_modes;
  }
bool operator!= (UserModeMask const & um1, UserModeMask const & um2) [friend]
Compare two UserModeMask instances.
Definition at line 76 of file UserMode.h.
  {
    return um1.lowercase_modes != um2.lowercase_modes ||
           um2.uppercase_modes != um2.uppercase_modes;
  }
std::ostream& operator<< (std::ostream & os, UserModeMask const & um) [friend]
For debugging purpose; write UserModeMask m to os.
Definition at line 84 of file UserMode.h.
  {
    os << "\"+";
    char c = 'a';
    for (uint32_t m = 1; c <= 'z'; ++c, m <<= 1)
      if ((um.lowercase_modes & m))
        os << c;
    c = 'A';
    for (uint32_t m = 1; c <= 'z'; ++c, m <<= 1)
      if ((um.uppercase_modes & m))
        os << c;
    return os << '"';
  }
Member Data Documentation
uint32_t UserModeMask::uppercase_modes
A mask for uppercase usermodes. Bit 0 represents 'A' and so on.
Definition at line 45 of file UserMode.h.
Referenced by operator &=(), operator=(), operator^=(), and operator|=().
uint32_t UserModeMask::lowercase_modes
A mask for lowercase usermodes. Bit 0 represents 'a' and so on.
Definition at line 46 of file UserMode.h.
Referenced by operator &=(), operator=(), operator^=(), and operator|=().
The documentation for this struct was generated from the following files:
UserMode.h
UserMode.cc
Copyright © 2005-2007 Carlo Wood. All rights reserved.