ircproxy The Ultimate Cyborg
UserMode.h File Reference
Detailed Description
This file contains the declaration of class UserMode.
Definition in file UserMode.h.
#include <cctype>
#include "Watched.h"
#include "MessageIn.h"
Classes
struct UserModeMask
class UserMode
A class representing a user mode.
Functions
uint32_t make_uppercase_usermode_mask (char c)
uint32_t make_lowercase_usermode_mask (char c)
UserModeMask operator| (UserModeMask const &um, char c)
Return UserModeMask um but with usermode c set.
UserModeMask operator| (UserModeMask const &um1, UserModeMask const &um2)
Return a bitwise OR-ed UserModeMask of um1 and um2.
UserModeMask operator & (UserModeMask const &um, char c)
Return a UserModeMask with only usermode c set, provided it is also set in UserModeMask um.
UserModeMask operator & (UserModeMask const &um1, UserModeMask const &um2)
Return a bitwise AND-ed UserModeMask of um1 and um2.
UserModeMask operator^ (UserModeMask const &um, char c)
Return UserModeMask um with usermode c toggled.
UserModeMask operator^ (UserModeMask const &um1, UserModeMask const &um2)
Return a bitwise XOR-ed UserModeMask of um1 and um2.
Function Documentation
uint32_t make_uppercase_usermode_mask (char c) [inline]
For internal use only.
Definition at line 28 of file UserMode.h.
References ASSERT.
Referenced by UserModeMask::operator &=(), UserModeMask::operator=(), UserModeMask::operator^=(), and UserModeMask::operator|=().
{
  ASSERT(std::isupper(c));
  return 1 << (c - 'A');
}
uint32_t make_lowercase_usermode_mask (char c) [inline]
For internal use only.
Definition at line 36 of file UserMode.h.
References ASSERT.
Referenced by UserModeMask::operator &=(), UserModeMask::operator=(), UserModeMask::operator^=(), and UserModeMask::operator|=().
{
  ASSERT(std::islower(c));
  return 1 << (c - 'a');
}
UserModeMask operator| (UserModeMask const & um, char c) [inline]
Return UserModeMask um but with usermode c set.
Definition at line 101 of file UserMode.h.
{
  UserModeMask result(um);
  return result |= c;
}
UserModeMask operator| (UserModeMask const & um1, UserModeMask const & um2) [inline]
Return a bitwise OR-ed UserModeMask of um1 and um2.
Definition at line 108 of file UserMode.h.
{
  UserModeMask result(um1);
  return result |= um2;
}
UserModeMask operator & (UserModeMask const & um, char c) [inline]
Return a UserModeMask with only usermode c set, provided it is also set in UserModeMask um.
Definition at line 115 of file UserMode.h.
{
  UserModeMask result(um);
  return result &= c;
}
UserModeMask operator & (UserModeMask const & um1, UserModeMask const & um2) [inline]
Return a bitwise AND-ed UserModeMask of um1 and um2.
Definition at line 122 of file UserMode.h.
{
  UserModeMask result(um1);
  return result &= um2;
}
UserModeMask operator^ (UserModeMask const & um, char c) [inline]
Return UserModeMask um with usermode c toggled.
Definition at line 129 of file UserMode.h.
{
  UserModeMask result(um);
  return result ^= c;
}
UserModeMask operator^ (UserModeMask const & um1, UserModeMask const & um2) [inline]
Return a bitwise XOR-ed UserModeMask of um1 and um2.
Definition at line 136 of file UserMode.h.
{
  UserModeMask result(um1);
  return result ^= um2;
}
Copyright © 2005-2007 Carlo Wood. All rights reserved.