ircproxy The Ultimate Cyborg
UserAnswer.cc File Reference
Detailed Description
This file contains the implementation of the UserAnswer events related code.
Definition in file UserAnswer.cc.
#include "sys.h"
#include "debug.h"
#include "UserAnswer.h"
#include "QuestionTarget.h"
#include "ClientSession.h"
#include "Identity.h"
Functions
char const * question_target_name (question_nt number)
Convert question index number into the channel name it belongs to.
Function Documentation
char const* question_target_name (question_nt number)
Convert question index number into the channel name it belongs to.
Definition at line 27 of file UserAnswer.cc.
References network_domain_question, no_related_question, and server_port_question.
Referenced by ServerConnection::do_connect(), Identity::notice_target(), and UserAnswerEventRequestBase::UserAnswerEventRequestBase().
{
  switch(number)
  {
    case network_domain_question:
      return "&NetworkDomain";
    case server_port_question:
      return "&WhatServerPort";
    case no_related_question:
      DoutFatal(dc::core, "Calling question_target_name(no_related_question)");
  }
  return NULL;  // Suppress compiler warning.
}
Copyright © 2005-2007 Carlo Wood. All rights reserved.