ircproxy The Ultimate Cyborg
Watched.h File Reference
Detailed Description
This file contains the definitions of class Watched and declarations related to Watched and expression (events).
Definition in file Watched.h.
#include <set>
#include <boost/shared_ptr.hpp>
#include "debug.h"
#include "ExpressionInterface.h"
#include "Expression.h"
Classes
class WatchedExpression< T >
An expression consisting of a single Watched object.
class Watched< T >
A wrapper class for arbitrary objects of type T that need to be watched.
Functions
template<typename T>
std::ostream & operator<< (std::ostream &os, Watched< T > const &b)
Serialize a Watched object.
template<typename T1, typename T2>
bool operator== (Watched< T1 > const &v1, T2 const &v2)
Compare a Watched object with another object.
template<typename T1, typename T2>
bool operator!= (Watched< T1 > const &v1, T2 const &v2)
Compare a Watched object with another object.
template<typename T1, typename T2>
bool operator< (Watched< T1 > const &v1, T2 const &v2)
Compare a Watched object with another object.
template<typename T1, typename T2>
bool operator<= (Watched< T1 > const &v1, T2 const &v2)
Compare a Watched object with another object.
template<typename T1, typename T2>
bool operator> (Watched< T1 > const &v1, T2 const &v2)
Compare a Watched object with another object.
template<typename T1, typename T2>
bool operator>= (Watched< T1 > const &v1, T2 const &v2)
Compare a Watched object with another object.
template<typename T1, typename T2>
T1 operator & (Watched< T1 > const &v1, T2 const &v2)
Perform a bitwise AND of a Watched object with another object.
template<typename T1, typename T2>
T1 operator| (Watched< T1 > const &v1, T2 const &v2)
Perform a bitwise OR of a Watched object with another object.
template<typename T1, typename T2>
T1 operator^ (Watched< T1 > const &v1, T2 const &v2)
Perform a bitwise XOR of a Watched object with another object.
Function Documentation
template<typename T> std::ostream& operator<< (std::ostream & os, Watched< T > const & b) [inline]
Serialize a Watched object.
Definition at line 236 of file Watched.h.
{
  return os << b.M_value;
}
template<typename T1, typename T2> bool operator== (Watched< T1 > const & v1, T2 const & v2) [inline]
Compare a Watched object with another object.
Definition at line 242 of file Watched.h.
References Watched< T >::value().
{ return v1.value() == v2; }
template<typename T1, typename T2> bool operator!= (Watched< T1 > const & v1, T2 const & v2) [inline]
Compare a Watched object with another object.
Definition at line 244 of file Watched.h.
References Watched< T >::value().
{ return v1.value() != v2; }
template<typename T1, typename T2> bool operator< (Watched< T1 > const & v1, T2 const & v2) [inline]
Compare a Watched object with another object.
Definition at line 246 of file Watched.h.
{ return v1.value() < v2; }
template<typename T1, typename T2> bool operator<= (Watched< T1 > const & v1, T2 const & v2) [inline]
Compare a Watched object with another object.
Definition at line 248 of file Watched.h.
{ return v1.value() <= v2; }
template<typename T1, typename T2> bool operator> (Watched< T1 > const & v1, T2 const & v2) [inline]
Compare a Watched object with another object.
Definition at line 250 of file Watched.h.
References Watched< T >::value().
{ return v1.value() > v2; }
template<typename T1, typename T2> bool operator>= (Watched< T1 > const & v1, T2 const & v2) [inline]
Compare a Watched object with another object.
Definition at line 252 of file Watched.h.
References Watched< T >::value().
{ return v1.value() >= v2; }
template<typename T1, typename T2> T1 operator & (Watched< T1 > const & v1, T2 const & v2) [inline]
Perform a bitwise AND of a Watched object with another object.
Definition at line 254 of file Watched.h.
References Watched< T >::value().
{ return v1.value() & v2; }
template<typename T1, typename T2> T1 operator| (Watched< T1 > const & v1, T2 const & v2) [inline]
Perform a bitwise OR of a Watched object with another object.
Definition at line 256 of file Watched.h.
References Watched< T >::value().
{ return v1.value() | v2; }
template<typename T1, typename T2> T1 operator^ (Watched< T1 > const & v1, T2 const & v2) [inline]
Perform a bitwise XOR of a Watched object with another object.
Definition at line 258 of file Watched.h.
References Watched< T >::value().
{ return v1.value() ^ v2; }
Copyright © 2005-2007 Carlo Wood. All rights reserved.